// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Xunit;

namespace IdentitySvc.Tests;

/// <summary>
/// Unit-level tests for the standard health / probe / version endpoints.
/// Uses WebApplicationFactory to boot the full minimal-API pipeline without external infra.
/// </summary>
public sealed class HealthEndpointsTests(WebApplicationFactory<Program> factory)
    : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly HttpClient _client = factory.CreateClient();

    [Fact]
    public async Task GetHealth_Returns200()
    {
        var response = await _client.GetAsync("/health");
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetLive_Returns200()
    {
        var response = await _client.GetAsync("/live");
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetHealth_ResponseBodyContainsSuccessEnvelope()
    {
        var response = await _client.GetAsync("/health");
        var body     = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);
        Assert.True(doc.RootElement.GetProperty("success").GetBoolean());
    }

    [Fact]
    public async Task GetVersion_Returns200_WithContractVersion()
    {
        var response = await _client.GetAsync("/version");
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = await response.Content.ReadAsStringAsync();
        Assert.Contains("contractVersion", body, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task AllProbes_SetCorrelationIdResponseHeader()
    {
        foreach (var path in new[] { "/health", "/live" })
        {
            var response = await _client.GetAsync(path);
            Assert.True(
                response.Headers.Contains("X-Correlation-Id"),
                $"{path} must echo X-Correlation-Id header");
        }
    }

    [Fact]
    public async Task AllProbes_SetSecurityHeaders()
    {
        var response = await _client.GetAsync("/health");
        Assert.True(response.Headers.Contains("X-Content-Type-Options"),
            "X-Content-Type-Options security header must be present");
    }
}
