# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""dkd_platform — generated DOKANDAR platform SDK (Python)."""
from ._provenance import GENERATOR_VERSION, CONTRACT_VERSION
from . import ids, money, topics, config, enums, errors, dto, events, schema, security, validation, apidocs
from . import custody_hash  # hand-authored platform primitive (CustodyHash Spec v2, not dkdgen)
from . import dbexec, outbox, inbox, dlq  # hand-authored effectively-once quartet (PL-02, not dkdgen)
from . import uuid7, idempotency, traceparent, http_status  # hand-authored SDK helpers (PL-03..06, not dkdgen)

__version__ = "1.0.0"
__all__ = ["ids","money","topics","config","enums","errors","dto","events","schema","security","validation","apidocs","custody_hash","dbexec","outbox","inbox","dlq","uuid7","idempotency","traceparent","http_status"]
