# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

GENERATOR = "dkdgen"
GENERATOR_VERSION = "1.0.0"
CONTRACT_VERSION = "1.0.0"
BUILD_TIME = "2026-06-29T00:00:00Z"
BUILD_COMMIT = "source"
