# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""API Documentation Standard helper (Python / FastAPI).

Centralizes the platform OpenAPI/Swagger behavior so every service inherits identical docs with one
call: Swagger UI at /docs, OpenAPI JSON at /swagger/v1/swagger.json, OpenAPI document "v1", a Bearer
(JWT) security scheme, and the standard title/description. FastAPI's built-in OpenAPI + Swagger UI is
an implementation detail of this helper.

Usage:
    from dkd_platform import apidocs
    app = FastAPI(**apidocs.platform_docs_kwargs(cfg.service_name), lifespan=lifespan)
    ...  # register routes
    apidocs.configure_platform_docs(app)   # after routes: injects the Bearer security scheme
"""
from typing import Any

DOCS_URL = "/docs"
OPENAPI_URL = "/swagger/v1/swagger.json"
# PL-08 (hand-authored extension): pin the emitted OpenAPI spec version fleet-wide to 3.1.0,
# ending the 3.0.1/3.0.3/3.1 drift. `openapi.json` (the `openapi` field) is the source of truth.
OPENAPI_VERSION = "3.1.0"
DOCS_CSP = (
    "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data:; font-src 'self'; connect-src 'self'"
)


def platform_docs_kwargs(title: str) -> dict:
    """FastAPI constructor kwargs realising the API Documentation Standard (UI /docs, JSON /swagger/v1/swagger.json)."""
    return {
        "title": title,
        "version": "v1",
        "description": title + " REST API.",
        "docs_url": DOCS_URL,
        "openapi_url": OPENAPI_URL,
        "redoc_url": None,
    }


def is_docs_path(path: str) -> bool:
    """True for the Swagger UI / OpenAPI paths — used to relax CSP for the UI only."""
    return path.startswith("/docs") or path.startswith("/swagger")


def pin_openapi_version(schema: dict) -> dict:
    """Force the OpenAPI document's spec version to the pinned OPENAPI_VERSION (3.1.0).

    FastAPI versions have emitted 3.0.1 / 3.0.3 / 3.1.0 depending on release; pinning here makes the
    served `openapi.json` deterministic across the fleet. Mutates and returns the same schema dict."""
    schema["openapi"] = OPENAPI_VERSION
    return schema


def configure_platform_docs(app: Any) -> None:
    """Install a Bearer (JWT) security scheme into the generated OpenAPI document (call after routes)."""
    from fastapi.openapi.utils import get_openapi

    def _openapi() -> dict:
        if app.openapi_schema:
            return app.openapi_schema
        schema = get_openapi(
            title=app.title, version=app.version,
            description=getattr(app, "description", None), routes=app.routes,
        )
        pin_openapi_version(schema)  # PL-08: deterministic 3.1.0 across the fleet
        components = schema.setdefault("components", {})
        components.setdefault("securitySchemes", {})["Bearer"] = {
            "type": "http", "scheme": "bearer", "bearerFormat": "JWT",
            "description": "JWT bearer token (injected by the API gateway in production).",
        }
        app.openapi_schema = schema
        return schema

    app.openapi = _openapi
