# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Canon-named operational constants (configuration.yaml). Values are verbatim from canon."""
from __future__ import annotations

COOLING_OFF_WINDOW = 259200000  # 72h — finance.escrow
ESCROW_ABANDON_TTL = 604800000  # 7d — finance.escrow
NIL_ROLLUP_MAX_LAG = 60000  # 60s — inventory.nil
B2_B_DELIVERY_MIN_LEAD = 86400000  # 24h — b2b.contractterms
MONEY_CUSTODY_RPO = 0  #  — finance+custody

CONSTANTS = {"COOLING_OFF_WINDOW": COOLING_OFF_WINDOW, "ESCROW_ABANDON_TTL": ESCROW_ABANDON_TTL, "NIL_ROLLUP_MAX_LAG": NIL_ROLLUP_MAX_LAG, "B2B_DELIVERY_MIN_LEAD": B2_B_DELIVERY_MIN_LEAD, "MONEY_CUSTODY_RPO": MONEY_CUSTODY_RPO}
