# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Common DTOs: the {success,data,error,meta} envelope, cursor pagination, trace/audit metadata."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Generic, TypeVar, Optional, List, Any, Dict
from .errors import ProblemDetails

T = TypeVar("T")


@dataclass
class PageMeta:
    next_cursor: Optional[str] = None
    has_more: bool = False
    limit: int = 0


@dataclass
class TraceMetadata:
    trace_id: Optional[str] = None
    span_id: Optional[str] = None
    correlation_id: Optional[str] = None


@dataclass
class AuditMetadata:
    actor_did: Optional[str] = None
    occurred_at_ms: Optional[int] = None
    request_id: Optional[str] = None


@dataclass
class Meta:
    page: Optional[PageMeta] = None
    trace: Optional[TraceMetadata] = None
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Response(Generic[T]):
    """The canonical external REST envelope (EF §7)."""
    success: bool
    data: Optional[T] = None
    error: Optional[ProblemDetails] = None
    meta: Optional[Meta] = None

    @classmethod
    def ok(cls, data: T, meta: Optional[Meta] = None) -> "Response[T]":
        return cls(success=True, data=data, meta=meta)

    @classmethod
    def fail(cls, error: ProblemDetails, meta: Optional[Meta] = None) -> "Response[T]":
        return cls(success=False, error=error, meta=meta)


@dataclass
class Page(Generic[T]):
    items: List[T]
    page: PageMeta
