# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Canonical enum families (glossary.yaml; FR-IDN-310). Values transcribed verbatim."""
from __future__ import annotations
from enum import Enum

class KycTiers(str, Enum):
    """source=FR-IDN-005; exhaustive=True"""
    V0 = "V0"
    V1 = "V1"
    V2 = "V2"
    V3 = "V3"

class FraudDetectors(str, Enum):
    """source=BA fraud dashboard; exhaustive=False"""
    HOARDING = "HOARDING"
    PASSPORT_FORGERY = "PASSPORT_FORGERY"
    GHOST_SPLIT = "GHOST_SPLIT"
    MFS_STRUCTURING = "MFS_STRUCTURING"
    SUBSIDY_DUP = "SUBSIDY_DUP"
    CIRCULAR_TRADE = "CIRCULAR_TRADE"
    VELOCITY_ANOMALY = "VELOCITY_ANOMALY"
    GEO_IMPOSSIBLE = "GEO_IMPOSSIBLE"
    COLLUSION_RING = "COLLUSION_RING"
    # NOTE: contract marks this family non-exhaustive (illustrative); extend on Phase-2 transcription.

class FraudCaseStates(str, Enum):
    """source=enum-registry S-4; exhaustive=False"""
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    SUBSTANTIATED = "SUBSTANTIATED"
    ENFORCED = "ENFORCED"
    DISMISSED = "DISMISSED"
    # NOTE: contract marks this family non-exhaustive (illustrative); extend on Phase-2 transcription.

class EnforcementActions(str, Enum):
    """source=enum-registry S-4; exhaustive=False"""
    WARN = "WARN"
    RESTRICT_LISTING = "RESTRICT_LISTING"
    SUSPEND = "SUSPEND"
    BLACKLIST = "BLACKLIST"
    LICENSE_REVOKE = "LICENSE_REVOKE"
    # NOTE: contract marks this family non-exhaustive (illustrative); extend on Phase-2 transcription.

class OversightRoles(str, Enum):
    """source=enum-registry S-4; exhaustive=False"""
    ANALYST = "ANALYST"
    INVESTIGATOR = "INVESTIGATOR"
    ENFORCEMENT_OFFICER = "ENFORCEMENT_OFFICER"
    APPROVER = "APPROVER"
    SUPER_ADMIN = "SUPER_ADMIN"
    # NOTE: contract marks this family non-exhaustive (illustrative); extend on Phase-2 transcription.

class PartyActorCodes(str, Enum):
    """source=BA actor table; exhaustive=False"""
    FARIA = "FARIA"
    WHOLESALER = "WHOLESALER"
    RETAIL = "RETAIL"
    GOV = "GOV"
    PERSON = "PERSON"
    ORG = "ORG"
    # NOTE: contract marks this family non-exhaustive (illustrative); extend on Phase-2 transcription.

class CommodityUnits(str, Enum):
    """source=BA/DM; exhaustive=False"""
    SEER = "seer"
    MAUND = "maund"
    BOSTA = "bosta"
    # NOTE: contract marks this family non-exhaustive (illustrative); extend on Phase-2 transcription.
