# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Error taxonomy (error-codes.yaml): dokandar.<context>.<category>.<reason> (RFC-7807).

Concrete codes are NEEDS-INFO in the frozen contracts (error-codes.yaml codes: []), so this module
provides the format-enforcing BUILDER + the context-slug enum + the typed exception hierarchy +
ProblemDetails — never a fabricated code list. Register codes when the contract is populated.
"""
from __future__ import annotations
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Dict, Any

CONTEXT_SLUGS = ('identity', 'catalog', 'custody', 'provenance', 'inventory', 'b2c', 'b2b', 'finance', 'logistics', 'fraud', 'government', 'analytics', 'platform', 'edge')
_CODE_RE = re.compile(r"^dokandar\.([a-z]+)\.([a-z0-9_]+)\.([a-z0-9_]+)$")


class ContextSlug(str, Enum):
    IDENTITY = "identity"
    CATALOG = "catalog"
    CUSTODY = "custody"
    PROVENANCE = "provenance"
    INVENTORY = "inventory"
    B2C = "b2c"
    B2B = "b2b"
    FINANCE = "finance"
    LOGISTICS = "logistics"
    FRAUD = "fraud"
    GOVERNMENT = "government"
    ANALYTICS = "analytics"
    PLATFORM = "platform"
    EDGE = "edge"


def error_code(context: str, category: str, reason: str) -> str:
    code = "dokandar.%s.%s.%s" % (context, category, reason)
    if context not in CONTEXT_SLUGS:
        raise ValueError("unknown context slug: %s" % context)
    if not _CODE_RE.match(code):
        raise ValueError("error code violates taxonomy: %s" % code)
    return code


@dataclass
class ProblemDetails:
    """RFC-7807 problem+json carried in the response envelope `error`."""
    type: str
    title: str
    status: int
    code: str
    detail: Optional[str] = None
    instance: Optional[str] = None
    trace_id: Optional[str] = None
    extensions: Dict[str, Any] = field(default_factory=dict)


class DokandarError(Exception):
    """Base typed exception. Subclasses map to problem categories."""
    http_status = 500

    def __init__(self, code: str, message: str, detail: Optional[str] = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.detail = detail

    def to_problem(self) -> ProblemDetails:
        return ProblemDetails(type="about:blank", title=self.message,
                              status=self.http_status, code=self.code, detail=self.detail)


class ValidationError(DokandarError):
    http_status = 400


class BusinessError(DokandarError):
    http_status = 409


class InfrastructureError(DokandarError):
    http_status = 503
