# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Event envelope/base + headers + metadata + topic binding + serializer protocol.

Per-event PAYLOAD classes are FRAMEWORK-ONLY here: schema-registry.yaml carries all 59 subjects with
schema=NEEDS-INFO, so no payload fields exist in the frozen contracts. EventEnvelope is generic over
the payload; concrete payload types are registered when the schema contract is populated (Phase 2).
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Generic, TypeVar, Dict, Any, Optional, Protocol
from .topics import topic_meta, TopicMeta

P = TypeVar("P")


@dataclass(frozen=True)
class EventHeaders:
    event_id: str            # inbox dedup key (effectively-once)
    occurred_at_ms: int
    producer_context: int
    partition_key: str       # per-aggregate ordering key
    correlation_id: Optional[str] = None
    trace_id: Optional[str] = None
    schema_version: int = 1


@dataclass(frozen=True)
class EventMetadata:
    topic: str
    meta: TopicMeta

    @staticmethod
    def for_topic(topic: str) -> "EventMetadata":
        return EventMetadata(topic=topic, meta=topic_meta(topic))


@dataclass
class EventEnvelope(Generic[P]):
    headers: EventHeaders
    topic: str
    payload: P               # payload type is contract-populated in Phase 2 (NEEDS-INFO)


class PayloadSerializer(Protocol[P]):
    """Extension point. Concrete (de)serializers bind once payload schemas are published."""
    def serialize(self, payload: P) -> bytes: ...
    def deserialize(self, data: bytes) -> P: ...
