# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source
#
# PL-04 (hand-authored extension): the prefixed-ID body is now validated as a UUIDv7 — the version
# nibble + variant bits are checked (see uuid7.py), so a v4 or garbage body is rejected. A leading
# category segment (e.g. GP-<cat>-<uuid7>) is permitted; the TRAILING UUID is what gets validated.

"""Strongly-typed identifiers (ids.yaml). No raw-string IDs."""
from __future__ import annotations

from . import uuid7 as _uuid7

class PrefixedId:
    """Base for prefixed canonical IDs. Validates the canonical prefix AND that the embedded body
    ends in a UUIDv7 (an optional `-<category>-` segment may precede it)."""
    PREFIX = ""
    OWNER_CONTEXT = 0
    IMMUTABLE = False

    __slots__ = ("value",)

    def __init__(self, value: str):
        if not isinstance(value, str) or not value.startswith(self.PREFIX) or len(value) <= len(self.PREFIX):
            raise ValueError("%s must start with %r and carry a body" % (type(self).__name__, self.PREFIX))
        body = value[len(self.PREFIX):]
        uuid_part = body[-_uuid7.UUID_STR_LEN:]
        if not _uuid7.is_valid(uuid_part):
            raise ValueError("%s body must end in a UUIDv7: %r" % (type(self).__name__, value))
        # anything before the trailing UUID must be a single "<category>-" segment (no stray text)
        prefixed = body[:-_uuid7.UUID_STR_LEN]
        if prefixed and (not prefixed.endswith("-") or "-" in prefixed[:-1]):
            raise ValueError("%s has an unexpected segment before its UUIDv7: %r" % (type(self).__name__, value))
        self.value = value

    @classmethod
    def of(cls, value: str):
        return cls(value)

    @classmethod
    def generate(cls, category: str = "") -> "PrefixedId":
        """Mint a fresh, valid ID: PREFIX [+ category "-"] + a new UUIDv7."""
        seg = (category + "-") if category else ""
        return cls(cls.PREFIX + seg + _uuid7.generate())

    def __str__(self): return self.value
    def __eq__(self, o): return type(o) is type(self) and o.value == self.value
    def __hash__(self): return hash((type(self).__name__, self.value))
    def __repr__(self): return "%s(%r)" % (type(self).__name__, self.value)

class DID(PrefixedId):
    PREFIX = "did:dokandar:"
    OWNER_CONTEXT = 1  # identity
    IMMUTABLE = True

class PPID(PrefixedId):
    PREFIX = "PP-"
    OWNER_CONTEXT = 3  # custody
    IMMUTABLE = False

class GPID(PrefixedId):
    PREFIX = "GP-"
    OWNER_CONTEXT = 2  # catalog
    IMMUTABLE = False

class ORD(PrefixedId):
    PREFIX = "ORD-"
    OWNER_CONTEXT = 6  # b2c
    IMMUTABLE = False

class TRD(PrefixedId):
    PREFIX = "TRD-"
    OWNER_CONTEXT = 7  # b2b
    IMMUTABLE = False

class WLT(PrefixedId):
    PREFIX = "WLT-"
    OWNER_CONTEXT = 8  # finance
    IMMUTABLE = False

class ESC(PrefixedId):
    PREFIX = "ESC-"
    OWNER_CONTEXT = 8  # finance
    IMMUTABLE = False

class TXN(PrefixedId):
    PREFIX = "TXN-"
    OWNER_CONTEXT = 8  # finance
    IMMUTABLE = False

class SHP(PrefixedId):
    PREFIX = "SHP-"
    OWNER_CONTEXT = 9  # logistics
    IMMUTABLE = False

class NTF(PrefixedId):
    PREFIX = "NTF-"
    OWNER_CONTEXT = 13  # platform
    IMMUTABLE = False

class MFSA(PrefixedId):
    PREFIX = "MFSA-"
    OWNER_CONTEXT = 8  # finance
    IMMUTABLE = False

ALL_ID_TYPES = [DID, PPID, GPID, ORD, TRD, WLT, ESC, TXN, SHP, NTF, MFSA]
