# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Money is int64 poisha; Timestamp is int64 unix-ms UTC (ids.yaml types)."""
from __future__ import annotations

POISHA_PER_BDT = 100


class Money:
    """Integer poisha. Float/decimal/string money is banned (DM type conventions)."""
    __slots__ = ("poisha",)

    def __init__(self, poisha: int):
        if not isinstance(poisha, int) or isinstance(poisha, bool):
            raise TypeError("Money must be int64 poisha, got %r" % type(poisha).__name__)
        self.poisha = poisha

    @classmethod
    def of_bdt(cls, bdt: int) -> "Money":
        return cls(bdt * POISHA_PER_BDT)

    def __eq__(self, o): return isinstance(o, Money) and o.poisha == self.poisha
    def __hash__(self): return hash(self.poisha)
    def __repr__(self): return "Money(%d poisha)" % self.poisha


class Timestamp:
    """Unix milliseconds, UTC (int64)."""
    __slots__ = ("epoch_ms",)

    def __init__(self, epoch_ms: int):
        if not isinstance(epoch_ms, int) or isinstance(epoch_ms, bool):
            raise TypeError("Timestamp must be int64 epoch_ms")
        self.epoch_ms = epoch_ms

    def __eq__(self, o): return isinstance(o, Timestamp) and o.epoch_ms == self.epoch_ms
    def __hash__(self): return hash(self.epoch_ms)
    def __repr__(self): return "Timestamp(%d)" % self.epoch_ms
