# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Schema-registry metadata (schema-registry.yaml): subjects + compatibility + version helpers.

Per-subject JSON-Schema is NEEDS-INFO in the frozen contracts, so get_schema() is an
extension point (raises until populated) — never a fabricated schema.
"""
from __future__ import annotations
from dataclasses import dataclass
from enum import Enum
from typing import Dict, Optional

class Compatibility(str, Enum):
    BACKWARD = "BACKWARD"

@dataclass(frozen=True)
class SubjectInfo:
    subject: str
    topic: str
    compatibility: str
    schema_status: str

SUBJECTS: Dict[str, SubjectInfo] = {
    "identity.party.PartyRegistered.v1": SubjectInfo("identity.party.PartyRegistered.v1", "identity.party.PartyRegistered.v1", "BACKWARD", "NEEDS-INFO"),
    "identity.party.KYCApproved.v1": SubjectInfo("identity.party.KYCApproved.v1", "identity.party.KYCApproved.v1", "BACKWARD", "NEEDS-INFO"),
    "identity.party.KYCTierChanged.v1": SubjectInfo("identity.party.KYCTierChanged.v1", "identity.party.KYCTierChanged.v1", "BACKWARD", "NEEDS-INFO"),
    "identity.party.KYCRejected.v1": SubjectInfo("identity.party.KYCRejected.v1", "identity.party.KYCRejected.v1", "BACKWARD", "NEEDS-INFO"),
    "identity.party.PartySuspended.v1": SubjectInfo("identity.party.PartySuspended.v1", "identity.party.PartySuspended.v1", "BACKWARD", "NEEDS-INFO"),
    "identity.party.PartyReactivated.v1": SubjectInfo("identity.party.PartyReactivated.v1", "identity.party.PartyReactivated.v1", "BACKWARD", "NEEDS-INFO"),
    "catalog.product.ProductCreated.v1": SubjectInfo("catalog.product.ProductCreated.v1", "catalog.product.ProductCreated.v1", "BACKWARD", "NEEDS-INFO"),
    "catalog.product.ProductPublished.v1": SubjectInfo("catalog.product.ProductPublished.v1", "catalog.product.ProductPublished.v1", "BACKWARD", "NEEDS-INFO"),
    "catalog.product.ProductDeprecated.v1": SubjectInfo("catalog.product.ProductDeprecated.v1", "catalog.product.ProductDeprecated.v1", "BACKWARD", "NEEDS-INFO"),
    "catalog.product.ProductPriceRuleAdded.v1": SubjectInfo("catalog.product.ProductPriceRuleAdded.v1", "catalog.product.ProductPriceRuleAdded.v1", "BACKWARD", "NEEDS-INFO"),
    "catalog.product.ProductMasterDataUpdated.v1": SubjectInfo("catalog.product.ProductMasterDataUpdated.v1", "catalog.product.ProductMasterDataUpdated.v1", "BACKWARD", "NEEDS-INFO"),
    "custody.passport.CustodyInitialized.v1": SubjectInfo("custody.passport.CustodyInitialized.v1", "custody.passport.CustodyInitialized.v1", "BACKWARD", "NEEDS-INFO"),
    "custody.passport.CustodyTransferred.v1": SubjectInfo("custody.passport.CustodyTransferred.v1", "custody.passport.CustodyTransferred.v1", "BACKWARD", "NEEDS-INFO"),
    "custody.passport.CustodySplit.v1": SubjectInfo("custody.passport.CustodySplit.v1", "custody.passport.CustodySplit.v1", "BACKWARD", "NEEDS-INFO"),
    "custody.passport.CustodyMerged.v1": SubjectInfo("custody.passport.CustodyMerged.v1", "custody.passport.CustodyMerged.v1", "BACKWARD", "NEEDS-INFO"),
    "custody.passport.ProductRecalled.v1": SubjectInfo("custody.passport.ProductRecalled.v1", "custody.passport.ProductRecalled.v1", "BACKWARD", "NEEDS-INFO"),
    "custody.passport.CustodialSigned.v1": SubjectInfo("custody.passport.CustodialSigned.v1", "custody.passport.CustodialSigned.v1", "BACKWARD", "NEEDS-INFO"),
    "b2c.order.OrderPlaced.v1": SubjectInfo("b2c.order.OrderPlaced.v1", "b2c.order.OrderPlaced.v1", "BACKWARD", "NEEDS-INFO"),
    "b2c.order.PaymentConfirmed.v1": SubjectInfo("b2c.order.PaymentConfirmed.v1", "b2c.order.PaymentConfirmed.v1", "BACKWARD", "NEEDS-INFO"),
    "b2c.order.OrderProcessingStarted.v1": SubjectInfo("b2c.order.OrderProcessingStarted.v1", "b2c.order.OrderProcessingStarted.v1", "BACKWARD", "NEEDS-INFO"),
    "b2c.order.OrderShipped.v1": SubjectInfo("b2c.order.OrderShipped.v1", "b2c.order.OrderShipped.v1", "BACKWARD", "NEEDS-INFO"),
    "b2c.order.OrderDelivered.v1": SubjectInfo("b2c.order.OrderDelivered.v1", "b2c.order.OrderDelivered.v1", "BACKWARD", "NEEDS-INFO"),
    "b2c.order.OrderCancelled.v1": SubjectInfo("b2c.order.OrderCancelled.v1", "b2c.order.OrderCancelled.v1", "BACKWARD", "NEEDS-INFO"),
    "b2c.order.OrderRefunded.v1": SubjectInfo("b2c.order.OrderRefunded.v1", "b2c.order.OrderRefunded.v1", "BACKWARD", "NEEDS-INFO"),
    "b2b.tradeorder.TradeOrderCreated.v1": SubjectInfo("b2b.tradeorder.TradeOrderCreated.v1", "b2b.tradeorder.TradeOrderCreated.v1", "BACKWARD", "NEEDS-INFO"),
    "b2b.tradeorder.MarginPosted.v1": SubjectInfo("b2b.tradeorder.MarginPosted.v1", "b2b.tradeorder.MarginPosted.v1", "BACKWARD", "NEEDS-INFO"),
    "b2b.tradeorder.TradeActivated.v1": SubjectInfo("b2b.tradeorder.TradeActivated.v1", "b2b.tradeorder.TradeActivated.v1", "BACKWARD", "NEEDS-INFO"),
    "b2b.tradeorder.SettlementInitiated.v1": SubjectInfo("b2b.tradeorder.SettlementInitiated.v1", "b2b.tradeorder.SettlementInitiated.v1", "BACKWARD", "NEEDS-INFO"),
    "b2b.tradeorder.TradeSettled.v1": SubjectInfo("b2b.tradeorder.TradeSettled.v1", "b2b.tradeorder.TradeSettled.v1", "BACKWARD", "NEEDS-INFO"),
    "b2b.tradeorder.TradeDisputed.v1": SubjectInfo("b2b.tradeorder.TradeDisputed.v1", "b2b.tradeorder.TradeDisputed.v1", "BACKWARD", "NEEDS-INFO"),
    "b2b.tradeorder.TradeCancelled.v1": SubjectInfo("b2b.tradeorder.TradeCancelled.v1", "b2b.tradeorder.TradeCancelled.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.WalletCreated.v1": SubjectInfo("finance.wallet.WalletCreated.v1", "finance.wallet.WalletCreated.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.MFSAccountRegistered.v1": SubjectInfo("finance.wallet.MFSAccountRegistered.v1", "finance.wallet.MFSAccountRegistered.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.MFSAccountVerified.v1": SubjectInfo("finance.wallet.MFSAccountVerified.v1", "finance.wallet.MFSAccountVerified.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.WalletCredited.v1": SubjectInfo("finance.wallet.WalletCredited.v1", "finance.wallet.WalletCredited.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.WalletDebited.v1": SubjectInfo("finance.wallet.WalletDebited.v1", "finance.wallet.WalletDebited.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.WalletFrozen.v1": SubjectInfo("finance.wallet.WalletFrozen.v1", "finance.wallet.WalletFrozen.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.MFSWithdrawalInitiated.v1": SubjectInfo("finance.wallet.MFSWithdrawalInitiated.v1", "finance.wallet.MFSWithdrawalInitiated.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.MFSWithdrawalConfirmed.v1": SubjectInfo("finance.wallet.MFSWithdrawalConfirmed.v1", "finance.wallet.MFSWithdrawalConfirmed.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.wallet.MFSWithdrawalFailed.v1": SubjectInfo("finance.wallet.MFSWithdrawalFailed.v1", "finance.wallet.MFSWithdrawalFailed.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.escrow.EscrowCreated.v1": SubjectInfo("finance.escrow.EscrowCreated.v1", "finance.escrow.EscrowCreated.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.escrow.EscrowReleased.v1": SubjectInfo("finance.escrow.EscrowReleased.v1", "finance.escrow.EscrowReleased.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.escrow.SettlementHoldReleased.v1": SubjectInfo("finance.escrow.SettlementHoldReleased.v1", "finance.escrow.SettlementHoldReleased.v1", "BACKWARD", "NEEDS-INFO"),
    "finance.escrow.EscrowReversed.v1": SubjectInfo("finance.escrow.EscrowReversed.v1", "finance.escrow.EscrowReversed.v1", "BACKWARD", "NEEDS-INFO"),
    "logistics.shipment.ShipmentCreated.v1": SubjectInfo("logistics.shipment.ShipmentCreated.v1", "logistics.shipment.ShipmentCreated.v1", "BACKWARD", "NEEDS-INFO"),
    "logistics.shipment.RiderAssigned.v1": SubjectInfo("logistics.shipment.RiderAssigned.v1", "logistics.shipment.RiderAssigned.v1", "BACKWARD", "NEEDS-INFO"),
    "logistics.shipment.PickupRecorded.v1": SubjectInfo("logistics.shipment.PickupRecorded.v1", "logistics.shipment.PickupRecorded.v1", "BACKWARD", "NEEDS-INFO"),
    "logistics.shipment.DeliveryRecorded.v1": SubjectInfo("logistics.shipment.DeliveryRecorded.v1", "logistics.shipment.DeliveryRecorded.v1", "BACKWARD", "NEEDS-INFO"),
    "logistics.shipment.ShipmentCancelled.v1": SubjectInfo("logistics.shipment.ShipmentCancelled.v1", "logistics.shipment.ShipmentCancelled.v1", "BACKWARD", "NEEDS-INFO"),
    "logistics.shipment.DeliveryFailed.v1": SubjectInfo("logistics.shipment.DeliveryFailed.v1", "logistics.shipment.DeliveryFailed.v1", "BACKWARD", "NEEDS-INFO"),
    "fraud.enforcement.FraudSignalRaised.v1": SubjectInfo("fraud.enforcement.FraudSignalRaised.v1", "fraud.enforcement.FraudSignalRaised.v1", "BACKWARD", "NEEDS-INFO"),
    "fraud.enforcement.AccountHeld.v1": SubjectInfo("fraud.enforcement.AccountHeld.v1", "fraud.enforcement.AccountHeld.v1", "BACKWARD", "NEEDS-INFO"),
    "fraud.enforcement.AccountHoldReleased.v1": SubjectInfo("fraud.enforcement.AccountHoldReleased.v1", "fraud.enforcement.AccountHoldReleased.v1", "BACKWARD", "NEEDS-INFO"),
    "government.oversight.RecallDirectiveIssued.v1": SubjectInfo("government.oversight.RecallDirectiveIssued.v1", "government.oversight.RecallDirectiveIssued.v1", "BACKWARD", "NEEDS-INFO"),
    "government.oversight.TradeFreezeDirective.v1": SubjectInfo("government.oversight.TradeFreezeDirective.v1", "government.oversight.TradeFreezeDirective.v1", "BACKWARD", "NEEDS-INFO"),
    "government.oversight.WalletFreezeDirective.v1": SubjectInfo("government.oversight.WalletFreezeDirective.v1", "government.oversight.WalletFreezeDirective.v1", "BACKWARD", "NEEDS-INFO"),
    "platform.scheduler.CoolingOffExpired.v1": SubjectInfo("platform.scheduler.CoolingOffExpired.v1", "platform.scheduler.CoolingOffExpired.v1", "BACKWARD", "NEEDS-INFO"),
    "platform.scheduler.EscrowExpired.v1": SubjectInfo("platform.scheduler.EscrowExpired.v1", "platform.scheduler.EscrowExpired.v1", "BACKWARD", "NEEDS-INFO"),
    "platform.scheduler.NILRollupRefresh.v1": SubjectInfo("platform.scheduler.NILRollupRefresh.v1", "platform.scheduler.NILRollupRefresh.v1", "BACKWARD", "NEEDS-INFO"),
}

def subject_for(topic: str) -> str:
    return SUBJECTS[topic].subject

def get_schema(subject: str):
    info = SUBJECTS[subject]
    raise NotImplementedError(
        "schema for %s is NEEDS-INFO in frozen contracts (Phase-2 transcription)" % subject)

def is_compatible(subject: str, new_version: int, old_version: int) -> bool:
    # BACKWARD within a major: a higher minor/patch reads older data (EF §8.4).
    return new_version >= old_version
