# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Security helpers: access principles, JWT claim names, correlation/trace propagation.

Role families are the canonical glossary enums (see enums.py: KycTiers/OversightRoles/
EnforcementActions) — defined once there. The full permission MATRIX is NEEDS-INFO
(permissions.yaml matrix: NEEDS-INFO); this module provides principle constants only.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional, Dict

PRINCIPLES = {
    "R1-custody-sole-writer": "Only custody-ledger-svc writes custody.*; all others are read-only consumers.",
    "R2-finance-isolation": "Finance DB reachable only by Finance; DID->wallet resolution happens inside Finance.",
    "R4-four-eyes": "Finance/Custody/Fraud/Government mutations require two DISTINCT human approvers (approver2 != approver1); only an enumerated narrow reversible-hold set is autonomous.",
    "R5-government-readonly": "Government has SELECT-only grants; intervenes on operational aggregates only via audited four-eyes directives.",
    "read-only-contexts": "Provenance(#4), Inventory(#5 vs custody), Analytics(#12) are read-only projections; never write the source of truth.",
    "pii-confinement": "PII lives only in Identity(#1); other contexts resolve via the Identity OHS; payloads carry IDs only (R6).",
}

class JwtClaims:
    """JWT claim names used fleet-wide (SA security; ABAC/RBAC via Identity PDP)."""
    SUBJECT_DID = "sub"
    KYC_TIER = "kyc_tier"
    ROLES = "roles"
    CORRELATION_ID = "cid"

@dataclass
class CorrelationContext:
    correlation_id: Optional[str] = None
    trace_id: Optional[str] = None
    actor_did: Optional[str] = None

    def headers(self) -> Dict[str, str]:
        h = {}
        if self.correlation_id: h["x-correlation-id"] = self.correlation_id
        if self.trace_id: h["traceparent"] = self.trace_id
        return h
