# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Kafka topics + RabbitMQ queues (messaging.yaml). Cross-context = Kafka only (R6)."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Tuple

@dataclass(frozen=True)
class TopicMeta:
    name: str
    producer: int
    key: str
    consumers: Tuple[int, ...]
    context: str
    aggregate: str
    event: str
    version: int

@dataclass(frozen=True)
class QueueMeta:
    name: str
    context: int
    purpose: str
    pii: bool

class KafkaTopics:
    """59 cross-context Published-Language topics (R6)."""
    IDENTITY_PARTY_PARTY_REGISTERED_V1 = "identity.party.PartyRegistered.v1"
    IDENTITY_PARTY_KYCAPPROVED_V1 = "identity.party.KYCApproved.v1"
    IDENTITY_PARTY_KYCTIER_CHANGED_V1 = "identity.party.KYCTierChanged.v1"
    IDENTITY_PARTY_KYCREJECTED_V1 = "identity.party.KYCRejected.v1"
    IDENTITY_PARTY_PARTY_SUSPENDED_V1 = "identity.party.PartySuspended.v1"
    IDENTITY_PARTY_PARTY_REACTIVATED_V1 = "identity.party.PartyReactivated.v1"
    CATALOG_PRODUCT_PRODUCT_CREATED_V1 = "catalog.product.ProductCreated.v1"
    CATALOG_PRODUCT_PRODUCT_PUBLISHED_V1 = "catalog.product.ProductPublished.v1"
    CATALOG_PRODUCT_PRODUCT_DEPRECATED_V1 = "catalog.product.ProductDeprecated.v1"
    CATALOG_PRODUCT_PRODUCT_PRICE_RULE_ADDED_V1 = "catalog.product.ProductPriceRuleAdded.v1"
    CATALOG_PRODUCT_PRODUCT_MASTER_DATA_UPDATED_V1 = "catalog.product.ProductMasterDataUpdated.v1"
    CUSTODY_PASSPORT_CUSTODY_INITIALIZED_V1 = "custody.passport.CustodyInitialized.v1"
    CUSTODY_PASSPORT_CUSTODY_TRANSFERRED_V1 = "custody.passport.CustodyTransferred.v1"
    CUSTODY_PASSPORT_CUSTODY_SPLIT_V1 = "custody.passport.CustodySplit.v1"
    CUSTODY_PASSPORT_CUSTODY_MERGED_V1 = "custody.passport.CustodyMerged.v1"
    CUSTODY_PASSPORT_PRODUCT_RECALLED_V1 = "custody.passport.ProductRecalled.v1"
    CUSTODY_PASSPORT_CUSTODIAL_SIGNED_V1 = "custody.passport.CustodialSigned.v1"
    B2C_ORDER_ORDER_PLACED_V1 = "b2c.order.OrderPlaced.v1"
    B2C_ORDER_PAYMENT_CONFIRMED_V1 = "b2c.order.PaymentConfirmed.v1"
    B2C_ORDER_ORDER_PROCESSING_STARTED_V1 = "b2c.order.OrderProcessingStarted.v1"
    B2C_ORDER_ORDER_SHIPPED_V1 = "b2c.order.OrderShipped.v1"
    B2C_ORDER_ORDER_DELIVERED_V1 = "b2c.order.OrderDelivered.v1"
    B2C_ORDER_ORDER_CANCELLED_V1 = "b2c.order.OrderCancelled.v1"
    B2C_ORDER_ORDER_REFUNDED_V1 = "b2c.order.OrderRefunded.v1"
    B2B_TRADEORDER_TRADE_ORDER_CREATED_V1 = "b2b.tradeorder.TradeOrderCreated.v1"
    B2B_TRADEORDER_MARGIN_POSTED_V1 = "b2b.tradeorder.MarginPosted.v1"
    B2B_TRADEORDER_TRADE_ACTIVATED_V1 = "b2b.tradeorder.TradeActivated.v1"
    B2B_TRADEORDER_SETTLEMENT_INITIATED_V1 = "b2b.tradeorder.SettlementInitiated.v1"
    B2B_TRADEORDER_TRADE_SETTLED_V1 = "b2b.tradeorder.TradeSettled.v1"
    B2B_TRADEORDER_TRADE_DISPUTED_V1 = "b2b.tradeorder.TradeDisputed.v1"
    B2B_TRADEORDER_TRADE_CANCELLED_V1 = "b2b.tradeorder.TradeCancelled.v1"
    FINANCE_WALLET_WALLET_CREATED_V1 = "finance.wallet.WalletCreated.v1"
    FINANCE_WALLET_MFSACCOUNT_REGISTERED_V1 = "finance.wallet.MFSAccountRegistered.v1"
    FINANCE_WALLET_MFSACCOUNT_VERIFIED_V1 = "finance.wallet.MFSAccountVerified.v1"
    FINANCE_WALLET_WALLET_CREDITED_V1 = "finance.wallet.WalletCredited.v1"
    FINANCE_WALLET_WALLET_DEBITED_V1 = "finance.wallet.WalletDebited.v1"
    FINANCE_WALLET_WALLET_FROZEN_V1 = "finance.wallet.WalletFrozen.v1"
    FINANCE_WALLET_MFSWITHDRAWAL_INITIATED_V1 = "finance.wallet.MFSWithdrawalInitiated.v1"
    FINANCE_WALLET_MFSWITHDRAWAL_CONFIRMED_V1 = "finance.wallet.MFSWithdrawalConfirmed.v1"
    FINANCE_WALLET_MFSWITHDRAWAL_FAILED_V1 = "finance.wallet.MFSWithdrawalFailed.v1"
    FINANCE_ESCROW_ESCROW_CREATED_V1 = "finance.escrow.EscrowCreated.v1"
    FINANCE_ESCROW_ESCROW_RELEASED_V1 = "finance.escrow.EscrowReleased.v1"
    FINANCE_ESCROW_SETTLEMENT_HOLD_RELEASED_V1 = "finance.escrow.SettlementHoldReleased.v1"
    FINANCE_ESCROW_ESCROW_REVERSED_V1 = "finance.escrow.EscrowReversed.v1"
    LOGISTICS_SHIPMENT_SHIPMENT_CREATED_V1 = "logistics.shipment.ShipmentCreated.v1"
    LOGISTICS_SHIPMENT_RIDER_ASSIGNED_V1 = "logistics.shipment.RiderAssigned.v1"
    LOGISTICS_SHIPMENT_PICKUP_RECORDED_V1 = "logistics.shipment.PickupRecorded.v1"
    LOGISTICS_SHIPMENT_DELIVERY_RECORDED_V1 = "logistics.shipment.DeliveryRecorded.v1"
    LOGISTICS_SHIPMENT_SHIPMENT_CANCELLED_V1 = "logistics.shipment.ShipmentCancelled.v1"
    LOGISTICS_SHIPMENT_DELIVERY_FAILED_V1 = "logistics.shipment.DeliveryFailed.v1"
    FRAUD_ENFORCEMENT_FRAUD_SIGNAL_RAISED_V1 = "fraud.enforcement.FraudSignalRaised.v1"
    FRAUD_ENFORCEMENT_ACCOUNT_HELD_V1 = "fraud.enforcement.AccountHeld.v1"
    FRAUD_ENFORCEMENT_ACCOUNT_HOLD_RELEASED_V1 = "fraud.enforcement.AccountHoldReleased.v1"
    GOVERNMENT_OVERSIGHT_RECALL_DIRECTIVE_ISSUED_V1 = "government.oversight.RecallDirectiveIssued.v1"
    GOVERNMENT_OVERSIGHT_TRADE_FREEZE_DIRECTIVE_V1 = "government.oversight.TradeFreezeDirective.v1"
    GOVERNMENT_OVERSIGHT_WALLET_FREEZE_DIRECTIVE_V1 = "government.oversight.WalletFreezeDirective.v1"
    PLATFORM_SCHEDULER_COOLING_OFF_EXPIRED_V1 = "platform.scheduler.CoolingOffExpired.v1"
    PLATFORM_SCHEDULER_ESCROW_EXPIRED_V1 = "platform.scheduler.EscrowExpired.v1"
    PLATFORM_SCHEDULER_NILROLLUP_REFRESH_V1 = "platform.scheduler.NILRollupRefresh.v1"

class RabbitQueues:
    """10 intra-context queues — NOT Published Language (R6)."""
    IDENTITY_KYC_VERIFICATION = "identity.kyc-verification"
    IDENTITY_OTP_DISPATCH = "identity.otp-dispatch"
    CATALOG_IMAGE_PROCESSING = "catalog.image-processing"
    CATALOG_SEARCH_INDEX = "catalog.search-index"
    B2C_ORDER_CONFIRMATION = "b2c.order-confirmation"
    B2C_STOCK_RESERVE = "b2c.stock-reserve"
    LOGISTICS_RIDER_ASSIGNMENT = "logistics.rider-assignment"
    LOGISTICS_DELIVERY_NOTIFICATION = "logistics.delivery-notification"
    FRAUD_HOLD_APPROVAL_REQUEST = "fraud.hold-approval-request"
    PLATFORM_NOTIFICATION_DISPATCH = "platform.notification-dispatch"

TOPIC_META = {
    "identity.party.PartyRegistered.v1": TopicMeta("identity.party.PartyRegistered.v1", 1, "DID", (8, 13), "identity", "party", "PartyRegistered", 1),
    "identity.party.KYCApproved.v1": TopicMeta("identity.party.KYCApproved.v1", 1, "DID", (6, 7, 10, 11), "identity", "party", "KYCApproved", 1),
    "identity.party.KYCTierChanged.v1": TopicMeta("identity.party.KYCTierChanged.v1", 1, "DID", (6, 7, 10, 11), "identity", "party", "KYCTierChanged", 1),
    "identity.party.KYCRejected.v1": TopicMeta("identity.party.KYCRejected.v1", 1, "DID", (13,), "identity", "party", "KYCRejected", 1),
    "identity.party.PartySuspended.v1": TopicMeta("identity.party.PartySuspended.v1", 1, "DID", (6, 7, 8, 10, 11), "identity", "party", "PartySuspended", 1),
    "identity.party.PartyReactivated.v1": TopicMeta("identity.party.PartyReactivated.v1", 1, "DID", (6, 7, 8), "identity", "party", "PartyReactivated", 1),
    "catalog.product.ProductCreated.v1": TopicMeta("catalog.product.ProductCreated.v1", 2, "GPID", (12,), "catalog", "product", "ProductCreated", 1),
    "catalog.product.ProductPublished.v1": TopicMeta("catalog.product.ProductPublished.v1", 2, "GPID", (6, 12), "catalog", "product", "ProductPublished", 1),
    "catalog.product.ProductDeprecated.v1": TopicMeta("catalog.product.ProductDeprecated.v1", 2, "GPID", (5, 6, 7, 12), "catalog", "product", "ProductDeprecated", 1),
    "catalog.product.ProductPriceRuleAdded.v1": TopicMeta("catalog.product.ProductPriceRuleAdded.v1", 2, "GPID", (6, 12), "catalog", "product", "ProductPriceRuleAdded", 1),
    "catalog.product.ProductMasterDataUpdated.v1": TopicMeta("catalog.product.ProductMasterDataUpdated.v1", 2, "GPID", (12,), "catalog", "product", "ProductMasterDataUpdated", 1),
    "custody.passport.CustodyInitialized.v1": TopicMeta("custody.passport.CustodyInitialized.v1", 3, "PPID", (2, 4, 5, 11, 12), "custody", "passport", "CustodyInitialized", 1),
    "custody.passport.CustodyTransferred.v1": TopicMeta("custody.passport.CustodyTransferred.v1", 3, "PPID", (2, 4, 5, 8, 11, 12), "custody", "passport", "CustodyTransferred", 1),
    "custody.passport.CustodySplit.v1": TopicMeta("custody.passport.CustodySplit.v1", 3, "parentPpid", (2, 4, 5, 12), "custody", "passport", "CustodySplit", 1),
    "custody.passport.CustodyMerged.v1": TopicMeta("custody.passport.CustodyMerged.v1", 3, "newPpid", (2, 4, 5, 12), "custody", "passport", "CustodyMerged", 1),
    "custody.passport.ProductRecalled.v1": TopicMeta("custody.passport.ProductRecalled.v1", 3, "recallId", (2, 4, 5, 6, 7, 11, 12), "custody", "passport", "ProductRecalled", 1),
    "custody.passport.CustodialSigned.v1": TopicMeta("custody.passport.CustodialSigned.v1", 3, "PPID", (4, 12), "custody", "passport", "CustodialSigned", 1),
    "b2c.order.OrderPlaced.v1": TopicMeta("b2c.order.OrderPlaced.v1", 6, "ORD", (8, 9, 10, 11, 12), "b2c", "order", "OrderPlaced", 1),
    "b2c.order.PaymentConfirmed.v1": TopicMeta("b2c.order.PaymentConfirmed.v1", 6, "ORD", (12,), "b2c", "order", "PaymentConfirmed", 1),
    "b2c.order.OrderProcessingStarted.v1": TopicMeta("b2c.order.OrderProcessingStarted.v1", 6, "ORD", (9, 12), "b2c", "order", "OrderProcessingStarted", 1),
    "b2c.order.OrderShipped.v1": TopicMeta("b2c.order.OrderShipped.v1", 6, "ORD", (12,), "b2c", "order", "OrderShipped", 1),
    "b2c.order.OrderDelivered.v1": TopicMeta("b2c.order.OrderDelivered.v1", 6, "ORD", (8, 12), "b2c", "order", "OrderDelivered", 1),
    "b2c.order.OrderCancelled.v1": TopicMeta("b2c.order.OrderCancelled.v1", 6, "ORD", (8, 9, 12), "b2c", "order", "OrderCancelled", 1),
    "b2c.order.OrderRefunded.v1": TopicMeta("b2c.order.OrderRefunded.v1", 6, "ORD", (12,), "b2c", "order", "OrderRefunded", 1),
    "b2b.tradeorder.TradeOrderCreated.v1": TopicMeta("b2b.tradeorder.TradeOrderCreated.v1", 7, "TRD", (8, 10, 11, 12), "b2b", "tradeorder", "TradeOrderCreated", 1),
    "b2b.tradeorder.MarginPosted.v1": TopicMeta("b2b.tradeorder.MarginPosted.v1", 7, "TRD", (8, 12), "b2b", "tradeorder", "MarginPosted", 1),
    "b2b.tradeorder.TradeActivated.v1": TopicMeta("b2b.tradeorder.TradeActivated.v1", 7, "TRD", (8, 12), "b2b", "tradeorder", "TradeActivated", 1),
    "b2b.tradeorder.SettlementInitiated.v1": TopicMeta("b2b.tradeorder.SettlementInitiated.v1", 7, "TRD", (8, 12), "b2b", "tradeorder", "SettlementInitiated", 1),
    "b2b.tradeorder.TradeSettled.v1": TopicMeta("b2b.tradeorder.TradeSettled.v1", 7, "TRD", (11, 12), "b2b", "tradeorder", "TradeSettled", 1),
    "b2b.tradeorder.TradeDisputed.v1": TopicMeta("b2b.tradeorder.TradeDisputed.v1", 7, "TRD", (8, 11, 12), "b2b", "tradeorder", "TradeDisputed", 1),
    "b2b.tradeorder.TradeCancelled.v1": TopicMeta("b2b.tradeorder.TradeCancelled.v1", 7, "TRD", (8, 12), "b2b", "tradeorder", "TradeCancelled", 1),
    "finance.wallet.WalletCreated.v1": TopicMeta("finance.wallet.WalletCreated.v1", 8, "WLT", (12,), "finance", "wallet", "WalletCreated", 1),
    "finance.wallet.MFSAccountRegistered.v1": TopicMeta("finance.wallet.MFSAccountRegistered.v1", 8, "WLT", (12,), "finance", "wallet", "MFSAccountRegistered", 1),
    "finance.wallet.MFSAccountVerified.v1": TopicMeta("finance.wallet.MFSAccountVerified.v1", 8, "WLT", (12,), "finance", "wallet", "MFSAccountVerified", 1),
    "finance.wallet.WalletCredited.v1": TopicMeta("finance.wallet.WalletCredited.v1", 8, "WLT", (11, 12), "finance", "wallet", "WalletCredited", 1),
    "finance.wallet.WalletDebited.v1": TopicMeta("finance.wallet.WalletDebited.v1", 8, "WLT", (11, 12), "finance", "wallet", "WalletDebited", 1),
    "finance.wallet.WalletFrozen.v1": TopicMeta("finance.wallet.WalletFrozen.v1", 8, "WLT", (11, 12), "finance", "wallet", "WalletFrozen", 1),
    "finance.wallet.MFSWithdrawalInitiated.v1": TopicMeta("finance.wallet.MFSWithdrawalInitiated.v1", 8, "TXN", (12,), "finance", "wallet", "MFSWithdrawalInitiated", 1),
    "finance.wallet.MFSWithdrawalConfirmed.v1": TopicMeta("finance.wallet.MFSWithdrawalConfirmed.v1", 8, "TXN", (11, 12), "finance", "wallet", "MFSWithdrawalConfirmed", 1),
    "finance.wallet.MFSWithdrawalFailed.v1": TopicMeta("finance.wallet.MFSWithdrawalFailed.v1", 8, "TXN", (12,), "finance", "wallet", "MFSWithdrawalFailed", 1),
    "finance.escrow.EscrowCreated.v1": TopicMeta("finance.escrow.EscrowCreated.v1", 8, "ESC", (6, 12), "finance", "escrow", "EscrowCreated", 1),
    "finance.escrow.EscrowReleased.v1": TopicMeta("finance.escrow.EscrowReleased.v1", 8, "ESC", (7, 11, 12), "finance", "escrow", "EscrowReleased", 1),
    "finance.escrow.SettlementHoldReleased.v1": TopicMeta("finance.escrow.SettlementHoldReleased.v1", 8, "ESC", (11, 12), "finance", "escrow", "SettlementHoldReleased", 1),
    "finance.escrow.EscrowReversed.v1": TopicMeta("finance.escrow.EscrowReversed.v1", 8, "ESC", (6, 11, 12), "finance", "escrow", "EscrowReversed", 1),
    "logistics.shipment.ShipmentCreated.v1": TopicMeta("logistics.shipment.ShipmentCreated.v1", 9, "SHP", (6, 12), "logistics", "shipment", "ShipmentCreated", 1),
    "logistics.shipment.RiderAssigned.v1": TopicMeta("logistics.shipment.RiderAssigned.v1", 9, "SHP", (6, 12), "logistics", "shipment", "RiderAssigned", 1),
    "logistics.shipment.PickupRecorded.v1": TopicMeta("logistics.shipment.PickupRecorded.v1", 9, "SHP", (12,), "logistics", "shipment", "PickupRecorded", 1),
    "logistics.shipment.DeliveryRecorded.v1": TopicMeta("logistics.shipment.DeliveryRecorded.v1", 9, "SHP", (6, 8, 12), "logistics", "shipment", "DeliveryRecorded", 1),
    "logistics.shipment.ShipmentCancelled.v1": TopicMeta("logistics.shipment.ShipmentCancelled.v1", 9, "SHP", (6, 8, 12), "logistics", "shipment", "ShipmentCancelled", 1),
    "logistics.shipment.DeliveryFailed.v1": TopicMeta("logistics.shipment.DeliveryFailed.v1", 9, "SHP", (6, 12), "logistics", "shipment", "DeliveryFailed", 1),
    "fraud.enforcement.FraudSignalRaised.v1": TopicMeta("fraud.enforcement.FraudSignalRaised.v1", 10, "DID", (11, 12), "fraud", "enforcement", "FraudSignalRaised", 1),
    "fraud.enforcement.AccountHeld.v1": TopicMeta("fraud.enforcement.AccountHeld.v1", 10, "DID", (6, 7, 8, 11), "fraud", "enforcement", "AccountHeld", 1),
    "fraud.enforcement.AccountHoldReleased.v1": TopicMeta("fraud.enforcement.AccountHoldReleased.v1", 10, "DID", (6, 7, 8, 11), "fraud", "enforcement", "AccountHoldReleased", 1),
    "government.oversight.RecallDirectiveIssued.v1": TopicMeta("government.oversight.RecallDirectiveIssued.v1", 11, "recallId", (3,), "government", "oversight", "RecallDirectiveIssued", 1),
    "government.oversight.TradeFreezeDirective.v1": TopicMeta("government.oversight.TradeFreezeDirective.v1", 11, "directiveId", (7,), "government", "oversight", "TradeFreezeDirective", 1),
    "government.oversight.WalletFreezeDirective.v1": TopicMeta("government.oversight.WalletFreezeDirective.v1", 11, "directiveId", (8,), "government", "oversight", "WalletFreezeDirective", 1),
    "platform.scheduler.CoolingOffExpired.v1": TopicMeta("platform.scheduler.CoolingOffExpired.v1", 13, "ESC", (8,), "platform", "scheduler", "CoolingOffExpired", 1),
    "platform.scheduler.EscrowExpired.v1": TopicMeta("platform.scheduler.EscrowExpired.v1", 13, "ESC", (8,), "platform", "scheduler", "EscrowExpired", 1),
    "platform.scheduler.NILRollupRefresh.v1": TopicMeta("platform.scheduler.NILRollupRefresh.v1", 13, "GPID", (5,), "platform", "scheduler", "NILRollupRefresh", 1),
}

def topic_meta(name: str) -> TopicMeta:
    return TOPIC_META[name]

ALL_TOPICS = tuple(TOPIC_META.keys())
