# DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
# The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
# build_time=2026-06-29T00:00:00Z build_commit=source

"""Validation utilities for IDs, money, the envelope, and config constants."""
from __future__ import annotations
from typing import Any
from . import ids as _ids
from .money import Money
from .topics import TOPIC_META


def validate_id(id_type, value: str):
    """Return a typed ID or raise ValueError."""
    return id_type(value)


def is_valid_id(id_type, value: str) -> bool:
    try:
        id_type(value)
        return True
    except Exception:
        return False


def validate_money(poisha: Any) -> Money:
    return Money(poisha)


def validate_topic(name: str) -> bool:
    return name in TOPIC_META
