// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

/** Canonical enum families (glossary.yaml; FR-IDN-310). Values transcribed verbatim. */
public final class Enums {
    private Enums() {}
    public enum KycTiers {
        V0("V0"), V1("V1"), V2("V2"), V3("V3");
        public final String value;
        KycTiers(String value) { this.value = value; }
    }
    public enum FraudDetectors {
        HOARDING("HOARDING"), PASSPORT_FORGERY("PASSPORT_FORGERY"), GHOST_SPLIT("GHOST_SPLIT"), MFS_STRUCTURING("MFS_STRUCTURING"), SUBSIDY_DUP("SUBSIDY_DUP"), CIRCULAR_TRADE("CIRCULAR_TRADE"), VELOCITY_ANOMALY("VELOCITY_ANOMALY"), GEO_IMPOSSIBLE("GEO_IMPOSSIBLE"), COLLUSION_RING("COLLUSION_RING");
        public final String value;
        FraudDetectors(String value) { this.value = value; }
    }
    // NOTE: contract marks the above family non-exhaustive (illustrative).
    public enum FraudCaseStates {
        OPEN("OPEN"), INVESTIGATING("INVESTIGATING"), SUBSTANTIATED("SUBSTANTIATED"), ENFORCED("ENFORCED"), DISMISSED("DISMISSED");
        public final String value;
        FraudCaseStates(String value) { this.value = value; }
    }
    // NOTE: contract marks the above family non-exhaustive (illustrative).
    public enum EnforcementActions {
        WARN("WARN"), RESTRICT_LISTING("RESTRICT_LISTING"), SUSPEND("SUSPEND"), BLACKLIST("BLACKLIST"), LICENSE_REVOKE("LICENSE_REVOKE");
        public final String value;
        EnforcementActions(String value) { this.value = value; }
    }
    // NOTE: contract marks the above family non-exhaustive (illustrative).
    public enum OversightRoles {
        ANALYST("ANALYST"), INVESTIGATOR("INVESTIGATOR"), ENFORCEMENT_OFFICER("ENFORCEMENT_OFFICER"), APPROVER("APPROVER"), SUPER_ADMIN("SUPER_ADMIN");
        public final String value;
        OversightRoles(String value) { this.value = value; }
    }
    // NOTE: contract marks the above family non-exhaustive (illustrative).
    public enum PartyActorCodes {
        FARIA("FARIA"), WHOLESALER("WHOLESALER"), RETAIL("RETAIL"), GOV("GOV"), PERSON("PERSON"), ORG("ORG");
        public final String value;
        PartyActorCodes(String value) { this.value = value; }
    }
    // NOTE: contract marks the above family non-exhaustive (illustrative).
    public enum CommodityUnits {
        SEER("seer"), MAUND("maund"), BOSTA("bosta");
        public final String value;
        CommodityUnits(String value) { this.value = value; }
    }
    // NOTE: contract marks the above family non-exhaustive (illustrative).
}
