// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

public final class Ids {
    private Ids() {}

    public abstract static class PrefixedId {
        public final String value;
        protected PrefixedId(String value, String prefix) {
            if (value == null || !value.startsWith(prefix) || value.length() <= prefix.length())
                throw new IllegalArgumentException(getClass().getSimpleName() + " must start with '" + prefix + "' and carry a body");
            this.value = value;
        }
        @Override public String toString() { return value; }
        @Override public boolean equals(Object o) { return o != null && o.getClass() == getClass() && ((PrefixedId) o).value.equals(value); }
        @Override public int hashCode() { return java.util.Objects.hash(getClass(), value); }
    }

    public static final class DID extends PrefixedId {
        public static final String PREFIX = "did:dokandar:";
        public static final int OWNER_CONTEXT = 1; // identity
        public static final boolean IMMUTABLE = true;
        public DID(String v) { super(v, PREFIX); }
    }

    public static final class PPID extends PrefixedId {
        public static final String PREFIX = "PP-";
        public static final int OWNER_CONTEXT = 3; // custody
        public static final boolean IMMUTABLE = false;
        public PPID(String v) { super(v, PREFIX); }
    }

    public static final class GPID extends PrefixedId {
        public static final String PREFIX = "GP-";
        public static final int OWNER_CONTEXT = 2; // catalog
        public static final boolean IMMUTABLE = false;
        public GPID(String v) { super(v, PREFIX); }
    }

    public static final class ORD extends PrefixedId {
        public static final String PREFIX = "ORD-";
        public static final int OWNER_CONTEXT = 6; // b2c
        public static final boolean IMMUTABLE = false;
        public ORD(String v) { super(v, PREFIX); }
    }

    public static final class TRD extends PrefixedId {
        public static final String PREFIX = "TRD-";
        public static final int OWNER_CONTEXT = 7; // b2b
        public static final boolean IMMUTABLE = false;
        public TRD(String v) { super(v, PREFIX); }
    }

    public static final class WLT extends PrefixedId {
        public static final String PREFIX = "WLT-";
        public static final int OWNER_CONTEXT = 8; // finance
        public static final boolean IMMUTABLE = false;
        public WLT(String v) { super(v, PREFIX); }
    }

    public static final class ESC extends PrefixedId {
        public static final String PREFIX = "ESC-";
        public static final int OWNER_CONTEXT = 8; // finance
        public static final boolean IMMUTABLE = false;
        public ESC(String v) { super(v, PREFIX); }
    }

    public static final class TXN extends PrefixedId {
        public static final String PREFIX = "TXN-";
        public static final int OWNER_CONTEXT = 8; // finance
        public static final boolean IMMUTABLE = false;
        public TXN(String v) { super(v, PREFIX); }
    }

    public static final class SHP extends PrefixedId {
        public static final String PREFIX = "SHP-";
        public static final int OWNER_CONTEXT = 9; // logistics
        public static final boolean IMMUTABLE = false;
        public SHP(String v) { super(v, PREFIX); }
    }

    public static final class NTF extends PrefixedId {
        public static final String PREFIX = "NTF-";
        public static final int OWNER_CONTEXT = 13; // platform
        public static final boolean IMMUTABLE = false;
        public NTF(String v) { super(v, PREFIX); }
    }

    public static final class MFSA extends PrefixedId {
        public static final String PREFIX = "MFSA-";
        public static final int OWNER_CONTEXT = 8; // finance
        public static final boolean IMMUTABLE = false;
        public MFSA(String v) { super(v, PREFIX); }
    }

}
