// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

// Common DTOs: the {success,data,error,meta} envelope, cursor pagination, trace/audit metadata.
type PageMeta struct {
	NextCursor string
	HasMore    bool
	Limit      int
}

type TraceMetadata struct{ TraceID, SpanID, CorrelationID string }
type AuditMetadata struct {
	ActorDID     string
	OccurredAtMs int64
	RequestID    string
}

type Meta struct {
	Page  *PageMeta
	Trace *TraceMetadata
	Extra map[string]any
}

// Response is the canonical external REST envelope (EF §7).
type Response[T any] struct {
	Success bool
	Data    *T
	Error   *ProblemDetails
	Meta    *Meta
}

func Ok[T any](data T, meta *Meta) Response[T] {
	return Response[T]{Success: true, Data: &data, Meta: meta}
}

func Fail[T any](err *ProblemDetails, meta *Meta) Response[T] {
	return Response[T]{Success: false, Error: err, Meta: meta}
}

type Page[T any] struct {
	Items []T
	Page  PageMeta
}
