// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

const (
	Generator        = "dkdgen"
	GeneratorVersion = "1.0.0"
	ContractVersion  = "1.0.0"
	BuildTime        = "2026-06-29T00:00:00Z"
	BuildCommit      = "source"
)
