apiVersion: v1
kind: Namespace
metadata:
  name: gateway
  labels:
    name: gateway
    tier: public
    environment: prod
    managed-by: gitlab-ci
    app.kubernetes.io/part-of: dokandar
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    name: frontend
    tier: public
    environment: prod
    managed-by: gitlab-ci
    app.kubernetes.io/part-of: dokandar
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    name: backend
    tier: private
    environment: prod
    managed-by: gitlab-ci
    app.kubernetes.io/part-of: dokandar
---
apiVersion: v1
kind: Namespace
metadata:
  name: support
  labels:
    name: support
    tier: public
    environment: prod
    managed-by: gitlab-ci
    app.kubernetes.io/part-of: dokandar
