// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using IdentitySvc.Observability;

namespace IdentitySvc.Http.Middleware;

/// <summary>
/// Ensures every inbound request carries a correlation ID and W3C traceparent.
/// Generates new values when the caller does not supply them and echoes them on the response.
/// </summary>
public sealed class CorrelationMiddleware(RequestDelegate next)
{
    public async Task InvokeAsync(HttpContext ctx)
    {
        var corrId = ctx.Request.Headers["X-Correlation-Id"].FirstOrDefault()
                     ?? Tracing.NewCorrelationId();
        var traceParent = ctx.Request.Headers["traceparent"].FirstOrDefault()
                          ?? Tracing.NewTraceParent();

        ctx.Items[AppLogger.Keys.CorrelationId] = corrId;
        ctx.Items[AppLogger.Keys.TraceParent]   = traceParent;
        ctx.Response.Headers["X-Correlation-Id"] = corrId;
        ctx.Response.Headers["traceparent"]       = traceParent;

        await next(ctx);
    }
}
