// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using Microsoft.AspNetCore.Http;
using Dkd.Platform;

namespace IdentitySvc.Http.Middleware;

/// <summary>
/// Outermost middleware: catches all unhandled exceptions and converts them to RFC-7807
/// problem+json responses with the Dokandar error code taxonomy
/// dokandar.identity.{category}.{reason}. Never leaks stack traces to callers.
/// </summary>
public sealed class ExceptionHandlingMiddleware(
    RequestDelegate next,
    ILogger<ExceptionHandlingMiddleware> logger)
{
    public async Task InvokeAsync(HttpContext ctx)
    {
        try
        {
            await next(ctx);
        }
        catch (ArgumentException ex) when (!ctx.Response.HasStarted)
        {
            logger.LogWarning(ex, "Validation error on {Path}", ctx.Request.Path);
            await WriteProblemAsync(ctx, 400, "Validation Error", ex.Message,
                // CC-CONS-2: reason segment must match the taxonomy regex ^dokandar\.[a-z]+\.[a-z0-9_]+\.[a-z0-9_]+$
                // (underscore, never hyphen).
                "dokandar.identity.validation.invalid_input");
        }
        catch (UnauthorizedAccessException ex) when (!ctx.Response.HasStarted)
        {
            logger.LogWarning(ex, "Unauthorized on {Path}", ctx.Request.Path);
            await WriteProblemAsync(ctx, 401, "Unauthorized", ex.Message,
                "dokandar.identity.auth.unauthorized");
        }
        catch (DokandarException ex) when (!ctx.Response.HasStarted)
        {
            // Domain/application errors carry their own taxonomy code + HTTP status.
            logger.Log(ex.HttpStatus >= 500 ? LogLevel.Error : LogLevel.Warning,
                ex, "Domain error {Code} on {Path}", ex.Code, ctx.Request.Path);
            await WriteProblemAsync(ctx, ex.HttpStatus, "Request Error", ex.Message, ex.Code);
        }
        catch (Exception ex) when (!ctx.Response.HasStarted)
        {
            logger.LogError(ex, "Unhandled exception on {Path}", ctx.Request.Path);
            await WriteProblemAsync(ctx, 500, "Internal Server Error",
                "An unexpected error occurred.",
                "dokandar.identity.internal.error");
        }
    }

    private static async Task WriteProblemAsync(
        HttpContext ctx, int status, string title, string detail, string code)
    {
        ctx.Response.StatusCode  = status;
        ctx.Response.ContentType = "application/problem+json";
        await ctx.Response.WriteAsJsonAsync(new
        {
            type     = "about:blank",
            title,
            status,
            detail,
            instance = ctx.Request.Path.Value,
            code,
        });
    }
}
