// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using IdentitySvc.Security;

namespace IdentitySvc.Http.Middleware;

/// <summary>
/// Optional JWT authentication middleware: extracts the bearer token, parses and verifies it via
/// <see cref="JwtAuthenticator"/>, then attaches the <see cref="DkdClaims"/> to HttpContext.Items.
/// Does NOT reject unauthenticated requests — health endpoints remain public. Use
/// <see cref="JwtAuthenticator.GetClaims"/> and <see cref="JwtAuthenticator.HasRole"/> downstream
/// to enforce route-level authorization.
/// </summary>
public sealed class JwtAuthMiddleware(RequestDelegate next, JwtAuthenticator auth)
{
    private const string BearerPrefix = "Bearer ";

    public async Task InvokeAsync(HttpContext ctx)
    {
        var token = ExtractBearer(ctx.Request);
        if (token is not null)
        {
            var claims = auth.TryAuthenticate(token);
            if (claims is not null)
                ctx.Items[nameof(DkdClaims)] = claims;
        }
        await next(ctx);
    }

    private static string? ExtractBearer(HttpRequest request)
    {
        var header = request.Headers.Authorization.FirstOrDefault();
        return header?.StartsWith(BearerPrefix, StringComparison.OrdinalIgnoreCase) == true
            ? header[BearerPrefix.Length..]
            : null;
    }
}
