// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using System.Diagnostics;
using IdentitySvc.Observability;

namespace IdentitySvc.Http.Middleware;

/// <summary>
/// Logs every request (method, path, status, elapsed ms, correlation ID) and increments the
/// http_requests_total counter. Runs after CorrelationMiddleware so the ID is always present.
/// </summary>
public sealed class RequestLoggingMiddleware(
    RequestDelegate next,
    ILogger<RequestLoggingMiddleware> logger,
    AppMetrics metrics)
{
    public async Task InvokeAsync(HttpContext ctx)
    {
        var start = Stopwatch.GetTimestamp();
        metrics.Increment("http_requests_total");

        await next(ctx);

        var elapsed = Stopwatch.GetElapsedTime(start);
        var corrId  = ctx.Items.TryGetValue(AppLogger.Keys.CorrelationId, out var v) ? v as string : null;

        logger.LogInformation(
            "request {Method} {Path} {StatusCode} {ElapsedMs}ms {CorrelationId}",
            ctx.Request.Method,
            ctx.Request.Path,
            ctx.Response.StatusCode,
            (long)elapsed.TotalMilliseconds,
            corrId);
    }
}
