// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.
// EXTENDED: the strict default CSP (default-src 'none') is relaxed ONLY for the Swagger UI paths
// (/docs, /swagger), which need inline script/style; all API/data responses keep the strict policy.

namespace IdentitySvc.Http.Middleware;

/// <summary>
/// Sets conservative security response headers on every outbound response.
/// Headers are applied via OnStarting to ensure they precede any response body.
/// </summary>
public sealed class SecurityHeadersMiddleware(RequestDelegate next)
{
    public Task InvokeAsync(HttpContext ctx)
    {
        var isDocs = ctx.Request.Path.StartsWithSegments("/docs")
                     || ctx.Request.Path.StartsWithSegments("/swagger");
        ctx.Response.OnStarting(() =>
        {
            var h = ctx.Response.Headers;
            h["X-Content-Type-Options"] = "nosniff";
            h["Referrer-Policy"]         = "no-referrer";
            if (isDocs)
            {
                // Swagger UI requires inline scripts/styles and same-origin fetch of the spec.
                h["Content-Security-Policy"] =
                    "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; " +
                    "img-src 'self' data:; font-src 'self'; connect-src 'self'";
            }
            else
            {
                h["X-Frame-Options"]         = "DENY";
                h["Content-Security-Policy"] = "default-src 'none'";
            }
            return Task.CompletedTask;
        });
        return next(ctx);
    }
}
