// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

namespace IdentitySvc.Persistence;

/// <summary>
/// Persistence abstractions for the hexagonal adapters layer. The concrete Npgsql/pgx driver is
/// the integration point — no business repositories are defined here. Each bounded context adds
/// its own repository implementations (inheriting RepositoryBase) in the adapters ring.
/// </summary>

/// <summary>Unit-of-work handle for an active database transaction.</summary>
public interface ITx
{
    /// <summary>Execute a parameterised SQL statement within the transaction.</summary>
    Task ExecuteAsync(string sql, object? parameters = null, CancellationToken ct = default);
}

/// <summary>
/// Database abstraction: ping (readiness), WithTransactionAsync (tx helper), and lifecycle.
/// The concrete implementation wraps a connection pool (e.g. NpgsqlDataSource).
/// </summary>
public interface IDb : IAsyncDisposable
{
    /// <summary>Verifies the database is reachable; used by the /ready probe.</summary>
    Task PingAsync(CancellationToken ct = default);

    /// <summary>
    /// Executes <paramref name="fn"/> inside a database transaction. Commits on success;
    /// rolls back and re-throws on any exception.
    /// </summary>
    Task<T> WithTransactionAsync<T>(Func<ITx, Task<T>> fn, CancellationToken ct = default);
}

/// <summary>
/// Base class for all context repositories. Carries the IDb handle and exposes the transaction
/// helper. Business repositories in the adapters ring inherit from this class.
/// </summary>
public abstract class RepositoryBase(IDb db)
{
    protected IDb Db { get; } = db;

    /// <summary>Convenience wrapper: executes <paramref name="fn"/> in a transaction.</summary>
    protected Task<T> InTransactionAsync<T>(Func<ITx, Task<T>> fn, CancellationToken ct = default)
        => Db.WithTransactionAsync(fn, ct);
}

/// <summary>
/// Schema migration abstraction: Apply runs ordered, idempotent SQL migrations at startup.
/// Replace NoopMigrator with a real driver (DbUp, Evolve, or EF Core Migrate) at the
/// integration point. Migrations run before the readiness gate flips to true.
/// </summary>
public interface IMigrator
{
    Task Apply(CancellationToken ct = default);
}

/// <summary>No-op migrator: safe default for local runs without a real database wired.</summary>
public sealed class NoopMigrator : IMigrator
{
    public Task Apply(CancellationToken ct = default) => Task.CompletedTask;
}
