// inventory-reservation-ohs (B2B-F2 / EF-API-1 internal plane). gRPC surface for the G2
// strong-local reserve/transition writes other contexts (B2B) use instead of REST.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/inventory_reservation_ohs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Gpid           string `protobuf:"bytes,2,opt,name=gpid,proto3" json:"gpid,omitempty"`
	Holder         string `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	Quantity       int64  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_reservation_ohs_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReserveRequest) GetGpid() string {
	if x != nil {
		return x.Gpid
	}
	return ""
}

func (x *ReserveRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *ReserveRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok                bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ResId             string `protobuf:"bytes,2,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	InsufficientStock bool   `protobuf:"varint,3,opt,name=insufficient_stock,json=insufficientStock,proto3" json:"insufficient_stock,omitempty"`
}

func (x *ReserveReply) Reset() {
	*x = ReserveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveReply) ProtoMessage() {}

func (x *ReserveReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveReply.ProtoReflect.Descriptor instead.
func (*ReserveReply) Descriptor() ([]byte, []int) {
	return file_proto_inventory_reservation_ohs_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReserveReply) GetResId() string {
	if x != nil {
		return x.ResId
	}
	return ""
}

func (x *ReserveReply) GetInsufficientStock() bool {
	if x != nil {
		return x.InsufficientStock
	}
	return false
}

type TransitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResId string `protobuf:"bytes,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	To    string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *TransitionRequest) Reset() {
	*x = TransitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionRequest) ProtoMessage() {}

func (x *TransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionRequest.ProtoReflect.Descriptor instead.
func (*TransitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_reservation_ohs_proto_rawDescGZIP(), []int{2}
}

func (x *TransitionRequest) GetResId() string {
	if x != nil {
		return x.ResId
	}
	return ""
}

func (x *TransitionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type TransitionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NotFound bool   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	State    string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *TransitionReply) Reset() {
	*x = TransitionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransitionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionReply) ProtoMessage() {}

func (x *TransitionReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_reservation_ohs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionReply.ProtoReflect.Descriptor instead.
func (*TransitionReply) Descriptor() ([]byte, []int) {
	return file_proto_inventory_reservation_ohs_proto_rawDescGZIP(), []int{3}
}

func (x *TransitionReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TransitionReply) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

func (x *TransitionReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_proto_inventory_reservation_ohs_proto protoreflect.FileDescriptor

var file_proto_inventory_reservation_ohs_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x68,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61,
	0x72, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e,
	0x76, 0x31, 0x22, 0x81, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74,
	0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x70,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x64, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x73, 0x49, 0x64, 0x12, 0x2d, 0x0a,
	0x12, 0x69, 0x6e, 0x73, 0x75, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x6e, 0x73, 0x75, 0x66,
	0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x3a, 0x0a, 0x11,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x65, 0x73, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x6e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x32, 0xe0,
	0x01, 0x0a, 0x17, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x68, 0x73, 0x12, 0x5d, 0x0a, 0x07, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x29, 0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72,
	0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x2e, 0x69, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x66, 0x0a, 0x0a, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64,
	0x61, 0x72, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x6f, 0x68, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72,
	0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x53, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x2d, 0x79, 0x65, 0x61, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x33, 0x33, 0x35, 0x34, 0x31, 0x32, 0x37, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2d, 0x6e, 0x69, 0x6c, 0x2d, 0x73, 0x76, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x6f, 0x68, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_inventory_reservation_ohs_proto_rawDescOnce sync.Once
	file_proto_inventory_reservation_ohs_proto_rawDescData = file_proto_inventory_reservation_ohs_proto_rawDesc
)

func file_proto_inventory_reservation_ohs_proto_rawDescGZIP() []byte {
	file_proto_inventory_reservation_ohs_proto_rawDescOnce.Do(func() {
		file_proto_inventory_reservation_ohs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_inventory_reservation_ohs_proto_rawDescData)
	})
	return file_proto_inventory_reservation_ohs_proto_rawDescData
}

var file_proto_inventory_reservation_ohs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_inventory_reservation_ohs_proto_goTypes = []any{
	(*ReserveRequest)(nil),    // 0: dokandar.inventory.ohs.v1.ReserveRequest
	(*ReserveReply)(nil),      // 1: dokandar.inventory.ohs.v1.ReserveReply
	(*TransitionRequest)(nil), // 2: dokandar.inventory.ohs.v1.TransitionRequest
	(*TransitionReply)(nil),   // 3: dokandar.inventory.ohs.v1.TransitionReply
}
var file_proto_inventory_reservation_ohs_proto_depIdxs = []int32{
	0, // 0: dokandar.inventory.ohs.v1.InventoryReservationOhs.Reserve:input_type -> dokandar.inventory.ohs.v1.ReserveRequest
	2, // 1: dokandar.inventory.ohs.v1.InventoryReservationOhs.Transition:input_type -> dokandar.inventory.ohs.v1.TransitionRequest
	1, // 2: dokandar.inventory.ohs.v1.InventoryReservationOhs.Reserve:output_type -> dokandar.inventory.ohs.v1.ReserveReply
	3, // 3: dokandar.inventory.ohs.v1.InventoryReservationOhs.Transition:output_type -> dokandar.inventory.ohs.v1.TransitionReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_reservation_ohs_proto_init() }
func file_proto_inventory_reservation_ohs_proto_init() {
	if File_proto_inventory_reservation_ohs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_inventory_reservation_ohs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ReserveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_reservation_ohs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ReserveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_reservation_ohs_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TransitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_reservation_ohs_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TransitionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_inventory_reservation_ohs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_reservation_ohs_proto_goTypes,
		DependencyIndexes: file_proto_inventory_reservation_ohs_proto_depIdxs,
		MessageInfos:      file_proto_inventory_reservation_ohs_proto_msgTypes,
	}.Build()
	File_proto_inventory_reservation_ohs_proto = out.File
	file_proto_inventory_reservation_ohs_proto_rawDesc = nil
	file_proto_inventory_reservation_ohs_proto_goTypes = nil
	file_proto_inventory_reservation_ohs_proto_depIdxs = nil
}
