// inventory-reservation-ohs (B2B-F2 / EF-API-1 internal plane). gRPC surface for the G2
// strong-local reserve/transition writes other contexts (B2B) use instead of REST.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/inventory_reservation_ohs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryReservationOhs_Reserve_FullMethodName    = "/dokandar.inventory.ohs.v1.InventoryReservationOhs/Reserve"
	InventoryReservationOhs_Transition_FullMethodName = "/dokandar.inventory.ohs.v1.InventoryReservationOhs/Transition"
)

// InventoryReservationOhsClient is the client API for InventoryReservationOhs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryReservationOhsClient interface {
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveReply, error)
	Transition(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*TransitionReply, error)
}

type inventoryReservationOhsClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryReservationOhsClient(cc grpc.ClientConnInterface) InventoryReservationOhsClient {
	return &inventoryReservationOhsClient{cc}
}

func (c *inventoryReservationOhsClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveReply)
	err := c.cc.Invoke(ctx, InventoryReservationOhs_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryReservationOhsClient) Transition(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*TransitionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionReply)
	err := c.cc.Invoke(ctx, InventoryReservationOhs_Transition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryReservationOhsServer is the server API for InventoryReservationOhs service.
// All implementations must embed UnimplementedInventoryReservationOhsServer
// for forward compatibility.
type InventoryReservationOhsServer interface {
	Reserve(context.Context, *ReserveRequest) (*ReserveReply, error)
	Transition(context.Context, *TransitionRequest) (*TransitionReply, error)
	mustEmbedUnimplementedInventoryReservationOhsServer()
}

// UnimplementedInventoryReservationOhsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryReservationOhsServer struct{}

func (UnimplementedInventoryReservationOhsServer) Reserve(context.Context, *ReserveRequest) (*ReserveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedInventoryReservationOhsServer) Transition(context.Context, *TransitionRequest) (*TransitionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transition not implemented")
}
func (UnimplementedInventoryReservationOhsServer) mustEmbedUnimplementedInventoryReservationOhsServer() {
}
func (UnimplementedInventoryReservationOhsServer) testEmbeddedByValue() {}

// UnsafeInventoryReservationOhsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryReservationOhsServer will
// result in compilation errors.
type UnsafeInventoryReservationOhsServer interface {
	mustEmbedUnimplementedInventoryReservationOhsServer()
}

func RegisterInventoryReservationOhsServer(s grpc.ServiceRegistrar, srv InventoryReservationOhsServer) {
	// If the following call pancis, it indicates UnimplementedInventoryReservationOhsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryReservationOhs_ServiceDesc, srv)
}

func _InventoryReservationOhs_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryReservationOhsServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryReservationOhs_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryReservationOhsServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryReservationOhs_Transition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryReservationOhsServer).Transition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryReservationOhs_Transition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryReservationOhsServer).Transition(ctx, req.(*TransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryReservationOhs_ServiceDesc is the grpc.ServiceDesc for InventoryReservationOhs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryReservationOhs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dokandar.inventory.ohs.v1.InventoryReservationOhs",
	HandlerType: (*InventoryReservationOhsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _InventoryReservationOhs_Reserve_Handler,
		},
		{
			MethodName: "Transition",
			Handler:    _InventoryReservationOhs_Transition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inventory_reservation_ohs.proto",
}
