# Generated Ansible inventory. The runner is reached on its PUBLIC IP (no VPN
# needed); the utilities host on its PRIVATE IP (connect the VPN first).
locals {
  keys_dir = abspath("${path.module}/../keys")
  ssh_args = "-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null"
}

resource "local_file" "platform_inventory" {
  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"

  content = <<-EOT
    # AUTO-GENERATED by Terraform. Do not edit by hand.
    # runner    -> public IP  (reachable directly, no VPN needed)
    # utilities -> private IP (connect the OpenVPN client FIRST)
    [runner]
    runner ansible_host=${aws_eip.runner.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${local.keys_dir}/${local.name}-gitlab-runner.pem ansible_ssh_common_args='${local.ssh_args}'

    [utilities]
    utilities ansible_host=${aws_instance.this["utilities"].private_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${local.keys_dir}/${local.name}-utilities.pem ansible_ssh_common_args='${local.ssh_args}'

    [platform:children]
    runner
    utilities
  EOT
}
