// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

namespace IdentitySvc.Validation;

/// <summary>
/// Input validation helpers for system boundary enforcement. Validate all external input before
/// processing (coding-style: fail fast with a clear error, never coerce silently).
/// ExceptionHandlingMiddleware converts ArgumentException to RFC-7807 400 responses.
/// </summary>
public static class InputValidator
{
    /// <summary>Throws <see cref="ArgumentException"/> when the value is null, empty, or whitespace.</summary>
    public static string Required(string fieldName, string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new ArgumentException($"{fieldName} is required", fieldName);
        return value;
    }

    /// <summary>Throws <see cref="ArgumentOutOfRangeException"/> when the value is not positive.</summary>
    public static int Positive(string fieldName, int value)
    {
        if (value <= 0)
            throw new ArgumentOutOfRangeException(fieldName, value, $"{fieldName} must be positive");
        return value;
    }

    /// <summary>
    /// Throws <see cref="ArgumentOutOfRangeException"/> when the value exceeds the allowed maximum length.
    /// </summary>
    public static string MaxLength(string fieldName, string value, int maxLength)
    {
        if (value.Length > maxLength)
            throw new ArgumentOutOfRangeException(
                fieldName, value.Length, $"{fieldName} must not exceed {maxLength} characters");
        return value;
    }
}
