// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/profile.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileQuery_LookupProfile_FullMethodName     = "/dokandar.profile.v1.ProfileQuery/LookupProfile"
	ProfileQuery_GetDefaultAddress_FullMethodName = "/dokandar.profile.v1.ProfileQuery/GetDefaultAddress"
)

// ProfileQueryClient is the client API for ProfileQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProfileQuery — east-west reads.
// Every RPC requires `x-internal-token` metadata equal to the service's
// configured INTERNAL_SERVICE_TOKEN; mismatch → UNAUTHENTICATED.
type ProfileQueryClient interface {
	LookupProfile(ctx context.Context, in *LookupProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	GetDefaultAddress(ctx context.Context, in *GetDefaultAddressRequest, opts ...grpc.CallOption) (*Address, error)
}

type profileQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileQueryClient(cc grpc.ClientConnInterface) ProfileQueryClient {
	return &profileQueryClient{cc}
}

func (c *profileQueryClient) LookupProfile(ctx context.Context, in *LookupProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, ProfileQuery_LookupProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileQueryClient) GetDefaultAddress(ctx context.Context, in *GetDefaultAddressRequest, opts ...grpc.CallOption) (*Address, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Address)
	err := c.cc.Invoke(ctx, ProfileQuery_GetDefaultAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileQueryServer is the server API for ProfileQuery service.
// All implementations must embed UnimplementedProfileQueryServer
// for forward compatibility.
//
// ProfileQuery — east-west reads.
// Every RPC requires `x-internal-token` metadata equal to the service's
// configured INTERNAL_SERVICE_TOKEN; mismatch → UNAUTHENTICATED.
type ProfileQueryServer interface {
	LookupProfile(context.Context, *LookupProfileRequest) (*Profile, error)
	GetDefaultAddress(context.Context, *GetDefaultAddressRequest) (*Address, error)
	mustEmbedUnimplementedProfileQueryServer()
}

// UnimplementedProfileQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileQueryServer struct{}

func (UnimplementedProfileQueryServer) LookupProfile(context.Context, *LookupProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupProfile not implemented")
}
func (UnimplementedProfileQueryServer) GetDefaultAddress(context.Context, *GetDefaultAddressRequest) (*Address, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultAddress not implemented")
}
func (UnimplementedProfileQueryServer) mustEmbedUnimplementedProfileQueryServer() {}
func (UnimplementedProfileQueryServer) testEmbeddedByValue()                      {}

// UnsafeProfileQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileQueryServer will
// result in compilation errors.
type UnsafeProfileQueryServer interface {
	mustEmbedUnimplementedProfileQueryServer()
}

func RegisterProfileQueryServer(s grpc.ServiceRegistrar, srv ProfileQueryServer) {
	// If the following call pancis, it indicates UnimplementedProfileQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileQuery_ServiceDesc, srv)
}

func _ProfileQuery_LookupProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileQueryServer).LookupProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileQuery_LookupProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileQueryServer).LookupProfile(ctx, req.(*LookupProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileQuery_GetDefaultAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileQueryServer).GetDefaultAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileQuery_GetDefaultAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileQueryServer).GetDefaultAddress(ctx, req.(*GetDefaultAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileQuery_ServiceDesc is the grpc.ServiceDesc for ProfileQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dokandar.profile.v1.ProfileQuery",
	HandlerType: (*ProfileQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupProfile",
			Handler:    _ProfileQuery_LookupProfile_Handler,
		},
		{
			MethodName: "GetDefaultAddress",
			Handler:    _ProfileQuery_GetDefaultAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/profile.proto",
}
