// Package grpcsrv implements the dokandar.wallet.v1.Wallet east-west service
// (GetBalance | DebitWallet | CreditWallet). Every RPC carries x-internal-token
// = the shared INTERNAL_SERVICE_TOKEN, compared constant-time, FAIL-CLOSED on
// empty (distinct from the REST guard's dev bypass — gRPC peers are never dev).
//
// The walletpb package is generated by protoc at image build (see Dockerfile)
// into internal/grpcsrv/walletpb. A //go:generate directive supports native
// rebuilds.
//
//go:generate protoc -I ../../proto --go_out=walletpb --go_opt=paths=source_relative --go-grpc_out=walletpb --go-grpc_opt=paths=source_relative wallet.proto
package grpcsrv

import (
	"context"
	"crypto/subtle"
	"errors"
	"net"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/reflection"
	"google.golang.org/grpc/status"

	"github.com/dokandar/dokandar-wallet/internal/grpcsrv/walletpb"
	"github.com/dokandar/dokandar-wallet/internal/service"
)

// Server adapts the ledger service to the gRPC contract.
type Server struct {
	walletpb.UnimplementedWalletServer
	Svc *service.Service
}

// internalAuthInterceptor enforces x-internal-token on every unary RPC.
// Constant-time compare; fail-closed when the configured token is empty.
func internalAuthInterceptor(want string) grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
		// Server reflection exposes only the service shape (not data) and is
		// needed by grpcurl to resolve message types — allow it unauthenticated.
		if strings.HasPrefix(info.FullMethod, "/grpc.reflection.") {
			return handler(ctx, req)
		}
		if want == "" {
			return nil, status.Error(codes.Unauthenticated, "internal token not configured")
		}
		md, _ := metadata.FromIncomingContext(ctx)
		got := ""
		if v := md.Get("x-internal-token"); len(v) > 0 {
			got = v[0]
		}
		if subtle.ConstantTimeCompare([]byte(got), []byte(want)) != 1 {
			return nil, status.Error(codes.Unauthenticated, "missing or invalid x-internal-token")
		}
		return handler(ctx, req)
	}
}

func (s *Server) GetBalance(ctx context.Context, r *walletpb.GetBalanceRequest) (*walletpb.BalanceResponse, error) {
	uid, err := uuid.Parse(r.GetUserId())
	if err != nil {
		return nil, status.Error(codes.InvalidArgument, "user_id must be a UUID")
	}
	w, err := s.Svc.GetOrCreate(ctx, uid)
	if err != nil {
		return nil, status.Error(codes.Internal, "could not load wallet")
	}
	return toBalance(w), nil
}

func (s *Server) DebitWallet(ctx context.Context, r *walletpb.DebitRequest) (*walletpb.BalanceResponse, error) {
	uid, err := uuid.Parse(r.GetUserId())
	if err != nil {
		return nil, status.Error(codes.InvalidArgument, "user_id must be a UUID")
	}
	if r.GetAmountMinor() <= 0 {
		return nil, status.Error(codes.InvalidArgument, "amount_minor must be > 0")
	}
	if len(r.GetIdempotencyKey()) < 8 {
		return nil, status.Error(codes.InvalidArgument, "idempotency_key required (min 8 chars)")
	}
	req := service.DebitReq{UserID: uid, AmountMinor: r.GetAmountMinor(), IdempotencyKey: r.GetIdempotencyKey()}
	if oid, err := uuid.Parse(r.GetOrderId()); err == nil {
		req.OrderID = &oid
	}
	w, err := s.Svc.Debit(ctx, req)
	if err != nil {
		return nil, mapLedgerErr(err)
	}
	return toBalance(w), nil
}

func (s *Server) CreditWallet(ctx context.Context, r *walletpb.CreditRequest) (*walletpb.BalanceResponse, error) {
	uid, err := uuid.Parse(r.GetUserId())
	if err != nil {
		return nil, status.Error(codes.InvalidArgument, "user_id must be a UUID")
	}
	if r.GetAmountMinor() <= 0 {
		return nil, status.Error(codes.InvalidArgument, "amount_minor must be > 0")
	}
	if len(r.GetIdempotencyKey()) < 8 {
		return nil, status.Error(codes.InvalidArgument, "idempotency_key required (min 8 chars)")
	}
	req := service.CreditReq{UserID: uid, AmountMinor: r.GetAmountMinor(), IdempotencyKey: r.GetIdempotencyKey(), Kind: r.GetKind()}
	if oid, err := uuid.Parse(r.GetOrderId()); err == nil {
		req.OrderID = &oid
	}
	w, err := s.Svc.Credit(ctx, req)
	if err != nil {
		return nil, mapLedgerErr(err)
	}
	return toBalance(w), nil
}

func mapLedgerErr(err error) error {
	switch {
	case errors.Is(err, service.ErrInsufficientBalance):
		return status.Error(codes.FailedPrecondition, "insufficient_balance")
	case errors.Is(err, service.ErrWalletMaxExceeded):
		return status.Error(codes.FailedPrecondition, "wallet_max_exceeded")
	case errors.Is(err, service.ErrInvalidAmount):
		return status.Error(codes.InvalidArgument, "invalid_amount")
	default:
		return status.Error(codes.Internal, "ledger error")
	}
}

func toBalance(w *service.Wallet) *walletpb.BalanceResponse {
	return &walletpb.BalanceResponse{
		UserId:         w.UserID.String(),
		BalanceMinor:   w.BalanceMinor,
		AvailableMinor: w.AvailableMinor,
		Currency:       w.Currency,
		Status:         w.Status,
	}
}

// Serve binds the gRPC server on addr, enforcing the internal-token interceptor,
// and runs until ctx is canceled (GracefulStop).
func Serve(ctx context.Context, addr, internalToken string, s *Server) error {
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		return err
	}
	srv := grpc.NewServer(grpc.UnaryInterceptor(internalAuthInterceptor(internalToken)))
	walletpb.RegisterWalletServer(srv, s)
	reflection.Register(srv) // so grpcurl works without local .proto files
	go func() {
		<-ctx.Done()
		srv.GracefulStop()
	}()
	return srv.Serve(lis)
}
