// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

/** Canon-named operational constants (configuration.yaml). Values verbatim from canon. */

export const COOLING_OFF_WINDOW = 259200000n; // 72h — finance.escrow
export const ESCROW_ABANDON_TTL = 604800000n; // 7d — finance.escrow
export const NIL_ROLLUP_MAX_LAG = 60000n; // 60s — inventory.nil
export const B2_B_DELIVERY_MIN_LEAD = 86400000n; // 24h — b2b.contractterms
export const MONEY_CUSTODY_RPO = 0n; //  — finance+custody
