// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

import type { ProblemDetails } from "./errors.js";

/** Common DTOs: the {success,data,error,meta} envelope, cursor pagination, trace/audit metadata. */
export interface PageMeta { nextCursor?: string; hasMore: boolean; limit: number; }
export interface TraceMetadata { traceId?: string; spanId?: string; correlationId?: string; }
export interface AuditMetadata { actorDid?: string; occurredAtMs?: number; requestId?: string; }
export interface Meta { page?: PageMeta; trace?: TraceMetadata; extra?: Record<string, unknown>; }

export interface Response<T> {
  success: boolean;
  data?: T;
  error?: ProblemDetails;
  meta?: Meta;
}
export function ok<T>(data: T, meta?: Meta): Response<T> { return { success: true, data, meta }; }
export function fail<T>(error: ProblemDetails, meta?: Meta): Response<T> { return { success: false, error, meta }; }

export interface Page<T> { items: T[]; page: PageMeta; }
