// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

/** Error taxonomy (error-codes.yaml): dokandar.<context>.<category>.<reason> (RFC-7807).
 * Concrete codes are NEEDS-INFO in the frozen contracts, so this provides the builder +
 * context-slug enum + exception hierarchy + ProblemDetails — never a fabricated code list. */

export enum ContextSlug {
  IDENTITY = "identity",
  CATALOG = "catalog",
  CUSTODY = "custody",
  PROVENANCE = "provenance",
  INVENTORY = "inventory",
  B2C = "b2c",
  B2B = "b2b",
  FINANCE = "finance",
  LOGISTICS = "logistics",
  FRAUD = "fraud",
  GOVERNMENT = "government",
  ANALYTICS = "analytics",
  PLATFORM = "platform",
  EDGE = "edge",
}

export const CONTEXT_SLUGS: readonly string[] = ["identity", "catalog", "custody", "provenance", "inventory", "b2c", "b2b", "finance", "logistics", "fraud", "government", "analytics", "platform", "edge"];
const CODE_RE = /^dokandar\.([a-z]+)\.([a-z0-9_]+)\.([a-z0-9_]+)$/;

export function errorCode(context: string, category: string, reason: string): string {
  const code = `dokandar.${context}.${category}.${reason}`;
  if (!CONTEXT_SLUGS.includes(context)) throw new Error(`unknown context slug: ${context}`);
  if (!CODE_RE.test(code)) throw new Error(`error code violates taxonomy: ${code}`);
  return code;
}

export interface ProblemDetails {
  type: string; title: string; status: number; code: string;
  detail?: string; instance?: string; traceId?: string;
  /** RFC-7807 extension: seconds until retry, mirrored into a `Retry-After` header (429/503). */
  retryAfter?: number;
}

export class DokandarError extends Error {
  readonly httpStatus: number = 500;
  constructor(public readonly code: string, message: string, public readonly detail?: string) {
    super(message);
    this.name = new.target.name;
  }
  toProblem(): ProblemDetails {
    return { type: "about:blank", title: this.message, status: this.httpStatus, code: this.code, detail: this.detail };
  }
  /** Response headers this error implies (e.g. `Retry-After`); empty by default. */
  headers(): Record<string, string> { return {}; }
}

// PL-06: the full canon HTTP-status vocabulary (EF-API-3). The coarse 400/409/503 mapping
// conflated malformed input with business-validation and had no 403/422/423/429/202.
export enum HttpStatus {
  OK = 200,
  ACCEPTED = 202,            // async accepted: escrow/payout in-flight
  BAD_REQUEST = 400,         // malformed request (syntax/shape)
  FORBIDDEN = 403,           // authz / four-eyes denial
  CONFLICT = 409,            // state conflict / idempotency-key payload mismatch
  UNPROCESSABLE = 422,       // business-validation failure (well-formed but invalid)
  LOCKED = 423,              // park-and-freeze / fence hold
  TOO_MANY_REQUESTS = 429,   // rate limit
  SERVICE_UNAVAILABLE = 503, // dependency/infrastructure unavailable
}

/** 400 — malformed request: bad syntax/shape. Was the old ValidationError semantic. */
export class MalformedError extends DokandarError { override readonly httpStatus = HttpStatus.BAD_REQUEST; }
/** 422 — business-validation: well-formed but violates a business rule (split from 400). */
export class BusinessValidationError extends DokandarError { override readonly httpStatus = HttpStatus.UNPROCESSABLE; }
/** 403 — authz / four-eyes denial (R4/R5). */
export class AuthorizationError extends DokandarError { override readonly httpStatus = HttpStatus.FORBIDDEN; }
/** 409 — state conflict or idempotency-key payload mismatch. */
export class StateConflictError extends DokandarError { override readonly httpStatus = HttpStatus.CONFLICT; }
/** 423 — park-and-freeze / fence hold (money/custody poison quarantine). */
export class LockedError extends DokandarError { override readonly httpStatus = HttpStatus.LOCKED; }
/** 429 — rate limited; carries a `Retry-After` (seconds). */
export class RateLimitError extends DokandarError {
  override readonly httpStatus = HttpStatus.TOO_MANY_REQUESTS;
  constructor(code: string, message: string, public readonly retryAfterSeconds: number, detail?: string) {
    super(code, message, detail);
  }
  override toProblem(): ProblemDetails { return { ...super.toProblem(), retryAfter: this.retryAfterSeconds }; }
  override headers(): Record<string, string> { return { "retry-after": String(this.retryAfterSeconds) }; }
}

// Backwards-compatible aliases (kept so existing callers keep compiling):
// ValidationError historically meant 400 (malformed); BusinessError 409; InfrastructureError 503.
export class ValidationError extends DokandarError { override readonly httpStatus = HttpStatus.BAD_REQUEST; }
export class BusinessError extends DokandarError { override readonly httpStatus = HttpStatus.CONFLICT; }
export class InfrastructureError extends DokandarError { override readonly httpStatus = HttpStatus.SERVICE_UNAVAILABLE; }

/**
 * Canon category → HTTP status (EF-API-3). Categories are the `<category>` segment of a
 * `dokandar.<context>.<category>.<reason>` code. `async` maps to 202 (accepted, not an error).
 */
export const CATEGORY_STATUS: Readonly<Record<string, number>> = {
  malformed: HttpStatus.BAD_REQUEST,
  validation: HttpStatus.UNPROCESSABLE,
  authz: HttpStatus.FORBIDDEN,
  four_eyes: HttpStatus.FORBIDDEN,
  state: HttpStatus.CONFLICT,
  idempotency: HttpStatus.CONFLICT,
  locked: HttpStatus.LOCKED,
  fence: HttpStatus.LOCKED,
  rate_limit: HttpStatus.TOO_MANY_REQUESTS,
  async: HttpStatus.ACCEPTED,
  unavailable: HttpStatus.SERVICE_UNAVAILABLE,
};

/** Map a canon error category to its HTTP status; unknown categories default to 500. */
export function statusForCategory(category: string): number {
  return CATEGORY_STATUS[category] ?? 500;
}
