// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

// dkd_platform — generated DOKANDAR platform SDK (TypeScript).
export * from "./provenance.js";
export * from "./money.js";
export * from "./ids.js";
export * from "./topics.js";
export * from "./config.js";
export * from "./enums.js";
export * from "./errors.js";
export * from "./dto.js";
export * from "./events.js";
export * from "./schema.js";
export * from "./security.js";
export * from "./validation.js";
export * from "./apidocs.js";
export * as custodyHash from "./custody_hash.js"; // hand-authored primitive (CustodyHash Spec v2)
export * from "./outbox.js";  // hand-authored primitive (transactional outbox + relay, PL-02)
export * from "./inbox.js";   // hand-authored primitive (consumer inbox dedup, PL-02)
export * from "./dlq.js";     // hand-authored primitive (DLQ park-and-freeze, PL-02)
export * from "./uuid7.js";       // hand-authored primitive (UUID v7 generator + validator, PL-04)
export * from "./trace.js";       // hand-authored primitive (W3C traceparent propagation, PL-05)
export * from "./idempotency.js"; // hand-authored primitive (Idempotency-Key enforcement, PL-03)
