// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

export const GENERATOR = "dkdgen";
export const GENERATOR_VERSION = "1.0.0";
export const CONTRACT_VERSION = "1.0.0";
export const BUILD_TIME = "2026-06-29T00:00:00Z";
export const BUILD_COMMIT = "source";
