// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

/** Security helpers: access principles, JWT claim names, correlation/trace propagation.
 * Role families live in ./enums.ts (one source per symbol; exported at the package root).
 * The permission MATRIX is NEEDS-INFO (permissions.yaml) — principle constants only. */

export const PRINCIPLES: Readonly<Record<string, string>> = {
  "R1-custody-sole-writer": "Only custody-ledger-svc writes custody.*; all others are read-only consumers.",
  "R2-finance-isolation": "Finance DB reachable only by Finance; DID->wallet resolution happens inside Finance.",
  "R4-four-eyes": "Finance/Custody/Fraud/Government mutations require two DISTINCT human approvers (approver2 != approver1); only an enumerated narrow reversible-hold set is autonomous.",
  "R5-government-readonly": "Government has SELECT-only grants; intervenes on operational aggregates only via audited four-eyes directives.",
  "read-only-contexts": "Provenance(#4), Inventory(#5 vs custody), Analytics(#12) are read-only projections; never write the source of truth.",
  "pii-confinement": "PII lives only in Identity(#1); other contexts resolve via the Identity OHS; payloads carry IDs only (R6).",
};

export const JwtClaims = {
  SUBJECT_DID: "sub", KYC_TIER: "kyc_tier", ROLES: "roles", CORRELATION_ID: "cid",
} as const;

import { type TraceParent, formatTraceparent, parseTraceparent } from "./trace.js";

export class CorrelationContext {
  /**
   * @param traceparent a W3C trace context — a parsed {@link TraceParent} or a raw wire string.
   *   A malformed string is dropped (no `traceparent` header emitted), never propagated as-is.
   */
  constructor(
    public correlationId?: string,
    public traceparent?: TraceParent | string,
    public actorDid?: string,
  ) {}
  headers(): Record<string, string> {
    const h: Record<string, string> = {};
    if (this.correlationId) h["x-correlation-id"] = this.correlationId;
    const tp = typeof this.traceparent === "string" ? parseTraceparent(this.traceparent) : this.traceparent;
    if (tp) h["traceparent"] = formatTraceparent(tp);
    return h;
  }
}
