// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

import { PrefixedId } from "./ids.js";
import { Money } from "./money.js";
import { TOPIC_META } from "./topics.js";

type IdCtor<T extends PrefixedId> = new (value: string) => T;

export function validateId<T extends PrefixedId>(ctor: IdCtor<T>, value: string): T {
  return new ctor(value);
}
export function isValidId<T extends PrefixedId>(ctor: IdCtor<T>, value: string): boolean {
  try { new ctor(value); return true; } catch { return false; }
}
export function validateMoney(poisha: bigint): Money { return new Money(poisha); }
export function validateTopic(name: string): boolean { return name in TOPIC_META; }
