// custody-passport-ohs (B2B-F2 / R6 internal plane). Read-only gRPC OHS for a passport head —
// the gRPC surface other contexts (e.g. B2B) use instead of the REST GET, per EF-API-1.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/custody_passport_ohs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustodyPassportOhs_GetPassport_FullMethodName = "/dokandar.custody.ohs.v1.CustodyPassportOhs/GetPassport"
)

// CustodyPassportOhsClient is the client API for CustodyPassportOhs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustodyPassportOhsClient interface {
	GetPassport(ctx context.Context, in *GetPassportRequest, opts ...grpc.CallOption) (*PassportReply, error)
}

type custodyPassportOhsClient struct {
	cc grpc.ClientConnInterface
}

func NewCustodyPassportOhsClient(cc grpc.ClientConnInterface) CustodyPassportOhsClient {
	return &custodyPassportOhsClient{cc}
}

func (c *custodyPassportOhsClient) GetPassport(ctx context.Context, in *GetPassportRequest, opts ...grpc.CallOption) (*PassportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PassportReply)
	err := c.cc.Invoke(ctx, CustodyPassportOhs_GetPassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustodyPassportOhsServer is the server API for CustodyPassportOhs service.
// All implementations must embed UnimplementedCustodyPassportOhsServer
// for forward compatibility.
type CustodyPassportOhsServer interface {
	GetPassport(context.Context, *GetPassportRequest) (*PassportReply, error)
	mustEmbedUnimplementedCustodyPassportOhsServer()
}

// UnimplementedCustodyPassportOhsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustodyPassportOhsServer struct{}

func (UnimplementedCustodyPassportOhsServer) GetPassport(context.Context, *GetPassportRequest) (*PassportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassport not implemented")
}
func (UnimplementedCustodyPassportOhsServer) mustEmbedUnimplementedCustodyPassportOhsServer() {}
func (UnimplementedCustodyPassportOhsServer) testEmbeddedByValue()                            {}

// UnsafeCustodyPassportOhsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustodyPassportOhsServer will
// result in compilation errors.
type UnsafeCustodyPassportOhsServer interface {
	mustEmbedUnimplementedCustodyPassportOhsServer()
}

func RegisterCustodyPassportOhsServer(s grpc.ServiceRegistrar, srv CustodyPassportOhsServer) {
	// If the following call pancis, it indicates UnimplementedCustodyPassportOhsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustodyPassportOhs_ServiceDesc, srv)
}

func _CustodyPassportOhs_GetPassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodyPassportOhsServer).GetPassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustodyPassportOhs_GetPassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodyPassportOhsServer).GetPassport(ctx, req.(*GetPassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustodyPassportOhs_ServiceDesc is the grpc.ServiceDesc for CustodyPassportOhs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustodyPassportOhs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dokandar.custody.ohs.v1.CustodyPassportOhs",
	HandlerType: (*CustodyPassportOhsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPassport",
			Handler:    _CustodyPassportOhs_GetPassport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/custody_passport_ohs.proto",
}
