// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;

/** Platform API Documentation Standard: OpenAPI document "v1" + Bearer (JWT) security scheme.
 *  Auto-configured from the SDK — services inherit identical docs with no Swagger code. */
@AutoConfiguration
public class DkdApiDocs {
    @Bean
    @ConditionalOnMissingBean
    public OpenAPI dkdOpenAPI(org.springframework.core.env.Environment env) {
        String title = env.getProperty("spring.application.name", "DOKANDAR service");
        return new OpenAPI()
            .info(new Info().title(title).version("v1").description(title + " REST API."))
            .components(new Components().addSecuritySchemes("Bearer",
                new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("bearer").bearerFormat("JWT")
                    .description("JWT bearer token (injected by the API gateway in production).")));
    }
}
