// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

import java.util.List;
import java.util.Map;

/** Common DTOs: the {success,data,error,meta} envelope, cursor pagination, trace/audit metadata. */
public final class Dto {
    private Dto() {}
    public record PageMeta(String nextCursor, boolean hasMore, int limit) {}
    public record TraceMetadata(String traceId, String spanId, String correlationId) {}
    public record AuditMetadata(String actorDid, long occurredAtMs, String requestId) {}
    public record Meta(PageMeta page, TraceMetadata trace, Map<String, Object> extra) {}

    public record Response<T>(boolean success, T data, Errors.ProblemDetails error, Meta meta) {
        public static <T> Response<T> ok(T data, Meta meta) { return new Response<>(true, data, null, meta); }
        public static <T> Response<T> fail(Errors.ProblemDetails error, Meta meta) { return new Response<>(false, null, error, meta); }
    }
    public record Page<T>(List<T> items, PageMeta page) {}
}
