// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

/** Event envelope/base + headers + metadata + topic binding + serializer interface.
  * Per-event PAYLOAD types are FRAMEWORK-ONLY (schema-registry subjects are NEEDS-INFO): EventEnvelope
  * is generic over the payload; concrete payloads bind on Phase-2 contract population. */
public final class Events {
    private Events() {}
    public record EventHeaders(String eventId, long occurredAtMs, int producerContext, String partitionKey,
                               String correlationId, String traceId, int schemaVersion) {}
    public record EventMetadata(String topic, Topics.TopicMeta meta) {}
    public record EventEnvelope<P>(EventHeaders headers, String topic, P payload) {}
    public interface PayloadSerializer<P> { byte[] serialize(P payload); P deserialize(byte[] data); }
    public static EventMetadata eventMetadataFor(String topic) { return new EventMetadata(topic, Topics.topicMeta(topic)); }
}
