// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

public final class Money {
    public static final long POISHA_PER_BDT = 100L;
    public final long poisha;
    public Money(long poisha) { this.poisha = poisha; }
    public static Money ofBdt(long bdt) { return new Money(bdt * POISHA_PER_BDT); }
    @Override public boolean equals(Object o) { return o instanceof Money m && m.poisha == poisha; }
    @Override public int hashCode() { return Long.hashCode(poisha); }
    @Override public String toString() { return "Money(" + poisha + " poisha)"; }
}
