// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

public final class Provenance {
    private Provenance() {}
    public static final String GENERATOR = "dkdgen";
    public static final String GENERATOR_VERSION = "1.0.0";
    public static final String CONTRACT_VERSION = "1.0.0";
    public static final String BUILD_TIME = "2026-06-29T00:00:00Z";
    public static final String BUILD_COMMIT = "source";
}
