// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

public final class Timestamp {
    public final long epochMs;
    public Timestamp(long epochMs) { this.epochMs = epochMs; }
    @Override public boolean equals(Object o) { return o instanceof Timestamp t && t.epochMs == epochMs; }
    @Override public int hashCode() { return Long.hashCode(epochMs); }
}
