// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

/** Validation utilities. */
public final class Validation {
    private Validation() {}
    public static boolean validateTopic(String name) { return Topics.META.containsKey(name); }
    public static long validateMoney(long poisha) { return poisha; }
}
