// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

// Canon-named operational constants (configuration.yaml). Values verbatim from canon.

const (
	COOLINGOFFWINDOW int64 = 259200000 // 72h — finance.escrow
	ESCROWABANDONTTL int64 = 604800000 // 7d — finance.escrow
	NILROLLUPMAXLAG int64 = 60000 // 60s — inventory.nil
	B2BDELIVERYMINLEAD int64 = 86400000 // 24h — b2b.contractterms
	MONEYCUSTODYRPO int64 = 0 //  — finance+custody
)
