// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using Dkd.Platform;
using Microsoft.AspNetCore.Http;

namespace IdentitySvc.Http;

/// <summary>
/// Standard health, readiness, liveness, and version endpoints. No business logic.
/// The {success, data, error} response envelope follows the Dokandar REST standard.
/// </summary>
public static class HealthEndpoints
{
    public static IResult Health() =>
        Results.Ok(new { success = true, data = new { status = "ok" } });

    public static IResult Live() =>
        Results.Ok(new { success = true, data = new { status = "alive" } });

    /// <summary>
    /// Readiness: returns 503 until the startup gate (migrations + dependency checks) succeeds.
    /// ASP.NET Core resolves ReadinessState from DI automatically when declared as a parameter.
    /// </summary>
    public static IResult Ready(ReadinessState state) =>
        state.IsReady
            ? Results.Ok(new { success = true, data = new { status = "ready" } })
            : Results.Json(
                new { success = false, error = new { status = "not-ready" } },
                statusCode: StatusCodes.Status503ServiceUnavailable);

    /// <summary>
    /// Version: reports the dkd-platform SDK contract version for provenance traceability.
    /// ContractVersion is sourced from the Dkd.Platform NuGet package (dkd-platform-libs).
    /// </summary>
    public static IResult Version() =>
        Results.Ok(new { success = true, data = new
        {
            service         = "identity-svc",
            // ID-06 / CC-CONS-1: real single-SHA provenance from the deploy build-args (env), with a
            // safe fallback to the SDK placeholder when built outside the pipeline.
            gitSha          = Environment.GetEnvironmentVariable("DKD_GIT_SHA") is { Length: > 0 } sha ? sha : Provenance.BuildCommit,
            version         = Environment.GetEnvironmentVariable("DKD_VERSION") is { Length: > 0 } ver ? ver : "0.0.0-dev",
            buildTime       = Environment.GetEnvironmentVariable("DKD_BUILD_TIME") is { Length: > 0 } bt ? bt : "unknown",
            contractVersion = Provenance.ContractVersion,
            sdkGenerator    = Provenance.Generator,
        }});
}
