// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

namespace IdentitySvc.Http;

/// <summary>
/// Readiness gate: flipped to true after startup migrations and dependency checks succeed.
/// Consumed by the /ready probe. Use a volatile field to ensure cross-thread visibility without
/// locking — the write happens once at startup before traffic is accepted.
/// </summary>
public sealed class ReadinessState
{
    private volatile bool _ready;

    public bool IsReady
    {
        get => _ready;
        set => _ready = value;
    }
}
