"""Generator + build provenance stamped into every generated artifact."""
from __future__ import annotations
import os

GENERATOR_NAME = "dkdgen"
GENERATOR_VERSION = "1.0.0"


def build_metadata(spine_version: str, build_time: str | None = None) -> dict:
    """Provenance block embedded in every generated file header.
    build_time is injected (never wall-clock here) so generation is reproducible/deterministic.
    """
    return {
        "generator": GENERATOR_NAME,
        "generator_version": GENERATOR_VERSION,
        "contract_version": spine_version,
        # Deterministic by default so committed SDK source is stable (drift gate). The publish
        # pipeline overrides DKDGEN_BUILD_TIME/DKDGEN_BUILD_COMMIT to stamp live values on artifacts.
        "build_time": build_time or os.environ.get("DKDGEN_BUILD_TIME", "2026-06-29T00:00:00Z"),
        "build_commit": os.environ.get("DKDGEN_BUILD_COMMIT", "source"),
    }


def banner(meta: dict, comment: str = "//") -> str:
    """A do-not-edit provenance banner in the target language's comment syntax."""
    lines = [
        "DO NOT EDIT — generated by %s v%s from dkd-contracts-spine@%s" % (
            meta["generator"], meta["generator_version"], meta["contract_version"]),
        "Source of truth: the frozen contracts. Regenerate via `dkdgen generate`.",
        "build_time=%s build_commit=%s" % (meta["build_time"], meta["build_commit"]),
    ]
    return "\n".join("%s %s" % (comment, ln) for ln in lines)
