// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

using Xunit;

public class SdkTests
{
    [Fact]
    public void ProvenanceVersion() => Assert.Equal("1.0.0", Dkd.Platform.Provenance.ContractVersion);

    [Fact]
    public void IdsTypedAndValidated()
    {
        var d = new DID("did:dokandar:abc");
        Assert.Equal("did:dokandar:abc", d.ToString());
        Assert.True(DID.Immutable);
        Assert.Equal(1, DID.OwnerContext);
        Assert.Throws<System.ArgumentException>(() => new PPID("did:dokandar:x"));
    }

    [Fact]
    public void Topics_59_WithMeta()
    {
        Assert.Equal(59, Dkd.Platform.Topics.Meta.Count);
        Assert.Equal(3, Dkd.Platform.Topics.TopicMetaFor("custody.passport.CustodyInitialized.v1").Producer);
    }

    [Fact]
    public void MoneyIsInt64() => Assert.Equal(5000L, new Money(5000L).Poisha);

    [Fact]
    public void ErrorTaxonomy()
    {
        Assert.Equal("dokandar.finance.idempotency.duplicate_key",
                     Errors.ErrorCode("finance", "idempotency", "duplicate_key"));
        Assert.Throws<System.ArgumentException>(() => Errors.ErrorCode("frobnicate", "x", "y"));
    }
}
