// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

/** Canonical enum families (glossary.yaml; FR-IDN-310). Values transcribed verbatim. */

export enum KycTiers {
  V0 = "V0",
  V1 = "V1",
  V2 = "V2",
  V3 = "V3",
}

export enum FraudDetectors {
  HOARDING = "HOARDING",
  PASSPORT_FORGERY = "PASSPORT_FORGERY",
  GHOST_SPLIT = "GHOST_SPLIT",
  MFS_STRUCTURING = "MFS_STRUCTURING",
  SUBSIDY_DUP = "SUBSIDY_DUP",
  CIRCULAR_TRADE = "CIRCULAR_TRADE",
  VELOCITY_ANOMALY = "VELOCITY_ANOMALY",
  GEO_IMPOSSIBLE = "GEO_IMPOSSIBLE",
  COLLUSION_RING = "COLLUSION_RING",
}
// NOTE: contract marks this family non-exhaustive (illustrative).

export enum FraudCaseStates {
  OPEN = "OPEN",
  INVESTIGATING = "INVESTIGATING",
  SUBSTANTIATED = "SUBSTANTIATED",
  ENFORCED = "ENFORCED",
  DISMISSED = "DISMISSED",
}
// NOTE: contract marks this family non-exhaustive (illustrative).

export enum EnforcementActions {
  WARN = "WARN",
  RESTRICT_LISTING = "RESTRICT_LISTING",
  SUSPEND = "SUSPEND",
  BLACKLIST = "BLACKLIST",
  LICENSE_REVOKE = "LICENSE_REVOKE",
}
// NOTE: contract marks this family non-exhaustive (illustrative).

export enum OversightRoles {
  ANALYST = "ANALYST",
  INVESTIGATOR = "INVESTIGATOR",
  ENFORCEMENT_OFFICER = "ENFORCEMENT_OFFICER",
  APPROVER = "APPROVER",
  SUPER_ADMIN = "SUPER_ADMIN",
}
// NOTE: contract marks this family non-exhaustive (illustrative).

export enum PartyActorCodes {
  FARIA = "FARIA",
  WHOLESALER = "WHOLESALER",
  RETAIL = "RETAIL",
  GOV = "GOV",
  PERSON = "PERSON",
  ORG = "ORG",
}
// NOTE: contract marks this family non-exhaustive (illustrative).

export enum CommodityUnits {
  SEER = "seer",
  MAUND = "maund",
  BOSTA = "bosta",
}
// NOTE: contract marks this family non-exhaustive (illustrative).
