// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

/** Error taxonomy (error-codes.yaml): dokandar.<context>.<category>.<reason> (RFC-7807).
 * Concrete codes are NEEDS-INFO in the frozen contracts, so this provides the builder +
 * context-slug enum + exception hierarchy + ProblemDetails — never a fabricated code list. */

export enum ContextSlug {
  IDENTITY = "identity",
  CATALOG = "catalog",
  CUSTODY = "custody",
  PROVENANCE = "provenance",
  INVENTORY = "inventory",
  B2C = "b2c",
  B2B = "b2b",
  FINANCE = "finance",
  LOGISTICS = "logistics",
  FRAUD = "fraud",
  GOVERNMENT = "government",
  ANALYTICS = "analytics",
  PLATFORM = "platform",
  EDGE = "edge",
}

export const CONTEXT_SLUGS: readonly string[] = ["identity", "catalog", "custody", "provenance", "inventory", "b2c", "b2b", "finance", "logistics", "fraud", "government", "analytics", "platform", "edge"];
const CODE_RE = /^dokandar\.([a-z]+)\.([a-z0-9_]+)\.([a-z0-9_]+)$/;

export function errorCode(context: string, category: string, reason: string): string {
  const code = `dokandar.${context}.${category}.${reason}`;
  if (!CONTEXT_SLUGS.includes(context)) throw new Error(`unknown context slug: ${context}`);
  if (!CODE_RE.test(code)) throw new Error(`error code violates taxonomy: ${code}`);
  return code;
}

export interface ProblemDetails {
  type: string; title: string; status: number; code: string;
  detail?: string; instance?: string; traceId?: string;
}

export class DokandarError extends Error {
  readonly httpStatus: number = 500;
  constructor(public readonly code: string, message: string, public readonly detail?: string) {
    super(message);
    this.name = new.target.name;
  }
  toProblem(): ProblemDetails {
    return { type: "about:blank", title: this.message, status: this.httpStatus, code: this.code, detail: this.detail };
  }
}
export class ValidationError extends DokandarError { override readonly httpStatus = 400; }
export class BusinessError extends DokandarError { override readonly httpStatus = 409; }
export class InfrastructureError extends DokandarError { override readonly httpStatus = 503; }
