// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

import { topicMeta, type TopicMeta } from "./topics.js";

/** Event envelope/base + headers + metadata + topic binding + serializer interface.
 * Per-event PAYLOAD types are FRAMEWORK-ONLY (schema-registry.yaml subjects are NEEDS-INFO):
 * EventEnvelope is generic over the payload; concrete payloads bind on Phase-2 contract population. */
export interface EventHeaders {
  eventId: string;          // inbox dedup key
  occurredAtMs: number;
  producerContext: number;
  partitionKey: string;     // per-aggregate ordering key
  correlationId?: string;
  traceId?: string;
  schemaVersion: number;
}

export interface EventMetadata { topic: string; meta: TopicMeta; }
export function eventMetadataFor(topic: string): EventMetadata {
  return { topic, meta: topicMeta(topic) };
}

export interface EventEnvelope<P> {
  headers: EventHeaders;
  topic: string;
  payload: P;               // contract-populated in Phase 2 (NEEDS-INFO)
}

export interface PayloadSerializer<P> {
  serialize(payload: P): Uint8Array;
  deserialize(data: Uint8Array): P;
}
