// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

/** Strongly-typed identifiers (ids.yaml). No raw-string IDs. */

export abstract class PrefixedId {
  static readonly PREFIX: string = "";
  static readonly OWNER_CONTEXT: number = 0;
  static readonly IMMUTABLE: boolean = false;
  constructor(public readonly value: string) {
    const prefix = (this.constructor as typeof PrefixedId).PREFIX;
    if (typeof value !== "string" || !value.startsWith(prefix) || value.length <= prefix.length) {
      throw new Error(`${this.constructor.name} must start with '${prefix}' and carry a body`);
    }
  }
  toString(): string { return this.value; }
}

export class DID extends PrefixedId {
  static override readonly PREFIX = "did:dokandar:";
  static override readonly OWNER_CONTEXT = 1; // identity
  static override readonly IMMUTABLE = true;
}

export class PPID extends PrefixedId {
  static override readonly PREFIX = "PP-";
  static override readonly OWNER_CONTEXT = 3; // custody
  static override readonly IMMUTABLE = false;
}

export class GPID extends PrefixedId {
  static override readonly PREFIX = "GP-";
  static override readonly OWNER_CONTEXT = 2; // catalog
  static override readonly IMMUTABLE = false;
}

export class ORD extends PrefixedId {
  static override readonly PREFIX = "ORD-";
  static override readonly OWNER_CONTEXT = 6; // b2c
  static override readonly IMMUTABLE = false;
}

export class TRD extends PrefixedId {
  static override readonly PREFIX = "TRD-";
  static override readonly OWNER_CONTEXT = 7; // b2b
  static override readonly IMMUTABLE = false;
}

export class WLT extends PrefixedId {
  static override readonly PREFIX = "WLT-";
  static override readonly OWNER_CONTEXT = 8; // finance
  static override readonly IMMUTABLE = false;
}

export class ESC extends PrefixedId {
  static override readonly PREFIX = "ESC-";
  static override readonly OWNER_CONTEXT = 8; // finance
  static override readonly IMMUTABLE = false;
}

export class TXN extends PrefixedId {
  static override readonly PREFIX = "TXN-";
  static override readonly OWNER_CONTEXT = 8; // finance
  static override readonly IMMUTABLE = false;
}

export class SHP extends PrefixedId {
  static override readonly PREFIX = "SHP-";
  static override readonly OWNER_CONTEXT = 9; // logistics
  static override readonly IMMUTABLE = false;
}

export class NTF extends PrefixedId {
  static override readonly PREFIX = "NTF-";
  static override readonly OWNER_CONTEXT = 13; // platform
  static override readonly IMMUTABLE = false;
}

export class MFSA extends PrefixedId {
  static override readonly PREFIX = "MFSA-";
  static override readonly OWNER_CONTEXT = 8; // finance
  static override readonly IMMUTABLE = false;
}
