// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

export const POISHA_PER_BDT = 100n;

/** Money is int64 poisha (bigint). Float/decimal/string money is banned (DM type conventions). */
export class Money {
  constructor(public readonly poisha: bigint) {
    if (typeof poisha !== "bigint") {
      throw new TypeError("Money must be a bigint poisha");
    }
  }
  static ofBdt(bdt: bigint): Money {
    return new Money(bdt * POISHA_PER_BDT);
  }
  equals(o: Money): boolean { return o instanceof Money && o.poisha === this.poisha; }
  toString(): string { return `Money(${this.poisha} poisha)`; }
}

/** Unix milliseconds, UTC (int64). */
export class Timestamp {
  constructor(public readonly epochMs: bigint) {
    if (typeof epochMs !== "bigint") {
      throw new TypeError("Timestamp must be a bigint epochMs");
    }
  }
}
