// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

/** Schema-registry metadata (schema-registry.yaml): subjects + compatibility + version helpers.
 * Per-subject JSON-Schema is NEEDS-INFO, so getSchema() is an extension point that throws
 * until populated — never a fabricated schema. */

export enum Compatibility { BACKWARD = "BACKWARD" }

export interface SubjectInfo { subject: string; topic: string; compatibility: string; schemaStatus: string; }

export const SUBJECTS: Readonly<Record<string, SubjectInfo>> = {
  "identity.party.PartyRegistered.v1": { subject: "identity.party.PartyRegistered.v1", topic: "identity.party.PartyRegistered.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "identity.party.KYCApproved.v1": { subject: "identity.party.KYCApproved.v1", topic: "identity.party.KYCApproved.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "identity.party.KYCTierChanged.v1": { subject: "identity.party.KYCTierChanged.v1", topic: "identity.party.KYCTierChanged.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "identity.party.KYCRejected.v1": { subject: "identity.party.KYCRejected.v1", topic: "identity.party.KYCRejected.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "identity.party.PartySuspended.v1": { subject: "identity.party.PartySuspended.v1", topic: "identity.party.PartySuspended.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "identity.party.PartyReactivated.v1": { subject: "identity.party.PartyReactivated.v1", topic: "identity.party.PartyReactivated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "catalog.product.ProductCreated.v1": { subject: "catalog.product.ProductCreated.v1", topic: "catalog.product.ProductCreated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "catalog.product.ProductPublished.v1": { subject: "catalog.product.ProductPublished.v1", topic: "catalog.product.ProductPublished.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "catalog.product.ProductDeprecated.v1": { subject: "catalog.product.ProductDeprecated.v1", topic: "catalog.product.ProductDeprecated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "catalog.product.ProductPriceRuleAdded.v1": { subject: "catalog.product.ProductPriceRuleAdded.v1", topic: "catalog.product.ProductPriceRuleAdded.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "catalog.product.ProductMasterDataUpdated.v1": { subject: "catalog.product.ProductMasterDataUpdated.v1", topic: "catalog.product.ProductMasterDataUpdated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "custody.passport.CustodyInitialized.v1": { subject: "custody.passport.CustodyInitialized.v1", topic: "custody.passport.CustodyInitialized.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "custody.passport.CustodyTransferred.v1": { subject: "custody.passport.CustodyTransferred.v1", topic: "custody.passport.CustodyTransferred.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "custody.passport.CustodySplit.v1": { subject: "custody.passport.CustodySplit.v1", topic: "custody.passport.CustodySplit.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "custody.passport.CustodyMerged.v1": { subject: "custody.passport.CustodyMerged.v1", topic: "custody.passport.CustodyMerged.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "custody.passport.ProductRecalled.v1": { subject: "custody.passport.ProductRecalled.v1", topic: "custody.passport.ProductRecalled.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "custody.passport.CustodialSigned.v1": { subject: "custody.passport.CustodialSigned.v1", topic: "custody.passport.CustodialSigned.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2c.order.OrderPlaced.v1": { subject: "b2c.order.OrderPlaced.v1", topic: "b2c.order.OrderPlaced.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2c.order.PaymentConfirmed.v1": { subject: "b2c.order.PaymentConfirmed.v1", topic: "b2c.order.PaymentConfirmed.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2c.order.OrderProcessingStarted.v1": { subject: "b2c.order.OrderProcessingStarted.v1", topic: "b2c.order.OrderProcessingStarted.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2c.order.OrderShipped.v1": { subject: "b2c.order.OrderShipped.v1", topic: "b2c.order.OrderShipped.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2c.order.OrderDelivered.v1": { subject: "b2c.order.OrderDelivered.v1", topic: "b2c.order.OrderDelivered.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2c.order.OrderCancelled.v1": { subject: "b2c.order.OrderCancelled.v1", topic: "b2c.order.OrderCancelled.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2c.order.OrderRefunded.v1": { subject: "b2c.order.OrderRefunded.v1", topic: "b2c.order.OrderRefunded.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2b.tradeorder.TradeOrderCreated.v1": { subject: "b2b.tradeorder.TradeOrderCreated.v1", topic: "b2b.tradeorder.TradeOrderCreated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2b.tradeorder.MarginPosted.v1": { subject: "b2b.tradeorder.MarginPosted.v1", topic: "b2b.tradeorder.MarginPosted.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2b.tradeorder.TradeActivated.v1": { subject: "b2b.tradeorder.TradeActivated.v1", topic: "b2b.tradeorder.TradeActivated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2b.tradeorder.SettlementInitiated.v1": { subject: "b2b.tradeorder.SettlementInitiated.v1", topic: "b2b.tradeorder.SettlementInitiated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2b.tradeorder.TradeSettled.v1": { subject: "b2b.tradeorder.TradeSettled.v1", topic: "b2b.tradeorder.TradeSettled.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2b.tradeorder.TradeDisputed.v1": { subject: "b2b.tradeorder.TradeDisputed.v1", topic: "b2b.tradeorder.TradeDisputed.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "b2b.tradeorder.TradeCancelled.v1": { subject: "b2b.tradeorder.TradeCancelled.v1", topic: "b2b.tradeorder.TradeCancelled.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.WalletCreated.v1": { subject: "finance.wallet.WalletCreated.v1", topic: "finance.wallet.WalletCreated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.MFSAccountRegistered.v1": { subject: "finance.wallet.MFSAccountRegistered.v1", topic: "finance.wallet.MFSAccountRegistered.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.MFSAccountVerified.v1": { subject: "finance.wallet.MFSAccountVerified.v1", topic: "finance.wallet.MFSAccountVerified.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.WalletCredited.v1": { subject: "finance.wallet.WalletCredited.v1", topic: "finance.wallet.WalletCredited.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.WalletDebited.v1": { subject: "finance.wallet.WalletDebited.v1", topic: "finance.wallet.WalletDebited.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.WalletFrozen.v1": { subject: "finance.wallet.WalletFrozen.v1", topic: "finance.wallet.WalletFrozen.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.MFSWithdrawalInitiated.v1": { subject: "finance.wallet.MFSWithdrawalInitiated.v1", topic: "finance.wallet.MFSWithdrawalInitiated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.MFSWithdrawalConfirmed.v1": { subject: "finance.wallet.MFSWithdrawalConfirmed.v1", topic: "finance.wallet.MFSWithdrawalConfirmed.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.wallet.MFSWithdrawalFailed.v1": { subject: "finance.wallet.MFSWithdrawalFailed.v1", topic: "finance.wallet.MFSWithdrawalFailed.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.escrow.EscrowCreated.v1": { subject: "finance.escrow.EscrowCreated.v1", topic: "finance.escrow.EscrowCreated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.escrow.EscrowReleased.v1": { subject: "finance.escrow.EscrowReleased.v1", topic: "finance.escrow.EscrowReleased.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.escrow.SettlementHoldReleased.v1": { subject: "finance.escrow.SettlementHoldReleased.v1", topic: "finance.escrow.SettlementHoldReleased.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "finance.escrow.EscrowReversed.v1": { subject: "finance.escrow.EscrowReversed.v1", topic: "finance.escrow.EscrowReversed.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "logistics.shipment.ShipmentCreated.v1": { subject: "logistics.shipment.ShipmentCreated.v1", topic: "logistics.shipment.ShipmentCreated.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "logistics.shipment.RiderAssigned.v1": { subject: "logistics.shipment.RiderAssigned.v1", topic: "logistics.shipment.RiderAssigned.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "logistics.shipment.PickupRecorded.v1": { subject: "logistics.shipment.PickupRecorded.v1", topic: "logistics.shipment.PickupRecorded.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "logistics.shipment.DeliveryRecorded.v1": { subject: "logistics.shipment.DeliveryRecorded.v1", topic: "logistics.shipment.DeliveryRecorded.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "logistics.shipment.ShipmentCancelled.v1": { subject: "logistics.shipment.ShipmentCancelled.v1", topic: "logistics.shipment.ShipmentCancelled.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "logistics.shipment.DeliveryFailed.v1": { subject: "logistics.shipment.DeliveryFailed.v1", topic: "logistics.shipment.DeliveryFailed.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "fraud.enforcement.FraudSignalRaised.v1": { subject: "fraud.enforcement.FraudSignalRaised.v1", topic: "fraud.enforcement.FraudSignalRaised.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "fraud.enforcement.AccountHeld.v1": { subject: "fraud.enforcement.AccountHeld.v1", topic: "fraud.enforcement.AccountHeld.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "fraud.enforcement.AccountHoldReleased.v1": { subject: "fraud.enforcement.AccountHoldReleased.v1", topic: "fraud.enforcement.AccountHoldReleased.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "government.oversight.RecallDirectiveIssued.v1": { subject: "government.oversight.RecallDirectiveIssued.v1", topic: "government.oversight.RecallDirectiveIssued.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "government.oversight.TradeFreezeDirective.v1": { subject: "government.oversight.TradeFreezeDirective.v1", topic: "government.oversight.TradeFreezeDirective.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "government.oversight.WalletFreezeDirective.v1": { subject: "government.oversight.WalletFreezeDirective.v1", topic: "government.oversight.WalletFreezeDirective.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "platform.scheduler.CoolingOffExpired.v1": { subject: "platform.scheduler.CoolingOffExpired.v1", topic: "platform.scheduler.CoolingOffExpired.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "platform.scheduler.EscrowExpired.v1": { subject: "platform.scheduler.EscrowExpired.v1", topic: "platform.scheduler.EscrowExpired.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
  "platform.scheduler.NILRollupRefresh.v1": { subject: "platform.scheduler.NILRollupRefresh.v1", topic: "platform.scheduler.NILRollupRefresh.v1", compatibility: "BACKWARD", schemaStatus: "NEEDS-INFO" },
};

export function subjectFor(topic: string): string {
  const s = SUBJECTS[topic];
  if (!s) throw new Error(`no subject for topic: ${topic}`);
  return s.subject;
}
export function getSchema(subject: string): never {
  throw new Error(`schema for ${subject} is NEEDS-INFO in frozen contracts (Phase-2 transcription)`);
}
export function isCompatible(newVersion: number, oldVersion: number): boolean {
  return newVersion >= oldVersion; // BACKWARD within a major (EF §8.4)
}
