// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

/// <summary>Event envelope/base + headers + metadata + topic binding + serializer interface.
/// Per-event PAYLOAD types are FRAMEWORK-ONLY (schema-registry subjects are NEEDS-INFO): EventEnvelope
/// is generic over the payload; concrete payloads bind on Phase-2 contract population.</summary>
public sealed record EventHeaders(string EventId, long OccurredAtMs, int ProducerContext, string PartitionKey,
                                  string? CorrelationId = null, string? TraceId = null, int SchemaVersion = 1);

public sealed record EventMetadata(string Topic, TopicMeta Meta)
{
    public static EventMetadata For(string topic) => new(topic, Topics.TopicMetaFor(topic));
}

public sealed record EventEnvelope<TPayload>(EventHeaders Headers, string Topic, TPayload Payload);

public interface IPayloadSerializer<TPayload>
{
    byte[] Serialize(TPayload payload);
    TPayload Deserialize(byte[] data);
}
