// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

using System;
using System.Collections.Generic;

/// <summary>Schema-registry metadata (schema-registry.yaml): subjects + compatibility + version helpers.
/// Per-subject JSON-Schema is NEEDS-INFO; GetSchema throws until populated.</summary>
public enum Compatibility { Backward }

public sealed record SubjectInfo(string Subject, string Topic, string Compatibility, string SchemaStatus);

public static class Schema
{
    public static readonly IReadOnlyDictionary<string, SubjectInfo> Subjects = new Dictionary<string, SubjectInfo>
    {
        ["identity.party.PartyRegistered.v1"] = new SubjectInfo("identity.party.PartyRegistered.v1", "identity.party.PartyRegistered.v1", "BACKWARD", "NEEDS-INFO"),
        ["identity.party.KYCApproved.v1"] = new SubjectInfo("identity.party.KYCApproved.v1", "identity.party.KYCApproved.v1", "BACKWARD", "NEEDS-INFO"),
        ["identity.party.KYCTierChanged.v1"] = new SubjectInfo("identity.party.KYCTierChanged.v1", "identity.party.KYCTierChanged.v1", "BACKWARD", "NEEDS-INFO"),
        ["identity.party.KYCRejected.v1"] = new SubjectInfo("identity.party.KYCRejected.v1", "identity.party.KYCRejected.v1", "BACKWARD", "NEEDS-INFO"),
        ["identity.party.PartySuspended.v1"] = new SubjectInfo("identity.party.PartySuspended.v1", "identity.party.PartySuspended.v1", "BACKWARD", "NEEDS-INFO"),
        ["identity.party.PartyReactivated.v1"] = new SubjectInfo("identity.party.PartyReactivated.v1", "identity.party.PartyReactivated.v1", "BACKWARD", "NEEDS-INFO"),
        ["catalog.product.ProductCreated.v1"] = new SubjectInfo("catalog.product.ProductCreated.v1", "catalog.product.ProductCreated.v1", "BACKWARD", "NEEDS-INFO"),
        ["catalog.product.ProductPublished.v1"] = new SubjectInfo("catalog.product.ProductPublished.v1", "catalog.product.ProductPublished.v1", "BACKWARD", "NEEDS-INFO"),
        ["catalog.product.ProductDeprecated.v1"] = new SubjectInfo("catalog.product.ProductDeprecated.v1", "catalog.product.ProductDeprecated.v1", "BACKWARD", "NEEDS-INFO"),
        ["catalog.product.ProductPriceRuleAdded.v1"] = new SubjectInfo("catalog.product.ProductPriceRuleAdded.v1", "catalog.product.ProductPriceRuleAdded.v1", "BACKWARD", "NEEDS-INFO"),
        ["catalog.product.ProductMasterDataUpdated.v1"] = new SubjectInfo("catalog.product.ProductMasterDataUpdated.v1", "catalog.product.ProductMasterDataUpdated.v1", "BACKWARD", "NEEDS-INFO"),
        ["custody.passport.CustodyInitialized.v1"] = new SubjectInfo("custody.passport.CustodyInitialized.v1", "custody.passport.CustodyInitialized.v1", "BACKWARD", "NEEDS-INFO"),
        ["custody.passport.CustodyTransferred.v1"] = new SubjectInfo("custody.passport.CustodyTransferred.v1", "custody.passport.CustodyTransferred.v1", "BACKWARD", "NEEDS-INFO"),
        ["custody.passport.CustodySplit.v1"] = new SubjectInfo("custody.passport.CustodySplit.v1", "custody.passport.CustodySplit.v1", "BACKWARD", "NEEDS-INFO"),
        ["custody.passport.CustodyMerged.v1"] = new SubjectInfo("custody.passport.CustodyMerged.v1", "custody.passport.CustodyMerged.v1", "BACKWARD", "NEEDS-INFO"),
        ["custody.passport.ProductRecalled.v1"] = new SubjectInfo("custody.passport.ProductRecalled.v1", "custody.passport.ProductRecalled.v1", "BACKWARD", "NEEDS-INFO"),
        ["custody.passport.CustodialSigned.v1"] = new SubjectInfo("custody.passport.CustodialSigned.v1", "custody.passport.CustodialSigned.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2c.order.OrderPlaced.v1"] = new SubjectInfo("b2c.order.OrderPlaced.v1", "b2c.order.OrderPlaced.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2c.order.PaymentConfirmed.v1"] = new SubjectInfo("b2c.order.PaymentConfirmed.v1", "b2c.order.PaymentConfirmed.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2c.order.OrderProcessingStarted.v1"] = new SubjectInfo("b2c.order.OrderProcessingStarted.v1", "b2c.order.OrderProcessingStarted.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2c.order.OrderShipped.v1"] = new SubjectInfo("b2c.order.OrderShipped.v1", "b2c.order.OrderShipped.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2c.order.OrderDelivered.v1"] = new SubjectInfo("b2c.order.OrderDelivered.v1", "b2c.order.OrderDelivered.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2c.order.OrderCancelled.v1"] = new SubjectInfo("b2c.order.OrderCancelled.v1", "b2c.order.OrderCancelled.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2c.order.OrderRefunded.v1"] = new SubjectInfo("b2c.order.OrderRefunded.v1", "b2c.order.OrderRefunded.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2b.tradeorder.TradeOrderCreated.v1"] = new SubjectInfo("b2b.tradeorder.TradeOrderCreated.v1", "b2b.tradeorder.TradeOrderCreated.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2b.tradeorder.MarginPosted.v1"] = new SubjectInfo("b2b.tradeorder.MarginPosted.v1", "b2b.tradeorder.MarginPosted.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2b.tradeorder.TradeActivated.v1"] = new SubjectInfo("b2b.tradeorder.TradeActivated.v1", "b2b.tradeorder.TradeActivated.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2b.tradeorder.SettlementInitiated.v1"] = new SubjectInfo("b2b.tradeorder.SettlementInitiated.v1", "b2b.tradeorder.SettlementInitiated.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2b.tradeorder.TradeSettled.v1"] = new SubjectInfo("b2b.tradeorder.TradeSettled.v1", "b2b.tradeorder.TradeSettled.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2b.tradeorder.TradeDisputed.v1"] = new SubjectInfo("b2b.tradeorder.TradeDisputed.v1", "b2b.tradeorder.TradeDisputed.v1", "BACKWARD", "NEEDS-INFO"),
        ["b2b.tradeorder.TradeCancelled.v1"] = new SubjectInfo("b2b.tradeorder.TradeCancelled.v1", "b2b.tradeorder.TradeCancelled.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.WalletCreated.v1"] = new SubjectInfo("finance.wallet.WalletCreated.v1", "finance.wallet.WalletCreated.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.MFSAccountRegistered.v1"] = new SubjectInfo("finance.wallet.MFSAccountRegistered.v1", "finance.wallet.MFSAccountRegistered.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.MFSAccountVerified.v1"] = new SubjectInfo("finance.wallet.MFSAccountVerified.v1", "finance.wallet.MFSAccountVerified.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.WalletCredited.v1"] = new SubjectInfo("finance.wallet.WalletCredited.v1", "finance.wallet.WalletCredited.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.WalletDebited.v1"] = new SubjectInfo("finance.wallet.WalletDebited.v1", "finance.wallet.WalletDebited.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.WalletFrozen.v1"] = new SubjectInfo("finance.wallet.WalletFrozen.v1", "finance.wallet.WalletFrozen.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.MFSWithdrawalInitiated.v1"] = new SubjectInfo("finance.wallet.MFSWithdrawalInitiated.v1", "finance.wallet.MFSWithdrawalInitiated.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.MFSWithdrawalConfirmed.v1"] = new SubjectInfo("finance.wallet.MFSWithdrawalConfirmed.v1", "finance.wallet.MFSWithdrawalConfirmed.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.wallet.MFSWithdrawalFailed.v1"] = new SubjectInfo("finance.wallet.MFSWithdrawalFailed.v1", "finance.wallet.MFSWithdrawalFailed.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.escrow.EscrowCreated.v1"] = new SubjectInfo("finance.escrow.EscrowCreated.v1", "finance.escrow.EscrowCreated.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.escrow.EscrowReleased.v1"] = new SubjectInfo("finance.escrow.EscrowReleased.v1", "finance.escrow.EscrowReleased.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.escrow.SettlementHoldReleased.v1"] = new SubjectInfo("finance.escrow.SettlementHoldReleased.v1", "finance.escrow.SettlementHoldReleased.v1", "BACKWARD", "NEEDS-INFO"),
        ["finance.escrow.EscrowReversed.v1"] = new SubjectInfo("finance.escrow.EscrowReversed.v1", "finance.escrow.EscrowReversed.v1", "BACKWARD", "NEEDS-INFO"),
        ["logistics.shipment.ShipmentCreated.v1"] = new SubjectInfo("logistics.shipment.ShipmentCreated.v1", "logistics.shipment.ShipmentCreated.v1", "BACKWARD", "NEEDS-INFO"),
        ["logistics.shipment.RiderAssigned.v1"] = new SubjectInfo("logistics.shipment.RiderAssigned.v1", "logistics.shipment.RiderAssigned.v1", "BACKWARD", "NEEDS-INFO"),
        ["logistics.shipment.PickupRecorded.v1"] = new SubjectInfo("logistics.shipment.PickupRecorded.v1", "logistics.shipment.PickupRecorded.v1", "BACKWARD", "NEEDS-INFO"),
        ["logistics.shipment.DeliveryRecorded.v1"] = new SubjectInfo("logistics.shipment.DeliveryRecorded.v1", "logistics.shipment.DeliveryRecorded.v1", "BACKWARD", "NEEDS-INFO"),
        ["logistics.shipment.ShipmentCancelled.v1"] = new SubjectInfo("logistics.shipment.ShipmentCancelled.v1", "logistics.shipment.ShipmentCancelled.v1", "BACKWARD", "NEEDS-INFO"),
        ["logistics.shipment.DeliveryFailed.v1"] = new SubjectInfo("logistics.shipment.DeliveryFailed.v1", "logistics.shipment.DeliveryFailed.v1", "BACKWARD", "NEEDS-INFO"),
        ["fraud.enforcement.FraudSignalRaised.v1"] = new SubjectInfo("fraud.enforcement.FraudSignalRaised.v1", "fraud.enforcement.FraudSignalRaised.v1", "BACKWARD", "NEEDS-INFO"),
        ["fraud.enforcement.AccountHeld.v1"] = new SubjectInfo("fraud.enforcement.AccountHeld.v1", "fraud.enforcement.AccountHeld.v1", "BACKWARD", "NEEDS-INFO"),
        ["fraud.enforcement.AccountHoldReleased.v1"] = new SubjectInfo("fraud.enforcement.AccountHoldReleased.v1", "fraud.enforcement.AccountHoldReleased.v1", "BACKWARD", "NEEDS-INFO"),
        ["government.oversight.RecallDirectiveIssued.v1"] = new SubjectInfo("government.oversight.RecallDirectiveIssued.v1", "government.oversight.RecallDirectiveIssued.v1", "BACKWARD", "NEEDS-INFO"),
        ["government.oversight.TradeFreezeDirective.v1"] = new SubjectInfo("government.oversight.TradeFreezeDirective.v1", "government.oversight.TradeFreezeDirective.v1", "BACKWARD", "NEEDS-INFO"),
        ["government.oversight.WalletFreezeDirective.v1"] = new SubjectInfo("government.oversight.WalletFreezeDirective.v1", "government.oversight.WalletFreezeDirective.v1", "BACKWARD", "NEEDS-INFO"),
        ["platform.scheduler.CoolingOffExpired.v1"] = new SubjectInfo("platform.scheduler.CoolingOffExpired.v1", "platform.scheduler.CoolingOffExpired.v1", "BACKWARD", "NEEDS-INFO"),
        ["platform.scheduler.EscrowExpired.v1"] = new SubjectInfo("platform.scheduler.EscrowExpired.v1", "platform.scheduler.EscrowExpired.v1", "BACKWARD", "NEEDS-INFO"),
        ["platform.scheduler.NILRollupRefresh.v1"] = new SubjectInfo("platform.scheduler.NILRollupRefresh.v1", "platform.scheduler.NILRollupRefresh.v1", "BACKWARD", "NEEDS-INFO"),
    };

    public static string SubjectFor(string topic) =>
        Subjects.TryGetValue(topic, out var s) ? s.Subject : throw new ArgumentException($"no subject for topic: {topic}");
    public static void GetSchema(string subject) =>
        throw new NotSupportedException($"schema for {subject} is NEEDS-INFO in frozen contracts (Phase-2 transcription)");
    public static bool IsCompatible(int newVersion, int oldVersion) => newVersion >= oldVersion;
}
