"""Emitter snapshot/regression tests — generate to a temp dir and assert contract-faithful output."""
import os
import sys
import importlib
import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.dirname(HERE)
sys.path.insert(0, GEN)
CONTRACTS = os.path.join(os.path.dirname(GEN), "contracts")

from dkdgen import load                       # noqa: E402
from dkdgen.version import build_metadata      # noqa: E402
from dkdgen.emitters import EMITTERS           # noqa: E402
# SDK-structure tests apply to the five LANGUAGE emitters; openapi emits an API doc, not an SDK.
SDK_LANGS = [l for l in sorted(EMITTERS.keys()) if l != "openapi"]


@pytest.fixture(scope="module")
def c():
    return load(CONTRACTS)


@pytest.fixture(scope="module")
def meta(c):
    return build_metadata(c.spine_version, build_time="2026-06-29T00:00:00Z")


def _emit(lang, c, meta, tmp):
    out = os.path.join(str(tmp), lang)
    files = EMITTERS[lang].emit(c, meta, out)
    return out, files


@pytest.mark.parametrize("lang", SDK_LANGS)
def test_emitter_runs_and_writes_files(lang, c, meta, tmp_path):
    out, files = _emit(lang, c, meta, tmp_path)
    assert len(files) >= 12, "%s emitted too few files: %d" % (lang, len(files))
    for rel in files:
        assert os.path.isfile(os.path.join(out, rel))


@pytest.mark.parametrize("lang", SDK_LANGS)
def test_provenance_banner_present(lang, c, meta, tmp_path):
    out, files = _emit(lang, c, meta, tmp_path)
    src_files = [f for f in files if not f.endswith((".toml", ".json", ".mod", ".xml", "go.mod"))]
    hits = 0
    for rel in src_files:
        txt = open(os.path.join(out, rel), encoding="utf-8").read()
        if "generated by dkdgen" in txt and "dkd-contracts-spine@1.0.0" in txt:
            hits += 1
    assert hits >= 1, "%s: no provenance banner found" % lang


@pytest.mark.parametrize("lang", SDK_LANGS)
def test_all_59_topics_present_in_output(lang, c, meta, tmp_path):
    out, files = _emit(lang, c, meta, tmp_path)
    blob = "".join(open(os.path.join(out, f), encoding="utf-8").read() for f in files)
    missing = [t.name for t in c.topics if t.name not in blob]
    assert not missing, "%s missing topics: %s" % (lang, missing[:3])


@pytest.mark.parametrize("lang", sorted(EMITTERS.keys()))
def test_no_fabrication_markers(lang, c, meta, tmp_path):
    """Generated code must not contain forbidden placeholders."""
    out, files = _emit(lang, c, meta, tmp_path)
    for rel in files:
        txt = open(os.path.join(out, rel), encoding="utf-8").read()
        for bad in ("TODO", "FIXME", "PLACEHOLDER", "pseudo-code"):
            assert bad not in txt, "%s/%s contains forbidden %s" % (lang, rel, bad)


@pytest.mark.parametrize("lang", SDK_LANGS)
def test_all_11_identifiers_present(lang, c, meta, tmp_path):
    out, files = _emit(lang, c, meta, tmp_path)
    blob = "".join(open(os.path.join(out, f), encoding="utf-8").read() for f in files)
    for ident in c.identifiers:
        assert ident.prefix in blob, "%s missing prefix %s" % (lang, ident.prefix)
