// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

import "testing"

func TestProvenance(t *testing.T) {
	if ContractVersion != "1.0.0" {
		t.Fatalf("contract version = %s", ContractVersion)
	}
}

func TestIDsTypedAndValidated(t *testing.T) {
	d, err := NewDID("did:dokandar:abc")
	if err != nil || d.String() != "did:dokandar:abc" {
		t.Fatalf("DID: %v", err)
	}
	if !DIDImmutable || DIDOwnerContext != 1 {
		t.Fatal("DID metadata")
	}
	if _, err := NewPPID("did:dokandar:x"); err == nil {
		t.Fatal("PPID should reject wrong prefix")
	}
}

func TestTopics(t *testing.T) {
	if len(TopicMetaByName) != 59 {
		t.Fatalf("topics = %d", len(TopicMetaByName))
	}
	m, ok := TopicMetaFor("custody.passport.CustodyInitialized.v1")
	if !ok || m.Producer != 3 || m.Key != "PPID" {
		t.Fatal("custody topic meta")
	}
}

func TestErrorCode(t *testing.T) {
	code, err := ErrorCode("finance", "idempotency", "duplicate_key")
	if err != nil || code != "dokandar.finance.idempotency.duplicate_key" {
		t.Fatalf("error code: %v %s", err, code)
	}
	if _, err := ErrorCode("frobnicate", "x", "y"); err == nil {
		t.Fatal("should reject unknown context")
	}
}
