// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

// Event envelope/base + headers + metadata + topic binding + serializer interface.
// Per-event PAYLOAD types are FRAMEWORK-ONLY (schema-registry subjects are NEEDS-INFO): EventEnvelope
// is generic over the payload; concrete payloads bind on Phase-2 contract population.
type EventHeaders struct {
	EventID         string // inbox dedup key
	OccurredAtMs    int64
	ProducerContext int
	PartitionKey    string // per-aggregate ordering key
	CorrelationID   string
	TraceID         string
	SchemaVersion   int
}

type EventMetadata struct {
	Topic string
	Meta  TopicMeta
}

func EventMetadataFor(topic string) (EventMetadata, bool) {
	m, ok := TopicMetaFor(topic)
	return EventMetadata{Topic: topic, Meta: m}, ok
}

type EventEnvelope[P any] struct {
	Headers EventHeaders
	Topic   string
	Payload P
}

type PayloadSerializer[P any] interface {
	Serialize(payload P) ([]byte, error)
	Deserialize(data []byte) (P, error)
}
