// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

// Money is int64 poisha (DM type conventions). Float/decimal money is impossible by type.
const PoishaPerBDT int64 = 100

type Money struct{ Poisha int64 }

func MoneyOfBDT(bdt int64) Money { return Money{Poisha: bdt * PoishaPerBDT} }

// Timestamp is Unix milliseconds, UTC (int64).
type Timestamp struct{ EpochMs int64 }
