// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

import type { IncomingMessage, ServerResponse } from "node:http";

// Content-Security-Policy for the Swagger UI paths (allows the UI assets it loads).
export const DOCS_CSP =
  "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; " +
  "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: https://cdn.jsdelivr.net; " +
  "font-src 'self' https://cdn.jsdelivr.net; connect-src 'self'";

export function isDocsPath(path: string): boolean {
  return path.startsWith("/docs") || path.startsWith("/swagger");
}

const SWAGGER_UI_HTML = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>API Documentation</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui.css"></head>
<body><div id="swagger-ui"></div>
<script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui-bundle.js"></script>
<script>window.ui = SwaggerUIBundle({ url: "/swagger/v1/swagger.json", dom_id: "#swagger-ui" });</script>
</body></html>`;

function openapiSpec(title: string): string {
  return JSON.stringify({
    openapi: "3.0.3",
    info: { title, version: "v1", description: title + " REST API." },
    paths: {
      "/health": { get: { tags: ["HealthEndpoints"], operationId: "getHealth", summary: "Health probe", responses: { "200": { description: "OK", content: { "application/json": { schema: { $ref: "#/components/schemas/Envelope" } } } } } } },
      "/live": { get: { tags: ["HealthEndpoints"], operationId: "getLive", summary: "Liveness probe", responses: { "200": { description: "OK" } } } },
      "/ready": { get: { tags: ["HealthEndpoints"], operationId: "getReady", summary: "Readiness probe", responses: { "200": { description: "OK" }, "503": { description: "Not ready", content: { "application/problem+json": { schema: { $ref: "#/components/schemas/ProblemDetails" } } } } } } },
      "/version": { get: { tags: ["HealthEndpoints"], operationId: "getVersion", summary: "Version", responses: { "200": { description: "OK", content: { "application/json": { schema: { $ref: "#/components/schemas/Envelope" } } } } } } },
    },
    components: {
      schemas: {
        Envelope: { type: "object", properties: { success: { type: "boolean" }, data: { type: "object", nullable: true }, error: { $ref: "#/components/schemas/ProblemDetails" }, meta: { type: "object", nullable: true } } },
        ProblemDetails: { type: "object", description: "RFC-7807 problem+json", properties: { type: { type: "string" }, title: { type: "string" }, status: { type: "integer" }, detail: { type: "string" }, instance: { type: "string" }, code: { type: "string" } } },
      },
      securitySchemes: { Bearer: { type: "http", scheme: "bearer", bearerFormat: "JWT", description: "JWT bearer token (injected by the API gateway in production)." } },
    },
  });
}

// handleDocs serves /docs and /swagger/v1/swagger.json; returns true when it handled the request.
export function handleDocs(req: IncomingMessage, res: ServerResponse, title: string): boolean {
  const url = req.url ?? "";
  if (url === "/docs") {
    res.statusCode = 200;
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.end(SWAGGER_UI_HTML);
    return true;
  }
  if (url === "/swagger/v1/swagger.json") {
    res.statusCode = 200;
    res.setHeader("Content-Type", "application/json");
    res.end(openapiSpec(title));
    return true;
  }
  return false;
}
