"""
dkdgen.emitters.base — shared emission infrastructure used by every language emitter.

Provides a Writer (file emission with provenance banner) and naming helpers so all four SDKs
derive identical names from the same IR symbols.
"""
from __future__ import annotations
import os
import re


class Writer:
    def __init__(self, out_dir: str, comment: str, meta: dict):
        self.out_dir = out_dir
        self.comment = comment
        self.meta = meta
        self.written: list[str] = []

    def banner(self) -> str:
        m = self.meta
        c = self.comment
        return "\n".join([
            "%s DO NOT EDIT — generated by %s v%s from dkd-contracts-spine@%s" % (
                c, m["generator"], m["generator_version"], m["contract_version"]),
            "%s The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`." % c,
            "%s build_time=%s build_commit=%s" % (c, m["build_time"], m["build_commit"]),
        ])

    def write(self, rel_path: str, body: str, with_banner: bool = True) -> None:
        full = os.path.join(self.out_dir, rel_path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        content = (self.banner() + "\n\n" + body) if with_banner else body
        if not content.endswith("\n"):
            content += "\n"
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)
        self.written.append(rel_path)


# ---- naming helpers (single source so all SDKs agree on derived names) ----
def _words(s: str) -> list[str]:
    s = s.replace("-", "_").replace(".", "_")
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", s)
    return [w for w in s.split("_") if w]


def pascal(s: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in _words(s))


def camel(s: str) -> str:
    p = pascal(s)
    return p[:1].lower() + p[1:] if p else p


def snake(s: str) -> str:
    return "_".join(w.lower() for w in _words(s))


def screaming(s: str) -> str:
    return "_".join(w.upper() for w in _words(s))


def const_name(s: str) -> str:
    """Topic/queue constant name, e.g. identity.party.PartyRegistered.v1 -> IDENTITY_PARTY_PARTY_REGISTERED_V1"""
    return screaming(s)
