// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

namespace IdentitySvc.Config;

/// <summary>
/// 12-factor configuration: every value is loaded from environment variables.
/// Secrets are delivered by the platform secret manager in non-local environments — never committed.
/// </summary>
public sealed class ServiceConfig
{
    public string ServiceName  { get; init; } = string.Empty;
    public string Context      { get; init; } = string.Empty;
    public string DkdEnv       { get; init; } = "local";
    public int    HttpPort     { get; init; } = 8080;
    public int    GrpcPort     { get; init; } = 8081;
    public string LogLevel     { get; init; } = "info";
    public string KafkaBrokers { get; init; } = string.Empty;
    public string RabbitUrl    { get; init; } = string.Empty;
    public string DbDsn        { get; init; } = string.Empty;
    public string OtelEndpoint { get; init; } = string.Empty;
    public string JwtIssuer    { get; init; } = string.Empty;

    /// <summary>Load all values from environment variables (12-factor).</summary>
    public static ServiceConfig Load() => new()
    {
        ServiceName  = GetEnv("DKD_SERVICE_NAME",  "identity-svc"),
        Context      = GetEnv("DKD_CONTEXT",        "identity"),
        DkdEnv       = GetEnv("DKD_ENV",             "local"),
        HttpPort     = int.Parse(GetEnv("DKD_HTTP_PORT", "8080")),
        GrpcPort     = int.Parse(GetEnv("DKD_GRPC_PORT", "8081")),
        LogLevel     = GetEnv("DKD_LOG_LEVEL",      "info"),
        KafkaBrokers = GetEnv("DKD_KAFKA_BROKERS",  "localhost:9092"),
        RabbitUrl    = GetEnv("DKD_RABBITMQ_URL",   string.Empty),
        DbDsn        = GetEnv("DKD_DB_DSN",         string.Empty),
        OtelEndpoint = GetEnv("DKD_OTEL_ENDPOINT",  string.Empty),
        JwtIssuer    = GetEnv("DKD_JWT_ISSUER",     string.Empty),
    };

    /// <summary>Startup validation — throws <see cref="InvalidOperationException"/> on missing required values.</summary>
    public void Validate()
    {
        if (string.IsNullOrWhiteSpace(ServiceName))
            throw new InvalidOperationException("DKD_SERVICE_NAME is required");
        if (string.IsNullOrWhiteSpace(Context))
            throw new InvalidOperationException("DKD_CONTEXT is required");
        if (HttpPort is <= 0 or > 65535)
            throw new InvalidOperationException($"DKD_HTTP_PORT is invalid: {HttpPort}");
    }

    private static string GetEnv(string key, string fallback) =>
        Environment.GetEnvironmentVariable(key) is { Length: > 0 } v ? v : fallback;
}
