output "cluster_name" {
  value = module.eks.cluster_name
}

output "update_kubeconfig" {
  value = "aws eks update-kubeconfig --name ${module.eks.cluster_name} --region ${var.region}"
}

output "jump_server_private_ip" {
  description = "SSH over the VPN: see jump_ssh_command."
  value       = aws_instance.jump.private_ip
}

output "jump_ssh_command" {
  value = "ssh -i ${abspath("${path.module}/../keys/${local.name}-jump-server.pem")} ubuntu@${aws_instance.jump.private_ip}  # VPN must be connected"
}

output "argocd_url_hint" {
  value = "http://<worker-node-private-ip>:30080  — run ../argocd-info.sh for the exact IP (VPN required)"
}

output "lb_controller_role_arn" {
  value = module.lb_controller_irsa.iam_role_arn
}

resource "local_file" "eks_vars" {
  filename        = "${path.module}/../ansible/eks-vars.yml"
  file_permission = "0644"
  content         = <<-EOT
    # AUTO-GENERATED by Terraform. Do not edit by hand.
    cluster_name: ${module.eks.cluster_name}
    region: ${var.region}
    lb_controller_role_arn: ${module.lb_controller_irsa.iam_role_arn}
    vpc_id: ${local.vpc_id}
    jump_server_ip: ${aws_instance.jump.private_ip}
  EOT
}

# Ansible inventory — the jump server is the ONLY target. You still launch
# `ansible-playbook` from your laptop (VPN connected), but every task runs on the
# jump server over SSH. Gitignored (ansible/inventory.ini).
resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"
  content         = <<-EOT
    # AUTO-GENERATED by Terraform. Do not edit by hand. Connect the VPN first.
    [jump]
    jump-server ansible_host=${aws_instance.jump.private_ip}

    [jump:vars]
    ansible_user=ubuntu
    ansible_ssh_private_key_file=${abspath("${path.module}/../keys/${local.name}-jump-server.pem")}
    ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null
  EOT
}
