// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

namespace IdentitySvc.Observability;

/// <summary>
/// Shared structured-log field name constants. Use these throughout the service to keep field
/// names consistent across log entries. Logging itself uses ILogger{T} injected via DI.
/// </summary>
public static class AppLogger
{
    public static class Keys
    {
        public const string CorrelationId = "correlation_id";
        public const string TraceParent   = "traceparent";
        public const string ServiceName   = "service_name";
        public const string DkdContext    = "dkd_context";
    }
}
