// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using System.Text;
using Microsoft.AspNetCore.Http;

namespace IdentitySvc.Observability;

/// <summary>
/// Thread-safe Prometheus-text counter registry. Exposed on :9090/metrics.
/// For richer metric types (histograms, gauges) replace with the prometheus-net NuGet package
/// at the integration point — the /metrics handler in Program.cs remains unchanged.
/// </summary>
public sealed class AppMetrics
{
    private readonly Dictionary<string, long> _counters = new();
    private readonly object _lock = new();

    /// <summary>Atomically increment a counter by name.</summary>
    public void Increment(string name)
    {
        lock (_lock)
            _counters[name] = _counters.TryGetValue(name, out var v) ? v + 1 : 1;
    }

    /// <summary>Write all counters in Prometheus text exposition format (version 0.0.4).</summary>
    public async Task WritePrometheusTextAsync(HttpResponse response)
    {
        response.ContentType = "text/plain; version=0.0.4; charset=utf-8";
        string body;
        lock (_lock)
        {
            var sb = new StringBuilder();
            foreach (var (name, value) in _counters)
                sb.Append(name).Append(' ').AppendLine(value.ToString());
            body = sb.ToString();
        }
        await response.WriteAsync(body);
    }
}
