// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using System.Security.Cryptography;

namespace IdentitySvc.Observability;

/// <summary>
/// W3C traceparent generation and correlation ID utilities. The OpenTelemetry SDK (OTLP exporter)
/// is the integration point for span export to the platform collector; propagation is independent.
/// </summary>
public static class Tracing
{
    /// <summary>
    /// Generates a W3C traceparent string (version=00, random trace-id + span-id, sampled flag=01).
    /// </summary>
    public static string NewTraceParent()
    {
        Span<byte> traceId = stackalloc byte[16];
        Span<byte> spanId  = stackalloc byte[8];
        RandomNumberGenerator.Fill(traceId);
        RandomNumberGenerator.Fill(spanId);
        return $"00-{Convert.ToHexString(traceId).ToLowerInvariant()}-{Convert.ToHexString(spanId).ToLowerInvariant()}-01";
    }

    /// <summary>Generates a new correlation ID (random hex, 32 chars).</summary>
    public static string NewCorrelationId()
    {
        Span<byte> buf = stackalloc byte[16];
        RandomNumberGenerator.Fill(buf);
        return Convert.ToHexString(buf).ToLowerInvariant();
    }
}
