// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Http;

namespace IdentitySvc.Security;

/// <summary>Minimal claim set issued by the Dokandar platform (see dkd-platform-libs JwtClaims).</summary>
public sealed record DkdClaims(
    [property: JsonPropertyName("sub")]      string   Sub,
    [property: JsonPropertyName("kyc_tier")] string   KycTier,
    [property: JsonPropertyName("roles")]    string[] Roles,
    [property: JsonPropertyName("cid")]      string   Cid);

/// <summary>
/// JWT signature verifier — integration point for the platform JWKS endpoint.
/// Throw <see cref="UnauthorizedAccessException"/> when the token signature is invalid.
/// </summary>
public interface IJwtVerifier
{
    void Verify(string token);
}

/// <summary>
/// No-op verifier: accepts all tokens without signature verification.
/// Safe for local development only. Replace with the Dkd.Platform JWKS verifier in all
/// non-local environments.
/// </summary>
public sealed class NoopJwtVerifier : IJwtVerifier
{
    public void Verify(string token) { }
}

/// <summary>
/// Authenticates bearer JWTs: base64url-decodes the payload, deserialises
/// <see cref="DkdClaims"/>, then delegates signature verification to the injected
/// <see cref="IJwtVerifier"/>. Returns null (never throws) when authentication fails.
/// </summary>
public sealed class JwtAuthenticator(IJwtVerifier verifier)
{
    private static readonly JsonSerializerOptions _jsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    /// <summary>Returns parsed claims on success; null on any structural or verification failure.</summary>
    public DkdClaims? TryAuthenticate(string token)
    {
        try
        {
            verifier.Verify(token);
            var parts = token.Split('.');
            if (parts.Length != 3) return null;
            var json = DecodeSegment(parts[1]);
            return JsonSerializer.Deserialize<DkdClaims>(json, _jsonOpts);
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// RBAC authorization helper: returns true when the claims contain the given role (case-insensitive).
    /// Pair with the platform PDP for ABAC enforcement.
    /// </summary>
    public static bool HasRole(DkdClaims? claims, string role) =>
        claims?.Roles.Contains(role, StringComparer.OrdinalIgnoreCase) == true;

    /// <summary>Retrieves claims attached by <see cref="JwtAuthMiddleware"/> from the current request context.</summary>
    public static DkdClaims? GetClaims(HttpContext ctx) =>
        ctx.Items.TryGetValue(nameof(DkdClaims), out var v) ? v as DkdClaims : null;

    private static string DecodeSegment(string segment)
    {
        var padded = (segment.Length % 4) switch
        {
            2 => segment + "==",
            3 => segment + "=",
            _ => segment,
        };
        var bytes = Convert.FromBase64String(padded.Replace('-', '+').Replace('_', '/'));
        return Encoding.UTF8.GetString(bytes);
    }
}
