// catalog-product-ohs (R7 master-data OHS). The Product read-model resolver over gRPC — the internal
// plane other contexts use to resolve a GPID to its canonical product (never a local fork of GPID).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/catalog_product_ohs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogProductOhs_ResolveProduct_FullMethodName = "/dokandar.catalog.ohs.v1.CatalogProductOhs/ResolveProduct"
)

// CatalogProductOhsClient is the client API for CatalogProductOhs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogProductOhsClient interface {
	// Resolve the canonical product read-model for a GPID.
	ResolveProduct(ctx context.Context, in *ResolveProductRequest, opts ...grpc.CallOption) (*ProductReply, error)
}

type catalogProductOhsClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogProductOhsClient(cc grpc.ClientConnInterface) CatalogProductOhsClient {
	return &catalogProductOhsClient{cc}
}

func (c *catalogProductOhsClient) ResolveProduct(ctx context.Context, in *ResolveProductRequest, opts ...grpc.CallOption) (*ProductReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductReply)
	err := c.cc.Invoke(ctx, CatalogProductOhs_ResolveProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogProductOhsServer is the server API for CatalogProductOhs service.
// All implementations must embed UnimplementedCatalogProductOhsServer
// for forward compatibility.
type CatalogProductOhsServer interface {
	// Resolve the canonical product read-model for a GPID.
	ResolveProduct(context.Context, *ResolveProductRequest) (*ProductReply, error)
	mustEmbedUnimplementedCatalogProductOhsServer()
}

// UnimplementedCatalogProductOhsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogProductOhsServer struct{}

func (UnimplementedCatalogProductOhsServer) ResolveProduct(context.Context, *ResolveProductRequest) (*ProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveProduct not implemented")
}
func (UnimplementedCatalogProductOhsServer) mustEmbedUnimplementedCatalogProductOhsServer() {}
func (UnimplementedCatalogProductOhsServer) testEmbeddedByValue()                           {}

// UnsafeCatalogProductOhsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogProductOhsServer will
// result in compilation errors.
type UnsafeCatalogProductOhsServer interface {
	mustEmbedUnimplementedCatalogProductOhsServer()
}

func RegisterCatalogProductOhsServer(s grpc.ServiceRegistrar, srv CatalogProductOhsServer) {
	// If the following call pancis, it indicates UnimplementedCatalogProductOhsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogProductOhs_ServiceDesc, srv)
}

func _CatalogProductOhs_ResolveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogProductOhsServer).ResolveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogProductOhs_ResolveProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogProductOhsServer).ResolveProduct(ctx, req.(*ResolveProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogProductOhs_ServiceDesc is the grpc.ServiceDesc for CatalogProductOhs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogProductOhs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dokandar.catalog.ohs.v1.CatalogProductOhs",
	HandlerType: (*CatalogProductOhsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveProduct",
			Handler:    _CatalogProductOhs_ResolveProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog_product_ohs.proto",
}
