// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

import (
	"fmt"
	"regexp"
)

// Error taxonomy (error-codes.yaml): dokandar.<context>.<category>.<reason> (RFC-7807).
// Concrete codes are NEEDS-INFO in frozen contracts; this provides the builder + slug type
// + ProblemDetails + typed errors — never a fabricated code list.

type ContextSlug string

const (
	ContextSlugIdentity ContextSlug = "identity"
	ContextSlugCatalog ContextSlug = "catalog"
	ContextSlugCustody ContextSlug = "custody"
	ContextSlugProvenance ContextSlug = "provenance"
	ContextSlugInventory ContextSlug = "inventory"
	ContextSlugB2c ContextSlug = "b2c"
	ContextSlugB2b ContextSlug = "b2b"
	ContextSlugFinance ContextSlug = "finance"
	ContextSlugLogistics ContextSlug = "logistics"
	ContextSlugFraud ContextSlug = "fraud"
	ContextSlugGovernment ContextSlug = "government"
	ContextSlugAnalytics ContextSlug = "analytics"
	ContextSlugPlatform ContextSlug = "platform"
	ContextSlugEdge ContextSlug = "edge"
)

var contextSlugs = map[string]bool{
	"identity": true,
	"catalog": true,
	"custody": true,
	"provenance": true,
	"inventory": true,
	"b2c": true,
	"b2b": true,
	"finance": true,
	"logistics": true,
	"fraud": true,
	"government": true,
	"analytics": true,
	"platform": true,
	"edge": true,
}

var codeRe = regexp.MustCompile(`^dokandar\.([a-z]+)\.([a-z0-9_]+)\.([a-z0-9_]+)$`)

func ErrorCode(context, category, reason string) (string, error) {
	code := fmt.Sprintf("dokandar.%s.%s.%s", context, category, reason)
	if !contextSlugs[context] {
		return "", fmt.Errorf("unknown context slug: %s", context)
	}
	if !codeRe.MatchString(code) {
		return "", fmt.Errorf("error code violates taxonomy: %s", code)
	}
	return code, nil
}

type ProblemDetails struct {
	Type, Title       string
	Status            int
	Code              string
	Detail, Instance  string
	TraceID           string
}

type DokandarError struct {
	Code       string
	Message    string
	Detail     string
	HTTPStatus int
}

func (e *DokandarError) Error() string { return e.Message }

func NewValidationError(code, message string) *DokandarError {
	return &DokandarError{Code: code, Message: message, HTTPStatus: 400}
}
func NewBusinessError(code, message string) *DokandarError {
	return &DokandarError{Code: code, Message: message, HTTPStatus: 409}
}
func NewInfrastructureError(code, message string) *DokandarError {
	return &DokandarError{Code: code, Message: message, HTTPStatus: 503}
}
