// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

using System.Text;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi;

/// <summary>Platform API Documentation Standard helper. Wires OpenAPI + Swagger UI identically for every
/// service: OpenAPI doc "v1", JSON at /swagger/v1/swagger.json, UI at /docs, a Bearer (JWT) security
/// scheme, and unique schema ids. Services call AddDkdApiDocs(title) + UseDkdApiDocs() — no per-service
/// Swagger configuration. The native tool (Swashbuckle) is an implementation detail of this helper.</summary>
public static class ApiDocs
{
    /// <summary>PL-08: the single pinned OpenAPI version emitted by every service's /swagger doc.</summary>
    public const string OpenApiVersion = "3.1.0";

    /// <summary>The Microsoft.OpenApi spec version corresponding to <see cref="OpenApiVersion"/>.</summary>
    public const OpenApiSpecVersion SpecVersion = OpenApiSpecVersion.OpenApi3_1;

    public static IServiceCollection AddDkdApiDocs(this IServiceCollection services, string title)
    {
        services.AddEndpointsApiExplorer();
        services.AddSwaggerGen(c =>
        {
            c.SwaggerDoc("v1", new OpenApiInfo { Title = title, Version = "v1", Description = title + " REST API." });
            c.CustomSchemaIds(t => t.FullName!.Replace("+", "."));   // unique schema ids (avoid collisions)
            c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
            {
                Type = SecuritySchemeType.Http,
                Scheme = "bearer",
                BearerFormat = "JWT",
                Description = "JWT bearer token (injected by the API gateway in production).",
            });
        });
        return services;
    }

    // PL-08: the OpenAPI 3.1 spec line is emitted by Microsoft.OpenApi as "3.1.1"; normalise the
    // declared version token to the single pinned OpenApiVersion so every language's /swagger doc
    // reads an identical "3.1.0" (removes the cross-language 3.0.1 / 3.0.3 / 3.1 drift).
    private static readonly Regex OpenApiVersionToken =
        new("\"openapi\"\\s*:\\s*\"3\\.1\\.\\d+\"", RegexOptions.Compiled);

    public static IApplicationBuilder UseDkdApiDocs(this IApplicationBuilder app)
    {
        app.Use(NormalizeOpenApiVersion);                    // PL-08: pin the emitted version to 3.1.0
        app.UseSwagger(o => o.OpenApiVersion = SpecVersion); // pin to the OpenAPI 3.1 spec line
        app.UseSwaggerUI(o =>
        {
            o.SwaggerEndpoint("/swagger/v1/swagger.json", "v1");
            o.RoutePrefix = "docs";                        // UI at /docs
        });
        return app;
    }

    // Buffers the /swagger/*.json response and rewrites the declared OpenAPI version token to the
    // pinned OpenApiVersion. Scoped to the OpenAPI document path only; every other request passes through.
    private static async Task NormalizeOpenApiVersion(HttpContext ctx, Func<Task> next)
    {
        var path = ctx.Request.Path;
        if (!path.StartsWithSegments("/swagger") || !path.Value!.EndsWith(".json", StringComparison.Ordinal))
        {
            await next();
            return;
        }

        var original = ctx.Response.Body;
        using var buffer = new MemoryStream();
        ctx.Response.Body = buffer;
        try
        {
            await next();
            buffer.Seek(0, SeekOrigin.Begin);
            var body = await new StreamReader(buffer).ReadToEndAsync();
            body = OpenApiVersionToken.Replace(body, $"\"openapi\": \"{OpenApiVersion}\"", 1);
            var bytes = Encoding.UTF8.GetBytes(body);
            ctx.Response.Body = original;
            ctx.Response.ContentLength = bytes.Length;
            await ctx.Response.Body.WriteAsync(bytes);
        }
        finally
        {
            ctx.Response.Body = original;
        }
    }
}
