// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

using System.Collections.Generic;

/// <summary>Common DTOs: the {success,data,error,meta} envelope, cursor pagination, trace/audit metadata.</summary>
public sealed record PageMeta(string? NextCursor = null, bool HasMore = false, int Limit = 0);
public sealed record TraceMetadata(string? TraceId = null, string? SpanId = null, string? CorrelationId = null);
public sealed record AuditMetadata(string? ActorDid = null, long OccurredAtMs = 0, string? RequestId = null);
public sealed record Meta(PageMeta? Page = null, TraceMetadata? Trace = null, IReadOnlyDictionary<string, object>? Extra = null);

public sealed record Response<T>(bool Success, T? Data = default, ProblemDetails? Error = null, Meta? Meta = null)
{
    public static Response<T> Ok(T data, Meta? meta = null) => new(true, data, null, meta);
    public static Response<T> Fail(ProblemDetails error, Meta? meta = null) => new(false, default, error, meta);
}

public sealed record Page<T>(IReadOnlyList<T> Items, PageMeta PageInfo);
