// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

using System.Collections.Generic;

/// <summary>Canonical enum families (glossary.yaml; FR-IDN-310). Values transcribed verbatim.</summary>
public static class KycTiers
{
    public const string V0 = "V0";
    public const string V1 = "V1";
    public const string V2 = "V2";
    public const string V3 = "V3";
    public static readonly IReadOnlyList<string> All = new[] { V0, V1, V2, V3 };
}

public static class FraudDetectors
{
    public const string HOARDING = "HOARDING";
    public const string PASSPORTFORGERY = "PASSPORT_FORGERY";
    public const string GHOSTSPLIT = "GHOST_SPLIT";
    public const string MFSSTRUCTURING = "MFS_STRUCTURING";
    public const string SUBSIDYDUP = "SUBSIDY_DUP";
    public const string CIRCULARTRADE = "CIRCULAR_TRADE";
    public const string VELOCITYANOMALY = "VELOCITY_ANOMALY";
    public const string GEOIMPOSSIBLE = "GEO_IMPOSSIBLE";
    public const string COLLUSIONRING = "COLLUSION_RING";
    public static readonly IReadOnlyList<string> All = new[] { HOARDING, PASSPORTFORGERY, GHOSTSPLIT, MFSSTRUCTURING, SUBSIDYDUP, CIRCULARTRADE, VELOCITYANOMALY, GEOIMPOSSIBLE, COLLUSIONRING };
    // NOTE: contract marks this family non-exhaustive (illustrative).
}

public static class FraudCaseStates
{
    public const string OPEN = "OPEN";
    public const string INVESTIGATING = "INVESTIGATING";
    public const string SUBSTANTIATED = "SUBSTANTIATED";
    public const string ENFORCED = "ENFORCED";
    public const string DISMISSED = "DISMISSED";
    public static readonly IReadOnlyList<string> All = new[] { OPEN, INVESTIGATING, SUBSTANTIATED, ENFORCED, DISMISSED };
    // NOTE: contract marks this family non-exhaustive (illustrative).
}

public static class EnforcementActions
{
    public const string WARN = "WARN";
    public const string RESTRICTLISTING = "RESTRICT_LISTING";
    public const string SUSPEND = "SUSPEND";
    public const string BLACKLIST = "BLACKLIST";
    public const string LICENSEREVOKE = "LICENSE_REVOKE";
    public static readonly IReadOnlyList<string> All = new[] { WARN, RESTRICTLISTING, SUSPEND, BLACKLIST, LICENSEREVOKE };
    // NOTE: contract marks this family non-exhaustive (illustrative).
}

public static class OversightRoles
{
    public const string ANALYST = "ANALYST";
    public const string INVESTIGATOR = "INVESTIGATOR";
    public const string ENFORCEMENTOFFICER = "ENFORCEMENT_OFFICER";
    public const string APPROVER = "APPROVER";
    public const string SUPERADMIN = "SUPER_ADMIN";
    public static readonly IReadOnlyList<string> All = new[] { ANALYST, INVESTIGATOR, ENFORCEMENTOFFICER, APPROVER, SUPERADMIN };
    // NOTE: contract marks this family non-exhaustive (illustrative).
}

public static class PartyActorCodes
{
    public const string FARIA = "FARIA";
    public const string WHOLESALER = "WHOLESALER";
    public const string RETAIL = "RETAIL";
    public const string GOV = "GOV";
    public const string PERSON = "PERSON";
    public const string ORG = "ORG";
    public static readonly IReadOnlyList<string> All = new[] { FARIA, WHOLESALER, RETAIL, GOV, PERSON, ORG };
    // NOTE: contract marks this family non-exhaustive (illustrative).
}

public static class CommodityUnits
{
    public const string Seer = "seer";
    public const string Maund = "maund";
    public const string Bosta = "bosta";
    public static readonly IReadOnlyList<string> All = new[] { Seer, Maund, Bosta };
    // NOTE: contract marks this family non-exhaustive (illustrative).
}
