// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

/// <summary>Strongly-typed identifiers (ids.yaml). No raw-string IDs.</summary>
public abstract class PrefixedId
{
    public string Value { get; }
    protected PrefixedId(string value, string prefix)
    {
        if (value is null || !value.StartsWith(prefix) || value.Length <= prefix.Length)
            throw new ArgumentException($"{GetType().Name} must start with '{prefix}' and carry a body");
        Value = value;
    }
    public override string ToString() => Value;
    public override bool Equals(object? o) => o is not null && o.GetType() == GetType() && ((PrefixedId)o).Value == Value;
    public override int GetHashCode() => System.HashCode.Combine(GetType(), Value);
}

public sealed class DID : PrefixedId
{
    public const string Prefix = "did:dokandar:";
    public const int OwnerContext = 1; // identity
    public const bool Immutable = true;
    public DID(string value) : base(value, Prefix) { }
}

public sealed class PPID : PrefixedId
{
    public const string Prefix = "PP-";
    public const int OwnerContext = 3; // custody
    public const bool Immutable = false;
    public PPID(string value) : base(value, Prefix) { }
}

public sealed class GPID : PrefixedId
{
    public const string Prefix = "GP-";
    public const int OwnerContext = 2; // catalog
    public const bool Immutable = false;
    public GPID(string value) : base(value, Prefix) { }
}

public sealed class ORD : PrefixedId
{
    public const string Prefix = "ORD-";
    public const int OwnerContext = 6; // b2c
    public const bool Immutable = false;
    public ORD(string value) : base(value, Prefix) { }
}

public sealed class TRD : PrefixedId
{
    public const string Prefix = "TRD-";
    public const int OwnerContext = 7; // b2b
    public const bool Immutable = false;
    public TRD(string value) : base(value, Prefix) { }
}

public sealed class WLT : PrefixedId
{
    public const string Prefix = "WLT-";
    public const int OwnerContext = 8; // finance
    public const bool Immutable = false;
    public WLT(string value) : base(value, Prefix) { }
}

public sealed class ESC : PrefixedId
{
    public const string Prefix = "ESC-";
    public const int OwnerContext = 8; // finance
    public const bool Immutable = false;
    public ESC(string value) : base(value, Prefix) { }
}

public sealed class TXN : PrefixedId
{
    public const string Prefix = "TXN-";
    public const int OwnerContext = 8; // finance
    public const bool Immutable = false;
    public TXN(string value) : base(value, Prefix) { }
}

public sealed class SHP : PrefixedId
{
    public const string Prefix = "SHP-";
    public const int OwnerContext = 9; // logistics
    public const bool Immutable = false;
    public SHP(string value) : base(value, Prefix) { }
}

public sealed class NTF : PrefixedId
{
    public const string Prefix = "NTF-";
    public const int OwnerContext = 13; // platform
    public const bool Immutable = false;
    public NTF(string value) : base(value, Prefix) { }
}

public sealed class MFSA : PrefixedId
{
    public const string Prefix = "MFSA-";
    public const int OwnerContext = 8; // finance
    public const bool Immutable = false;
    public MFSA(string value) : base(value, Prefix) { }
}
