// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

/// <summary>Validation utilities.</summary>
public static class Validation
{
    public static bool ValidateTopic(string name) => Topics.Meta.ContainsKey(name);
    public static Money ValidateMoney(long poisha) => new(poisha);
}
