// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

import java.util.Set;
import java.util.regex.Pattern;

/** Error taxonomy (error-codes.yaml): dokandar.<context>.<category>.<reason> (RFC-7807).
  * Concrete codes are NEEDS-INFO in frozen contracts; builder + slug enum + ProblemDetails +
  * typed exceptions only — never a fabricated code list. */
public final class Errors {
    private Errors() {}

    public enum ContextSlug {
        IDENTITY("identity"), CATALOG("catalog"), CUSTODY("custody"), PROVENANCE("provenance"), INVENTORY("inventory"), B2C("b2c"), B2B("b2b"), FINANCE("finance"), LOGISTICS("logistics"), FRAUD("fraud"), GOVERNMENT("government"), ANALYTICS("analytics"), PLATFORM("platform"), EDGE("edge");
        public final String value;
        ContextSlug(String value) { this.value = value; }
    }

    private static final Set<String> SLUGS = Set.of("identity", "catalog", "custody", "provenance", "inventory", "b2c", "b2b", "finance", "logistics", "fraud", "government", "analytics", "platform", "edge");
    private static final Pattern CODE = Pattern.compile("^dokandar\\.([a-z]+)\\.([a-z0-9_]+)\\.([a-z0-9_]+)$");

    public static String errorCode(String context, String category, String reason) {
        String code = "dokandar." + context + "." + category + "." + reason;
        if (!SLUGS.contains(context)) throw new IllegalArgumentException("unknown context slug: " + context);
        if (!CODE.matcher(code).matches()) throw new IllegalArgumentException("error code violates taxonomy: " + code);
        return code;
    }

    public record ProblemDetails(String type, String title, int status, String code,
                                 String detail, String instance, String traceId) {}

    public static class DokandarException extends RuntimeException {
        public final String code; public final int httpStatus; public final String detail;
        public DokandarException(String code, String message, int httpStatus, String detail) {
            super(message); this.code = code; this.httpStatus = httpStatus; this.detail = detail;
        }
    }
    public static final class ValidationException extends DokandarException {
        public ValidationException(String code, String message) { super(code, message, 400, null); } }
    public static final class BusinessException extends DokandarException {
        public BusinessException(String code, String message) { super(code, message, 409, null); } }
    public static final class InfrastructureException extends DokandarException {
        public InfrastructureException(String code, String message) { super(code, message, 503, null); } }
}
