// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

import java.util.HashMap;
import java.util.Map;

/** Security helpers: access principles, JWT claim names, correlation/trace propagation.
  * Role families are the canonical glossary enums (Enums). Permission MATRIX is NEEDS-INFO. */
public final class Security {
    private Security() {}

    public static final Map<String, String> PRINCIPLES = Map.ofEntries(
        Map.entry("R1-custody-sole-writer", "Only custody-ledger-svc writes custody.*; all others are read-only consumers."),
        Map.entry("R2-finance-isolation", "Finance DB reachable only by Finance; DID->wallet resolution happens inside Finance."),
        Map.entry("R4-four-eyes", "Finance/Custody/Fraud/Government mutations require two DISTINCT human approvers (approver2 != approver1); only an enumerated narrow reversible-hold set is autonomous."),
        Map.entry("R5-government-readonly", "Government has SELECT-only grants; intervenes on operational aggregates only via audited four-eyes directives."),
        Map.entry("read-only-contexts", "Provenance(#4), Inventory(#5 vs custody), Analytics(#12) are read-only projections; never write the source of truth."),
        Map.entry("pii-confinement", "PII lives only in Identity(#1); other contexts resolve via the Identity OHS; payloads carry IDs only (R6).")
    );

    public static final class JwtClaims {
        private JwtClaims() {}
        public static final String SUBJECT_DID = "sub", KYC_TIER = "kyc_tier", ROLES = "roles", CORRELATION_ID = "cid";
    }

    public static final class CorrelationContext {
        public final String correlationId, traceId, actorDid;
        public CorrelationContext(String correlationId, String traceId, String actorDid) {
            this.correlationId = correlationId; this.traceId = traceId; this.actorDid = actorDid;
        }
        public Map<String, String> headers() {
            var h = new HashMap<String, String>();
            if (correlationId != null) h.put("x-correlation-id", correlationId);
            if (traceId != null) h.put("traceparent", traceId);
            return h;
        }
    }
}
