// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

import java.util.List;
import java.util.Map;

/** Kafka topics + RabbitMQ queues (messaging.yaml). Cross-context = Kafka only (R6). */
public final class Topics {
    private Topics() {}
    public record TopicMeta(String name, int producer, String key, List<Integer> consumers,
                            String context, String aggregate, String event, int version) {}

    public static final String IDENTITY_PARTY_PARTY_REGISTERED_V1 = "identity.party.PartyRegistered.v1";
    public static final String IDENTITY_PARTY_KYCAPPROVED_V1 = "identity.party.KYCApproved.v1";
    public static final String IDENTITY_PARTY_KYCTIER_CHANGED_V1 = "identity.party.KYCTierChanged.v1";
    public static final String IDENTITY_PARTY_KYCREJECTED_V1 = "identity.party.KYCRejected.v1";
    public static final String IDENTITY_PARTY_PARTY_SUSPENDED_V1 = "identity.party.PartySuspended.v1";
    public static final String IDENTITY_PARTY_PARTY_REACTIVATED_V1 = "identity.party.PartyReactivated.v1";
    public static final String CATALOG_PRODUCT_PRODUCT_CREATED_V1 = "catalog.product.ProductCreated.v1";
    public static final String CATALOG_PRODUCT_PRODUCT_PUBLISHED_V1 = "catalog.product.ProductPublished.v1";
    public static final String CATALOG_PRODUCT_PRODUCT_DEPRECATED_V1 = "catalog.product.ProductDeprecated.v1";
    public static final String CATALOG_PRODUCT_PRODUCT_PRICE_RULE_ADDED_V1 = "catalog.product.ProductPriceRuleAdded.v1";
    public static final String CATALOG_PRODUCT_PRODUCT_MASTER_DATA_UPDATED_V1 = "catalog.product.ProductMasterDataUpdated.v1";
    public static final String CUSTODY_PASSPORT_CUSTODY_INITIALIZED_V1 = "custody.passport.CustodyInitialized.v1";
    public static final String CUSTODY_PASSPORT_CUSTODY_TRANSFERRED_V1 = "custody.passport.CustodyTransferred.v1";
    public static final String CUSTODY_PASSPORT_CUSTODY_SPLIT_V1 = "custody.passport.CustodySplit.v1";
    public static final String CUSTODY_PASSPORT_CUSTODY_MERGED_V1 = "custody.passport.CustodyMerged.v1";
    public static final String CUSTODY_PASSPORT_PRODUCT_RECALLED_V1 = "custody.passport.ProductRecalled.v1";
    public static final String CUSTODY_PASSPORT_CUSTODIAL_SIGNED_V1 = "custody.passport.CustodialSigned.v1";
    public static final String B2C_ORDER_ORDER_PLACED_V1 = "b2c.order.OrderPlaced.v1";
    public static final String B2C_ORDER_PAYMENT_CONFIRMED_V1 = "b2c.order.PaymentConfirmed.v1";
    public static final String B2C_ORDER_ORDER_PROCESSING_STARTED_V1 = "b2c.order.OrderProcessingStarted.v1";
    public static final String B2C_ORDER_ORDER_SHIPPED_V1 = "b2c.order.OrderShipped.v1";
    public static final String B2C_ORDER_ORDER_DELIVERED_V1 = "b2c.order.OrderDelivered.v1";
    public static final String B2C_ORDER_ORDER_CANCELLED_V1 = "b2c.order.OrderCancelled.v1";
    public static final String B2C_ORDER_ORDER_REFUNDED_V1 = "b2c.order.OrderRefunded.v1";
    public static final String B2B_TRADEORDER_TRADE_ORDER_CREATED_V1 = "b2b.tradeorder.TradeOrderCreated.v1";
    public static final String B2B_TRADEORDER_MARGIN_POSTED_V1 = "b2b.tradeorder.MarginPosted.v1";
    public static final String B2B_TRADEORDER_TRADE_ACTIVATED_V1 = "b2b.tradeorder.TradeActivated.v1";
    public static final String B2B_TRADEORDER_SETTLEMENT_INITIATED_V1 = "b2b.tradeorder.SettlementInitiated.v1";
    public static final String B2B_TRADEORDER_TRADE_SETTLED_V1 = "b2b.tradeorder.TradeSettled.v1";
    public static final String B2B_TRADEORDER_TRADE_DISPUTED_V1 = "b2b.tradeorder.TradeDisputed.v1";
    public static final String B2B_TRADEORDER_TRADE_CANCELLED_V1 = "b2b.tradeorder.TradeCancelled.v1";
    public static final String FINANCE_WALLET_WALLET_CREATED_V1 = "finance.wallet.WalletCreated.v1";
    public static final String FINANCE_WALLET_MFSACCOUNT_REGISTERED_V1 = "finance.wallet.MFSAccountRegistered.v1";
    public static final String FINANCE_WALLET_MFSACCOUNT_VERIFIED_V1 = "finance.wallet.MFSAccountVerified.v1";
    public static final String FINANCE_WALLET_WALLET_CREDITED_V1 = "finance.wallet.WalletCredited.v1";
    public static final String FINANCE_WALLET_WALLET_DEBITED_V1 = "finance.wallet.WalletDebited.v1";
    public static final String FINANCE_WALLET_WALLET_FROZEN_V1 = "finance.wallet.WalletFrozen.v1";
    public static final String FINANCE_WALLET_MFSWITHDRAWAL_INITIATED_V1 = "finance.wallet.MFSWithdrawalInitiated.v1";
    public static final String FINANCE_WALLET_MFSWITHDRAWAL_CONFIRMED_V1 = "finance.wallet.MFSWithdrawalConfirmed.v1";
    public static final String FINANCE_WALLET_MFSWITHDRAWAL_FAILED_V1 = "finance.wallet.MFSWithdrawalFailed.v1";
    public static final String FINANCE_ESCROW_ESCROW_CREATED_V1 = "finance.escrow.EscrowCreated.v1";
    public static final String FINANCE_ESCROW_ESCROW_RELEASED_V1 = "finance.escrow.EscrowReleased.v1";
    public static final String FINANCE_ESCROW_SETTLEMENT_HOLD_RELEASED_V1 = "finance.escrow.SettlementHoldReleased.v1";
    public static final String FINANCE_ESCROW_ESCROW_REVERSED_V1 = "finance.escrow.EscrowReversed.v1";
    public static final String LOGISTICS_SHIPMENT_SHIPMENT_CREATED_V1 = "logistics.shipment.ShipmentCreated.v1";
    public static final String LOGISTICS_SHIPMENT_RIDER_ASSIGNED_V1 = "logistics.shipment.RiderAssigned.v1";
    public static final String LOGISTICS_SHIPMENT_PICKUP_RECORDED_V1 = "logistics.shipment.PickupRecorded.v1";
    public static final String LOGISTICS_SHIPMENT_DELIVERY_RECORDED_V1 = "logistics.shipment.DeliveryRecorded.v1";
    public static final String LOGISTICS_SHIPMENT_SHIPMENT_CANCELLED_V1 = "logistics.shipment.ShipmentCancelled.v1";
    public static final String LOGISTICS_SHIPMENT_DELIVERY_FAILED_V1 = "logistics.shipment.DeliveryFailed.v1";
    public static final String FRAUD_ENFORCEMENT_FRAUD_SIGNAL_RAISED_V1 = "fraud.enforcement.FraudSignalRaised.v1";
    public static final String FRAUD_ENFORCEMENT_ACCOUNT_HELD_V1 = "fraud.enforcement.AccountHeld.v1";
    public static final String FRAUD_ENFORCEMENT_ACCOUNT_HOLD_RELEASED_V1 = "fraud.enforcement.AccountHoldReleased.v1";
    public static final String GOVERNMENT_OVERSIGHT_RECALL_DIRECTIVE_ISSUED_V1 = "government.oversight.RecallDirectiveIssued.v1";
    public static final String GOVERNMENT_OVERSIGHT_TRADE_FREEZE_DIRECTIVE_V1 = "government.oversight.TradeFreezeDirective.v1";
    public static final String GOVERNMENT_OVERSIGHT_WALLET_FREEZE_DIRECTIVE_V1 = "government.oversight.WalletFreezeDirective.v1";
    public static final String PLATFORM_SCHEDULER_COOLING_OFF_EXPIRED_V1 = "platform.scheduler.CoolingOffExpired.v1";
    public static final String PLATFORM_SCHEDULER_ESCROW_EXPIRED_V1 = "platform.scheduler.EscrowExpired.v1";
    public static final String PLATFORM_SCHEDULER_NILROLLUP_REFRESH_V1 = "platform.scheduler.NILRollupRefresh.v1";

    public static final String QUEUE_IDENTITY_KYC_VERIFICATION = "identity.kyc-verification";
    public static final String QUEUE_IDENTITY_OTP_DISPATCH = "identity.otp-dispatch";
    public static final String QUEUE_CATALOG_IMAGE_PROCESSING = "catalog.image-processing";
    public static final String QUEUE_CATALOG_SEARCH_INDEX = "catalog.search-index";
    public static final String QUEUE_B2C_ORDER_CONFIRMATION = "b2c.order-confirmation";
    public static final String QUEUE_B2C_STOCK_RESERVE = "b2c.stock-reserve";
    public static final String QUEUE_LOGISTICS_RIDER_ASSIGNMENT = "logistics.rider-assignment";
    public static final String QUEUE_LOGISTICS_DELIVERY_NOTIFICATION = "logistics.delivery-notification";
    public static final String QUEUE_FRAUD_HOLD_APPROVAL_REQUEST = "fraud.hold-approval-request";
    public static final String QUEUE_PLATFORM_NOTIFICATION_DISPATCH = "platform.notification-dispatch";

    public static final Map<String, TopicMeta> META = Map.ofEntries(
        Map.entry("identity.party.PartyRegistered.v1", new TopicMeta("identity.party.PartyRegistered.v1", 1, "DID", List.of(8, 13), "identity", "party", "PartyRegistered", 1)),
        Map.entry("identity.party.KYCApproved.v1", new TopicMeta("identity.party.KYCApproved.v1", 1, "DID", List.of(6, 7, 10, 11), "identity", "party", "KYCApproved", 1)),
        Map.entry("identity.party.KYCTierChanged.v1", new TopicMeta("identity.party.KYCTierChanged.v1", 1, "DID", List.of(6, 7, 10, 11), "identity", "party", "KYCTierChanged", 1)),
        Map.entry("identity.party.KYCRejected.v1", new TopicMeta("identity.party.KYCRejected.v1", 1, "DID", List.of(13), "identity", "party", "KYCRejected", 1)),
        Map.entry("identity.party.PartySuspended.v1", new TopicMeta("identity.party.PartySuspended.v1", 1, "DID", List.of(6, 7, 8, 10, 11), "identity", "party", "PartySuspended", 1)),
        Map.entry("identity.party.PartyReactivated.v1", new TopicMeta("identity.party.PartyReactivated.v1", 1, "DID", List.of(6, 7, 8), "identity", "party", "PartyReactivated", 1)),
        Map.entry("catalog.product.ProductCreated.v1", new TopicMeta("catalog.product.ProductCreated.v1", 2, "GPID", List.of(12), "catalog", "product", "ProductCreated", 1)),
        Map.entry("catalog.product.ProductPublished.v1", new TopicMeta("catalog.product.ProductPublished.v1", 2, "GPID", List.of(6, 12), "catalog", "product", "ProductPublished", 1)),
        Map.entry("catalog.product.ProductDeprecated.v1", new TopicMeta("catalog.product.ProductDeprecated.v1", 2, "GPID", List.of(5, 6, 7, 12), "catalog", "product", "ProductDeprecated", 1)),
        Map.entry("catalog.product.ProductPriceRuleAdded.v1", new TopicMeta("catalog.product.ProductPriceRuleAdded.v1", 2, "GPID", List.of(6, 12), "catalog", "product", "ProductPriceRuleAdded", 1)),
        Map.entry("catalog.product.ProductMasterDataUpdated.v1", new TopicMeta("catalog.product.ProductMasterDataUpdated.v1", 2, "GPID", List.of(12), "catalog", "product", "ProductMasterDataUpdated", 1)),
        Map.entry("custody.passport.CustodyInitialized.v1", new TopicMeta("custody.passport.CustodyInitialized.v1", 3, "PPID", List.of(2, 4, 5, 11, 12), "custody", "passport", "CustodyInitialized", 1)),
        Map.entry("custody.passport.CustodyTransferred.v1", new TopicMeta("custody.passport.CustodyTransferred.v1", 3, "PPID", List.of(2, 4, 5, 8, 11, 12), "custody", "passport", "CustodyTransferred", 1)),
        Map.entry("custody.passport.CustodySplit.v1", new TopicMeta("custody.passport.CustodySplit.v1", 3, "parentPpid", List.of(2, 4, 5, 12), "custody", "passport", "CustodySplit", 1)),
        Map.entry("custody.passport.CustodyMerged.v1", new TopicMeta("custody.passport.CustodyMerged.v1", 3, "newPpid", List.of(2, 4, 5, 12), "custody", "passport", "CustodyMerged", 1)),
        Map.entry("custody.passport.ProductRecalled.v1", new TopicMeta("custody.passport.ProductRecalled.v1", 3, "recallId", List.of(2, 4, 5, 6, 7, 11, 12), "custody", "passport", "ProductRecalled", 1)),
        Map.entry("custody.passport.CustodialSigned.v1", new TopicMeta("custody.passport.CustodialSigned.v1", 3, "PPID", List.of(4, 12), "custody", "passport", "CustodialSigned", 1)),
        Map.entry("b2c.order.OrderPlaced.v1", new TopicMeta("b2c.order.OrderPlaced.v1", 6, "ORD", List.of(8, 9, 10, 11, 12), "b2c", "order", "OrderPlaced", 1)),
        Map.entry("b2c.order.PaymentConfirmed.v1", new TopicMeta("b2c.order.PaymentConfirmed.v1", 6, "ORD", List.of(12), "b2c", "order", "PaymentConfirmed", 1)),
        Map.entry("b2c.order.OrderProcessingStarted.v1", new TopicMeta("b2c.order.OrderProcessingStarted.v1", 6, "ORD", List.of(9, 12), "b2c", "order", "OrderProcessingStarted", 1)),
        Map.entry("b2c.order.OrderShipped.v1", new TopicMeta("b2c.order.OrderShipped.v1", 6, "ORD", List.of(12), "b2c", "order", "OrderShipped", 1)),
        Map.entry("b2c.order.OrderDelivered.v1", new TopicMeta("b2c.order.OrderDelivered.v1", 6, "ORD", List.of(8, 12), "b2c", "order", "OrderDelivered", 1)),
        Map.entry("b2c.order.OrderCancelled.v1", new TopicMeta("b2c.order.OrderCancelled.v1", 6, "ORD", List.of(8, 9, 12), "b2c", "order", "OrderCancelled", 1)),
        Map.entry("b2c.order.OrderRefunded.v1", new TopicMeta("b2c.order.OrderRefunded.v1", 6, "ORD", List.of(12), "b2c", "order", "OrderRefunded", 1)),
        Map.entry("b2b.tradeorder.TradeOrderCreated.v1", new TopicMeta("b2b.tradeorder.TradeOrderCreated.v1", 7, "TRD", List.of(8, 10, 11, 12), "b2b", "tradeorder", "TradeOrderCreated", 1)),
        Map.entry("b2b.tradeorder.MarginPosted.v1", new TopicMeta("b2b.tradeorder.MarginPosted.v1", 7, "TRD", List.of(8, 12), "b2b", "tradeorder", "MarginPosted", 1)),
        Map.entry("b2b.tradeorder.TradeActivated.v1", new TopicMeta("b2b.tradeorder.TradeActivated.v1", 7, "TRD", List.of(8, 12), "b2b", "tradeorder", "TradeActivated", 1)),
        Map.entry("b2b.tradeorder.SettlementInitiated.v1", new TopicMeta("b2b.tradeorder.SettlementInitiated.v1", 7, "TRD", List.of(8, 12), "b2b", "tradeorder", "SettlementInitiated", 1)),
        Map.entry("b2b.tradeorder.TradeSettled.v1", new TopicMeta("b2b.tradeorder.TradeSettled.v1", 7, "TRD", List.of(11, 12), "b2b", "tradeorder", "TradeSettled", 1)),
        Map.entry("b2b.tradeorder.TradeDisputed.v1", new TopicMeta("b2b.tradeorder.TradeDisputed.v1", 7, "TRD", List.of(8, 11, 12), "b2b", "tradeorder", "TradeDisputed", 1)),
        Map.entry("b2b.tradeorder.TradeCancelled.v1", new TopicMeta("b2b.tradeorder.TradeCancelled.v1", 7, "TRD", List.of(8, 12), "b2b", "tradeorder", "TradeCancelled", 1)),
        Map.entry("finance.wallet.WalletCreated.v1", new TopicMeta("finance.wallet.WalletCreated.v1", 8, "WLT", List.of(12), "finance", "wallet", "WalletCreated", 1)),
        Map.entry("finance.wallet.MFSAccountRegistered.v1", new TopicMeta("finance.wallet.MFSAccountRegistered.v1", 8, "WLT", List.of(12), "finance", "wallet", "MFSAccountRegistered", 1)),
        Map.entry("finance.wallet.MFSAccountVerified.v1", new TopicMeta("finance.wallet.MFSAccountVerified.v1", 8, "WLT", List.of(12), "finance", "wallet", "MFSAccountVerified", 1)),
        Map.entry("finance.wallet.WalletCredited.v1", new TopicMeta("finance.wallet.WalletCredited.v1", 8, "WLT", List.of(11, 12), "finance", "wallet", "WalletCredited", 1)),
        Map.entry("finance.wallet.WalletDebited.v1", new TopicMeta("finance.wallet.WalletDebited.v1", 8, "WLT", List.of(11, 12), "finance", "wallet", "WalletDebited", 1)),
        Map.entry("finance.wallet.WalletFrozen.v1", new TopicMeta("finance.wallet.WalletFrozen.v1", 8, "WLT", List.of(11, 12), "finance", "wallet", "WalletFrozen", 1)),
        Map.entry("finance.wallet.MFSWithdrawalInitiated.v1", new TopicMeta("finance.wallet.MFSWithdrawalInitiated.v1", 8, "TXN", List.of(12), "finance", "wallet", "MFSWithdrawalInitiated", 1)),
        Map.entry("finance.wallet.MFSWithdrawalConfirmed.v1", new TopicMeta("finance.wallet.MFSWithdrawalConfirmed.v1", 8, "TXN", List.of(11, 12), "finance", "wallet", "MFSWithdrawalConfirmed", 1)),
        Map.entry("finance.wallet.MFSWithdrawalFailed.v1", new TopicMeta("finance.wallet.MFSWithdrawalFailed.v1", 8, "TXN", List.of(12), "finance", "wallet", "MFSWithdrawalFailed", 1)),
        Map.entry("finance.escrow.EscrowCreated.v1", new TopicMeta("finance.escrow.EscrowCreated.v1", 8, "ESC", List.of(6, 12), "finance", "escrow", "EscrowCreated", 1)),
        Map.entry("finance.escrow.EscrowReleased.v1", new TopicMeta("finance.escrow.EscrowReleased.v1", 8, "ESC", List.of(7, 11, 12), "finance", "escrow", "EscrowReleased", 1)),
        Map.entry("finance.escrow.SettlementHoldReleased.v1", new TopicMeta("finance.escrow.SettlementHoldReleased.v1", 8, "ESC", List.of(11, 12), "finance", "escrow", "SettlementHoldReleased", 1)),
        Map.entry("finance.escrow.EscrowReversed.v1", new TopicMeta("finance.escrow.EscrowReversed.v1", 8, "ESC", List.of(6, 11, 12), "finance", "escrow", "EscrowReversed", 1)),
        Map.entry("logistics.shipment.ShipmentCreated.v1", new TopicMeta("logistics.shipment.ShipmentCreated.v1", 9, "SHP", List.of(6, 12), "logistics", "shipment", "ShipmentCreated", 1)),
        Map.entry("logistics.shipment.RiderAssigned.v1", new TopicMeta("logistics.shipment.RiderAssigned.v1", 9, "SHP", List.of(6, 12), "logistics", "shipment", "RiderAssigned", 1)),
        Map.entry("logistics.shipment.PickupRecorded.v1", new TopicMeta("logistics.shipment.PickupRecorded.v1", 9, "SHP", List.of(12), "logistics", "shipment", "PickupRecorded", 1)),
        Map.entry("logistics.shipment.DeliveryRecorded.v1", new TopicMeta("logistics.shipment.DeliveryRecorded.v1", 9, "SHP", List.of(6, 8, 12), "logistics", "shipment", "DeliveryRecorded", 1)),
        Map.entry("logistics.shipment.ShipmentCancelled.v1", new TopicMeta("logistics.shipment.ShipmentCancelled.v1", 9, "SHP", List.of(6, 8, 12), "logistics", "shipment", "ShipmentCancelled", 1)),
        Map.entry("logistics.shipment.DeliveryFailed.v1", new TopicMeta("logistics.shipment.DeliveryFailed.v1", 9, "SHP", List.of(6, 12), "logistics", "shipment", "DeliveryFailed", 1)),
        Map.entry("fraud.enforcement.FraudSignalRaised.v1", new TopicMeta("fraud.enforcement.FraudSignalRaised.v1", 10, "DID", List.of(11, 12), "fraud", "enforcement", "FraudSignalRaised", 1)),
        Map.entry("fraud.enforcement.AccountHeld.v1", new TopicMeta("fraud.enforcement.AccountHeld.v1", 10, "DID", List.of(6, 7, 8, 11), "fraud", "enforcement", "AccountHeld", 1)),
        Map.entry("fraud.enforcement.AccountHoldReleased.v1", new TopicMeta("fraud.enforcement.AccountHoldReleased.v1", 10, "DID", List.of(6, 7, 8, 11), "fraud", "enforcement", "AccountHoldReleased", 1)),
        Map.entry("government.oversight.RecallDirectiveIssued.v1", new TopicMeta("government.oversight.RecallDirectiveIssued.v1", 11, "recallId", List.of(3), "government", "oversight", "RecallDirectiveIssued", 1)),
        Map.entry("government.oversight.TradeFreezeDirective.v1", new TopicMeta("government.oversight.TradeFreezeDirective.v1", 11, "directiveId", List.of(7), "government", "oversight", "TradeFreezeDirective", 1)),
        Map.entry("government.oversight.WalletFreezeDirective.v1", new TopicMeta("government.oversight.WalletFreezeDirective.v1", 11, "directiveId", List.of(8), "government", "oversight", "WalletFreezeDirective", 1)),
        Map.entry("platform.scheduler.CoolingOffExpired.v1", new TopicMeta("platform.scheduler.CoolingOffExpired.v1", 13, "ESC", List.of(8), "platform", "scheduler", "CoolingOffExpired", 1)),
        Map.entry("platform.scheduler.EscrowExpired.v1", new TopicMeta("platform.scheduler.EscrowExpired.v1", 13, "ESC", List.of(8), "platform", "scheduler", "EscrowExpired", 1)),
        Map.entry("platform.scheduler.NILRollupRefresh.v1", new TopicMeta("platform.scheduler.NILRollupRefresh.v1", 13, "GPID", List.of(5), "platform", "scheduler", "NILRollupRefresh", 1))
    );

    public static TopicMeta topicMeta(String name) {
        TopicMeta m = META.get(name);
        if (m == null) throw new IllegalArgumentException("unknown topic: " + name);
        return m;
    }
}
