// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

/// <summary>Canon-named operational constants (configuration.yaml). Values verbatim from canon.</summary>
public static class Config
{
    public const long COOLING_OFF_WINDOW = 259200000L; // 72h - finance.escrow
    public const long ESCROW_ABANDON_TTL = 604800000L; // 7d - finance.escrow
    public const long NIL_ROLLUP_MAX_LAG = 60000L; // 60s - inventory.nil
    public const long B2_B_DELIVERY_MIN_LEAD = 86400000L; // 24h - b2b.contractterms
    public const long MONEY_CUSTODY_RPO = 0L; //  - finance+custody
}
