// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

/// <summary>Error taxonomy (error-codes.yaml): dokandar.&lt;context&gt;.&lt;category&gt;.&lt;reason&gt; (RFC-7807).
/// Concrete codes are NEEDS-INFO in frozen contracts; builder + slug set + ProblemDetails + typed
/// exceptions only - never a fabricated code list.</summary>
public static class ContextSlug
{
    public const string Identity = "identity";
    public const string Catalog = "catalog";
    public const string Custody = "custody";
    public const string Provenance = "provenance";
    public const string Inventory = "inventory";
    public const string B2c = "b2c";
    public const string B2b = "b2b";
    public const string Finance = "finance";
    public const string Logistics = "logistics";
    public const string Fraud = "fraud";
    public const string Government = "government";
    public const string Analytics = "analytics";
    public const string Platform = "platform";
    public const string Edge = "edge";
}

public static class Errors
{
    private static readonly HashSet<string> Slugs = new() { "identity", "catalog", "custody", "provenance", "inventory", "b2c", "b2b", "finance", "logistics", "fraud", "government", "analytics", "platform", "edge" };
    private static readonly Regex CodeRe = new(@"^dokandar\.([a-z]+)\.([a-z0-9_]+)\.([a-z0-9_]+)$");

    public static string ErrorCode(string context, string category, string reason)
    {
        var code = $"dokandar.{context}.{category}.{reason}";
        if (!Slugs.Contains(context)) throw new ArgumentException($"unknown context slug: {context}");
        if (!CodeRe.IsMatch(code)) throw new ArgumentException($"error code violates taxonomy: {code}");
        return code;
    }
}

public sealed record ProblemDetails(string Type, string Title, int Status, string Code,
                                    string? Detail = null, string? Instance = null, string? TraceId = null);

public class DokandarException : Exception
{
    public string Code { get; }
    public int HttpStatus { get; }
    public string? Detail { get; }
    public DokandarException(string code, string message, int httpStatus = 500, string? detail = null) : base(message)
    {
        Code = code; HttpStatus = httpStatus; Detail = detail;
    }
}
public sealed class ValidationException : DokandarException
{ public ValidationException(string code, string message) : base(code, message, 400) { } }
public sealed class BusinessException : DokandarException
{ public BusinessException(string code, string message) : base(code, message, 409) { } }
public sealed class InfrastructureException : DokandarException
{ public InfrastructureException(string code, string message) : base(code, message, 503) { } }
