// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

/// <summary>Money is int64 poisha (DM type conventions). Float/decimal money is impossible by type.</summary>
public readonly record struct Money(long Poisha)
{
    public const long PoishaPerBdt = 100L;
    public static Money OfBdt(long bdt) => new(bdt * PoishaPerBdt);
}

/// <summary>Unix milliseconds, UTC (int64).</summary>
public readonly record struct Timestamp(long EpochMs);
