// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

namespace Dkd.Platform;

public static class Provenance
{
    public const string Generator = "dkdgen";
    public const string GeneratorVersion = "1.0.0";
    public const string ContractVersion = "1.0.0";
    public const string BuildTime = "2026-06-29T00:00:00Z";
    public const string BuildCommit = "source";
}
