// Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;
// no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files.

namespace IdentitySvc.Messaging;

/// <summary>
/// Event-bus abstractions for the Dokandar Published Language (R6). Concrete Kafka (Redpanda) and
/// RabbitMQ client implementations are the integration point — wire them in the adapters layer.
/// No business events are defined here; topic names and payload schemas come from
/// dkd-contracts-spine/messaging.yaml.
/// </summary>

/// <summary>Handler delegate invoked by <see cref="IConsumer"/> for each received message.</summary>
public delegate Task MessageHandler(
    string topic,
    string key,
    ReadOnlyMemory<byte> payload,
    CancellationToken ct);

/// <summary>
/// Event publisher abstraction (Kafka cross-context Published Language + RabbitMQ intra-context).
/// Implementations must guarantee at-least-once delivery via the transactional outbox pattern.
/// </summary>
public interface IPublisher : IAsyncDisposable
{
    Task PublishAsync(
        string topic,
        string key,
        ReadOnlyMemory<byte> payload,
        CancellationToken ct = default);
}

/// <summary>
/// Event consumer abstraction. Implementations must provide inbox deduplication on event_id
/// and per-topic DLQ with replay (park-and-freeze on poison messages — never silently drop).
/// </summary>
public interface IConsumer : IAsyncDisposable
{
    Task SubscribeAsync(
        IReadOnlyList<string> topics,
        MessageHandler handler,
        CancellationToken ct = default);
}

/// <summary>
/// No-op publisher: safe default for local runs without a broker. Replace with the Redpanda
/// (Kafka-compatible) driver at the integration point for all non-local environments.
/// </summary>
public sealed class NoopPublisher : IPublisher
{
    public Task PublishAsync(string topic, string key, ReadOnlyMemory<byte> payload, CancellationToken ct = default)
        => Task.CompletedTask;

    public ValueTask DisposeAsync() => ValueTask.CompletedTask;
}

/// <summary>No-op consumer: mirrors NoopPublisher for local development parity.</summary>
public sealed class NoopConsumer : IConsumer
{
    public Task SubscribeAsync(IReadOnlyList<string> topics, MessageHandler handler, CancellationToken ct = default)
        => Task.CompletedTask;

    public ValueTask DisposeAsync() => ValueTask.CompletedTask;
}
