// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package dkdplatform

// Security helpers: access principles, JWT claim names, correlation/trace propagation.
// Role families are the canonical glossary enums (enums.go). The permission MATRIX is
// NEEDS-INFO (permissions.yaml) — principle constants only.

var Principles = map[string]string{
	"R1-custody-sole-writer": "Only custody-ledger-svc writes custody.*; all others are read-only consumers.",
	"R2-finance-isolation": "Finance DB reachable only by Finance; DID->wallet resolution happens inside Finance.",
	"R4-four-eyes": "Finance/Custody/Fraud/Government mutations require two DISTINCT human approvers (approver2 != approver1); only an enumerated narrow reversible-hold set is autonomous.",
	"R5-government-readonly": "Government has SELECT-only grants; intervenes on operational aggregates only via audited four-eyes directives.",
	"read-only-contexts": "Provenance(#4), Inventory(#5 vs custody), Analytics(#12) are read-only projections; never write the source of truth.",
	"pii-confinement": "PII lives only in Identity(#1); other contexts resolve via the Identity OHS; payloads carry IDs only (R6).",
}

const (
	JwtClaimSubjectDID    = "sub"
	JwtClaimKycTier       = "kyc_tier"
	JwtClaimRoles         = "roles"
	JwtClaimCorrelationID = "cid"
)

type CorrelationContext struct {
	CorrelationID string
	TraceID       string
	ActorDID      string
}

func (c CorrelationContext) Headers() map[string]string {
	h := map[string]string{}
	if c.CorrelationID != "" {
		h["x-correlation-id"] = c.CorrelationID
	}
	if c.TraceID != "" {
		h["traceparent"] = c.TraceID
	}
	return h
}
