// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package apidocs

import (
	"net/http"
	"strings"
)

// OpenAPIVersion pins the emitted OpenAPI document version to the source-of-truth
// (sdk/openapi/dkd-platform.openapi.json → "3.1.0"), fixing the prior
// 3.0.x drift across language SDKs (PL-08).
const OpenAPIVersion = "3.1.0"

// DocsCSP is the Content-Security-Policy for the Swagger UI paths (allows the UI assets it loads).
func DocsCSP() string {
	return "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; " +
		"style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: https://cdn.jsdelivr.net; " +
		"font-src 'self' https://cdn.jsdelivr.net; connect-src 'self'"
}

// IsDocsPath reports whether the request path targets the Swagger UI or the OpenAPI document.
func IsDocsPath(path string) bool {
	return strings.HasPrefix(path, "/docs") || strings.HasPrefix(path, "/swagger")
}

// Register wires /docs (Swagger UI) and /swagger/v1/swagger.json (OpenAPI document) onto the mux.
func Register(mux *http.ServeMux, title string) {
	spec := strings.ReplaceAll(openapiTemplate, "__TITLE__", title)
	mux.HandleFunc("/swagger/v1/swagger.json", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(spec))
	})
	mux.HandleFunc("/docs", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(swaggerUIHTML))
	})
}

const swaggerUIHTML = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>API Documentation</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui.css"></head>
<body><div id="swagger-ui"></div>
<script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist/swagger-ui-bundle.js"></script>
<script>window.ui = SwaggerUIBundle({url: "/swagger/v1/swagger.json", dom_id: "#swagger-ui"});</script>
</body></html>`

const openapiTemplate = `{
  "openapi": "3.1.0",
  "info": {"title": "__TITLE__", "version": "v1", "description": "__TITLE__ REST API."},
  "paths": {
    "/health": {"get": {"tags": ["HealthEndpoints"], "operationId": "getHealth", "summary": "Health probe", "responses": {"200": {"description": "OK", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Envelope"}}}}}}},
    "/live": {"get": {"tags": ["HealthEndpoints"], "operationId": "getLive", "summary": "Liveness probe", "responses": {"200": {"description": "OK"}}}},
    "/ready": {"get": {"tags": ["HealthEndpoints"], "operationId": "getReady", "summary": "Readiness probe", "responses": {"200": {"description": "OK"}, "503": {"description": "Not ready", "content": {"application/problem+json": {"schema": {"$ref": "#/components/schemas/ProblemDetails"}}}}}}},
    "/version": {"get": {"tags": ["HealthEndpoints"], "operationId": "getVersion", "summary": "Version", "responses": {"200": {"description": "OK", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Envelope"}}}}}}}
  },
  "components": {
    "schemas": {
      "Envelope": {"type": "object", "properties": {"success": {"type": "boolean"}, "data": {"type": "object", "nullable": true}, "error": {"$ref": "#/components/schemas/ProblemDetails"}, "meta": {"type": "object", "nullable": true}}},
      "ProblemDetails": {"type": "object", "description": "RFC-7807 problem+json", "properties": {"type": {"type": "string"}, "title": {"type": "string"}, "status": {"type": "integer"}, "detail": {"type": "string"}, "instance": {"type": "string"}, "code": {"type": "string"}}}
    },
    "securitySchemes": {"Bearer": {"type": "http", "scheme": "bearer", "bearerFormat": "JWT", "description": "JWT bearer token (injected by the API gateway in production)."}}
  }
}`
