"""dkdscaffold.render — shared emission infrastructure for runtime emitters (Writer + naming)."""
from __future__ import annotations
import os
import re


class Writer:
    """Writes generated service files. Optionally stamps a provenance banner in the file's comment syntax."""

    def __init__(self, out_dir: str, comment: str | None = None):
        self.out_dir = out_dir
        self.comment = comment
        self.written: list[str] = []

    def banner(self) -> str:
        c = self.comment
        return "\n".join([
            "%s Generated by dkd-scaffold from the canonical service blueprint. Infrastructure only;" % c,
            "%s no business logic. Safe to extend; re-scaffolding overwrites only blueprint-owned files." % c,
        ])

    def write(self, rel_path: str, body: str, banner: bool = False) -> None:
        full = os.path.join(self.out_dir, rel_path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        content = (self.banner() + "\n\n" + body) if (banner and self.comment) else body
        if not content.endswith("\n"):
            content += "\n"
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)
        self.written.append(rel_path)


def _words(s: str) -> list[str]:
    s = s.replace("-", "_").replace(".", "_")
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", s)
    return [w for w in s.split("_") if w]


def pascal(s: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in _words(s))


def camel(s: str) -> str:
    p = pascal(s)
    return p[:1].lower() + p[1:] if p else p


def snake(s: str) -> str:
    return "_".join(w.lower() for w in _words(s))


def kebab(s: str) -> str:
    return "-".join(w.lower() for w in _words(s))
