// DO NOT EDIT — generated by dkdgen v1.0.0 from dkd-contracts-spine@1.0.0
// The frozen contracts are the only source of truth. Regenerate via `dkdgen generate`.
// build_time=2026-06-29T00:00:00Z build_commit=source

package com.dokandar.platform;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SdkTest {
    @Test void provenance() { assertEquals("1.0.0", Provenance.CONTRACT_VERSION); }

    @Test void idsTypedAndValidated() {
        var d = new Ids.DID("did:dokandar:abc");
        assertEquals("did:dokandar:abc", d.toString());
        assertTrue(Ids.DID.IMMUTABLE);
        assertEquals(1, Ids.DID.OWNER_CONTEXT);
        assertThrows(IllegalArgumentException.class, () -> new Ids.PPID("did:dokandar:x"));
    }

    @Test void topics() {
        assertEquals(59, Topics.META.size());
        assertEquals(3, Topics.topicMeta("custody.passport.CustodyInitialized.v1").producer());
    }

    @Test void money() { assertEquals(5000L, new Money(5000L).poisha); }

    @Test void errorCode() {
        assertEquals("dokandar.finance.idempotency.duplicate_key",
                     Errors.errorCode("finance", "idempotency", "duplicate_key"));
        assertThrows(IllegalArgumentException.class, () -> Errors.errorCode("frobnicate", "x", "y"));
    }
}
