// identity-party-ohs (api-registry.yaml, owner_ctx 1, root_id DID). The Party read model and the
// ONLY PII resolver (R7). Concrete .proto signatures were NEEDS-INFO in the frozen spine; this is the
// MVP surface (ResolveParty + GetKycTier). Additional ops (Authorize/IssueSigningCert) are Phase 2.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/identity_party_ohs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityPartyOhs_ResolveParty_FullMethodName = "/dokandar.identity.ohs.v1.IdentityPartyOhs/ResolveParty"
	IdentityPartyOhs_GetKycTier_FullMethodName   = "/dokandar.identity.ohs.v1.IdentityPartyOhs/GetKycTier"
)

// IdentityPartyOhsClient is the client API for IdentityPartyOhs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityPartyOhsClient interface {
	// Resolve the canonical Party read model for a DID. As the sole PII resolver, this returns phone.
	ResolveParty(ctx context.Context, in *ResolvePartyRequest, opts ...grpc.CallOption) (*PartyReply, error)
	// Lightweight KYC-tier lookup for authorization/gating by other contexts.
	GetKycTier(ctx context.Context, in *GetKycTierRequest, opts ...grpc.CallOption) (*KycTierReply, error)
}

type identityPartyOhsClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityPartyOhsClient(cc grpc.ClientConnInterface) IdentityPartyOhsClient {
	return &identityPartyOhsClient{cc}
}

func (c *identityPartyOhsClient) ResolveParty(ctx context.Context, in *ResolvePartyRequest, opts ...grpc.CallOption) (*PartyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyReply)
	err := c.cc.Invoke(ctx, IdentityPartyOhs_ResolveParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityPartyOhsClient) GetKycTier(ctx context.Context, in *GetKycTierRequest, opts ...grpc.CallOption) (*KycTierReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KycTierReply)
	err := c.cc.Invoke(ctx, IdentityPartyOhs_GetKycTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityPartyOhsServer is the server API for IdentityPartyOhs service.
// All implementations must embed UnimplementedIdentityPartyOhsServer
// for forward compatibility.
type IdentityPartyOhsServer interface {
	// Resolve the canonical Party read model for a DID. As the sole PII resolver, this returns phone.
	ResolveParty(context.Context, *ResolvePartyRequest) (*PartyReply, error)
	// Lightweight KYC-tier lookup for authorization/gating by other contexts.
	GetKycTier(context.Context, *GetKycTierRequest) (*KycTierReply, error)
	mustEmbedUnimplementedIdentityPartyOhsServer()
}

// UnimplementedIdentityPartyOhsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityPartyOhsServer struct{}

func (UnimplementedIdentityPartyOhsServer) ResolveParty(context.Context, *ResolvePartyRequest) (*PartyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveParty not implemented")
}
func (UnimplementedIdentityPartyOhsServer) GetKycTier(context.Context, *GetKycTierRequest) (*KycTierReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKycTier not implemented")
}
func (UnimplementedIdentityPartyOhsServer) mustEmbedUnimplementedIdentityPartyOhsServer() {}
func (UnimplementedIdentityPartyOhsServer) testEmbeddedByValue()                          {}

// UnsafeIdentityPartyOhsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityPartyOhsServer will
// result in compilation errors.
type UnsafeIdentityPartyOhsServer interface {
	mustEmbedUnimplementedIdentityPartyOhsServer()
}

func RegisterIdentityPartyOhsServer(s grpc.ServiceRegistrar, srv IdentityPartyOhsServer) {
	// If the following call pancis, it indicates UnimplementedIdentityPartyOhsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityPartyOhs_ServiceDesc, srv)
}

func _IdentityPartyOhs_ResolveParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPartyOhsServer).ResolveParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityPartyOhs_ResolveParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPartyOhsServer).ResolveParty(ctx, req.(*ResolvePartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityPartyOhs_GetKycTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKycTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPartyOhsServer).GetKycTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityPartyOhs_GetKycTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPartyOhsServer).GetKycTier(ctx, req.(*GetKycTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityPartyOhs_ServiceDesc is the grpc.ServiceDesc for IdentityPartyOhs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityPartyOhs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dokandar.identity.ohs.v1.IdentityPartyOhs",
	HandlerType: (*IdentityPartyOhsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveParty",
			Handler:    _IdentityPartyOhs_ResolveParty_Handler,
		},
		{
			MethodName: "GetKycTier",
			Handler:    _IdentityPartyOhs_GetKycTier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/identity_party_ohs.proto",
}
