// identity-party-ohs (api-registry.yaml, owner_ctx 1, root_id DID). The Party read model and the
// ONLY PII resolver (R7). Concrete .proto signatures were NEEDS-INFO in the frozen spine; this is the
// MVP surface (ResolveParty + GetKycTier). Additional ops (Authorize/IssueSigningCert) are Phase 2.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/identity_party_ohs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolvePartyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *ResolvePartyRequest) Reset() {
	*x = ResolvePartyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_identity_party_ohs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolvePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePartyRequest) ProtoMessage() {}

func (x *ResolvePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_party_ohs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePartyRequest.ProtoReflect.Descriptor instead.
func (*ResolvePartyRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_party_ohs_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvePartyRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetKycTierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *GetKycTierRequest) Reset() {
	*x = GetKycTierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_identity_party_ohs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKycTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycTierRequest) ProtoMessage() {}

func (x *GetKycTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_party_ohs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycTierRequest.ProtoReflect.Descriptor instead.
func (*GetKycTierRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_party_ohs_proto_rawDescGZIP(), []int{1}
}

func (x *GetKycTierRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type PartyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found        bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Did          string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	KycTier      string `protobuf:"bytes,3,opt,name=kyc_tier,json=kycTier,proto3" json:"kyc_tier,omitempty"` // UNVERIFIED|BASIC|FULL|BUSINESS
	Status       string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                  // ACTIVE|SUSPENDED|DELETED
	Locale       string `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	Phone        string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"` // PII — resolved only via this OHS (R6/R7)
	KycSubmitted bool   `protobuf:"varint,7,opt,name=kyc_submitted,json=kycSubmitted,proto3" json:"kyc_submitted,omitempty"`
	Bin          string `protobuf:"bytes,8,opt,name=bin,proto3" json:"bin,omitempty"`
	CreatedAt    int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    int64  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *PartyReply) Reset() {
	*x = PartyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_identity_party_ohs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReply) ProtoMessage() {}

func (x *PartyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_party_ohs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReply.ProtoReflect.Descriptor instead.
func (*PartyReply) Descriptor() ([]byte, []int) {
	return file_proto_identity_party_ohs_proto_rawDescGZIP(), []int{2}
}

func (x *PartyReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *PartyReply) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *PartyReply) GetKycTier() string {
	if x != nil {
		return x.KycTier
	}
	return ""
}

func (x *PartyReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PartyReply) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *PartyReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PartyReply) GetKycSubmitted() bool {
	if x != nil {
		return x.KycSubmitted
	}
	return false
}

func (x *PartyReply) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

func (x *PartyReply) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PartyReply) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type KycTierReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found   bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Did     string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	KycTier string `protobuf:"bytes,3,opt,name=kyc_tier,json=kycTier,proto3" json:"kyc_tier,omitempty"`
}

func (x *KycTierReply) Reset() {
	*x = KycTierReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_identity_party_ohs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KycTierReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycTierReply) ProtoMessage() {}

func (x *KycTierReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_party_ohs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycTierReply.ProtoReflect.Descriptor instead.
func (*KycTierReply) Descriptor() ([]byte, []int) {
	return file_proto_identity_party_ohs_proto_rawDescGZIP(), []int{3}
}

func (x *KycTierReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *KycTierReply) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *KycTierReply) GetKycTier() string {
	if x != nil {
		return x.KycTier
	}
	return ""
}

var File_proto_identity_party_ohs_proto protoreflect.FileDescriptor

var file_proto_identity_party_ohs_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x6f, 0x68, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x18, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x27, 0x0a, 0x13, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4b, 0x79, 0x63, 0x54, 0x69, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x8a, 0x02, 0x0a, 0x0a, 0x50,
	0x61, 0x72, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x79, 0x63, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x79, 0x63, 0x54, 0x69, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6b, 0x79, 0x63, 0x5f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6b, 0x79, 0x63, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x51, 0x0a, 0x0c, 0x4b, 0x79, 0x63, 0x54, 0x69,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x6b, 0x79, 0x63, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6b, 0x79, 0x63, 0x54, 0x69, 0x65, 0x72, 0x32, 0xda, 0x01, 0x0a, 0x10, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x61, 0x72, 0x74, 0x79, 0x4f, 0x68, 0x73, 0x12,
	0x63, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12,
	0x2d, 0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x61, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4b, 0x79, 0x63, 0x54, 0x69,
	0x65, 0x72, 0x12, 0x2b, 0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4b, 0x79, 0x63, 0x54, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x64, 0x6f, 0x6b, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x6f, 0x68, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x79, 0x63, 0x54, 0x69,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x67, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x2d, 0x79, 0x65, 0x61, 0x72,
	0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x33, 0x33, 0x35, 0x34, 0x31, 0x32, 0x37, 0x2f,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x64, 0x79, 0x2d, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2d, 0x73,
	0x76, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0xaa, 0x02, 0x10,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x76, 0x63, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_identity_party_ohs_proto_rawDescOnce sync.Once
	file_proto_identity_party_ohs_proto_rawDescData = file_proto_identity_party_ohs_proto_rawDesc
)

func file_proto_identity_party_ohs_proto_rawDescGZIP() []byte {
	file_proto_identity_party_ohs_proto_rawDescOnce.Do(func() {
		file_proto_identity_party_ohs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_identity_party_ohs_proto_rawDescData)
	})
	return file_proto_identity_party_ohs_proto_rawDescData
}

var file_proto_identity_party_ohs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_identity_party_ohs_proto_goTypes = []any{
	(*ResolvePartyRequest)(nil), // 0: dokandar.identity.ohs.v1.ResolvePartyRequest
	(*GetKycTierRequest)(nil),   // 1: dokandar.identity.ohs.v1.GetKycTierRequest
	(*PartyReply)(nil),          // 2: dokandar.identity.ohs.v1.PartyReply
	(*KycTierReply)(nil),        // 3: dokandar.identity.ohs.v1.KycTierReply
}
var file_proto_identity_party_ohs_proto_depIdxs = []int32{
	0, // 0: dokandar.identity.ohs.v1.IdentityPartyOhs.ResolveParty:input_type -> dokandar.identity.ohs.v1.ResolvePartyRequest
	1, // 1: dokandar.identity.ohs.v1.IdentityPartyOhs.GetKycTier:input_type -> dokandar.identity.ohs.v1.GetKycTierRequest
	2, // 2: dokandar.identity.ohs.v1.IdentityPartyOhs.ResolveParty:output_type -> dokandar.identity.ohs.v1.PartyReply
	3, // 3: dokandar.identity.ohs.v1.IdentityPartyOhs.GetKycTier:output_type -> dokandar.identity.ohs.v1.KycTierReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_identity_party_ohs_proto_init() }
func file_proto_identity_party_ohs_proto_init() {
	if File_proto_identity_party_ohs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_identity_party_ohs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ResolvePartyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_identity_party_ohs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetKycTierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_identity_party_ohs_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PartyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_identity_party_ohs_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*KycTierReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_identity_party_ohs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_identity_party_ohs_proto_goTypes,
		DependencyIndexes: file_proto_identity_party_ohs_proto_depIdxs,
		MessageInfos:      file_proto_identity_party_ohs_proto_msgTypes,
	}.Build()
	File_proto_identity_party_ohs_proto = out.File
	file_proto_identity_party_ohs_proto_rawDesc = nil
	file_proto_identity_party_ohs_proto_goTypes = nil
	file_proto_identity_party_ohs_proto_depIdxs = nil
}
